-- ==============================================================
-- Generated by Vitis HLS v2023.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity eye_feature_eye_feature_Pipeline_FRAME_X is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    in_stream_TVALID : IN STD_LOGIC;
    c_cx0 : IN STD_LOGIC_VECTOR (31 downto 0);
    ex1_1 : IN STD_LOGIC_VECTOR (31 downto 0);
    c_valid_2 : IN STD_LOGIC_VECTOR (0 downto 0);
    rev84 : IN STD_LOGIC_VECTOR (0 downto 0);
    icmp_ln523_1 : IN STD_LOGIC_VECTOR (0 downto 0);
    in_stream_TDATA : IN STD_LOGIC_VECTOR (31 downto 0);
    in_stream_TREADY : OUT STD_LOGIC;
    in_stream_TKEEP : IN STD_LOGIC_VECTOR (3 downto 0);
    in_stream_TSTRB : IN STD_LOGIC_VECTOR (3 downto 0);
    in_stream_TLAST : IN STD_LOGIC_VECTOR (0 downto 0);
    pixel_format : IN STD_LOGIC_VECTOR (31 downto 0);
    cmp6_i : IN STD_LOGIC_VECTOR (0 downto 0);
    c_cx0_3 : IN STD_LOGIC_VECTOR (31 downto 0);
    ex0_1 : IN STD_LOGIC_VECTOR (31 downto 0);
    c_valid_3 : IN STD_LOGIC_VECTOR (0 downto 0);
    rev : IN STD_LOGIC_VECTOR (0 downto 0);
    icmp_ln522_1 : IN STD_LOGIC_VECTOR (0 downto 0);
    frame_width : IN STD_LOGIC_VECTOR (31 downto 0);
    empty_55 : IN STD_LOGIC_VECTOR (12 downto 0);
    zext_ln540_1 : IN STD_LOGIC_VECTOR (12 downto 0);
    hist0_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    hist0_ce0 : OUT STD_LOGIC;
    hist0_we0 : OUT STD_LOGIC;
    hist0_d0 : OUT STD_LOGIC_VECTOR (15 downto 0);
    hist0_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
    hist0_1_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    hist0_1_ce0 : OUT STD_LOGIC;
    hist0_1_we0 : OUT STD_LOGIC;
    hist0_1_d0 : OUT STD_LOGIC_VECTOR (15 downto 0);
    hist0_1_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
    hist0_2_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    hist0_2_ce0 : OUT STD_LOGIC;
    hist0_2_we0 : OUT STD_LOGIC;
    hist0_2_d0 : OUT STD_LOGIC_VECTOR (15 downto 0);
    hist0_2_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
    hist0_3_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    hist0_3_ce0 : OUT STD_LOGIC;
    hist0_3_we0 : OUT STD_LOGIC;
    hist0_3_d0 : OUT STD_LOGIC_VECTOR (15 downto 0);
    hist0_3_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
    empty : IN STD_LOGIC_VECTOR (12 downto 0);
    zext_ln546_1 : IN STD_LOGIC_VECTOR (12 downto 0);
    hist1_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    hist1_ce0 : OUT STD_LOGIC;
    hist1_we0 : OUT STD_LOGIC;
    hist1_d0 : OUT STD_LOGIC_VECTOR (15 downto 0);
    hist1_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
    hist1_1_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    hist1_1_ce0 : OUT STD_LOGIC;
    hist1_1_we0 : OUT STD_LOGIC;
    hist1_1_d0 : OUT STD_LOGIC_VECTOR (15 downto 0);
    hist1_1_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
    hist1_2_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    hist1_2_ce0 : OUT STD_LOGIC;
    hist1_2_we0 : OUT STD_LOGIC;
    hist1_2_d0 : OUT STD_LOGIC_VECTOR (15 downto 0);
    hist1_2_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
    hist1_3_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    hist1_3_ce0 : OUT STD_LOGIC;
    hist1_3_we0 : OUT STD_LOGIC;
    hist1_3_d0 : OUT STD_LOGIC_VECTOR (15 downto 0);
    hist1_3_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
    pix0_address1 : OUT STD_LOGIC_VECTOR (12 downto 0);
    pix0_ce1 : OUT STD_LOGIC;
    pix0_we1 : OUT STD_LOGIC;
    pix0_d1 : OUT STD_LOGIC_VECTOR (7 downto 0);
    pix1_address1 : OUT STD_LOGIC_VECTOR (12 downto 0);
    pix1_ce1 : OUT STD_LOGIC;
    pix1_we1 : OUT STD_LOGIC;
    pix1_d1 : OUT STD_LOGIC_VECTOR (7 downto 0) );
end;


architecture behav of eye_feature_eye_feature_Pipeline_FRAME_X is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_ST_fsm_pp0_stage1 : STD_LOGIC_VECTOR (1 downto 0) := "10";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv31_0 : STD_LOGIC_VECTOR (30 downto 0) := "0000000000000000000000000000000";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv2_1 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_const_lv2_2 : STD_LOGIC_VECTOR (1 downto 0) := "10";
    constant ap_const_lv2_3 : STD_LOGIC_VECTOR (1 downto 0) := "11";
    constant ap_const_lv31_280 : STD_LOGIC_VECTOR (30 downto 0) := "0000000000000000000001010000000";
    constant ap_const_lv31_1 : STD_LOGIC_VECTOR (30 downto 0) := "0000000000000000000000000000001";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_D : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001101";
    constant ap_const_lv32_F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001111";
    constant ap_const_lv32_B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001011";
    constant ap_const_lv32_9 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001001";
    constant ap_const_lv32_A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001010";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_10 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010000";
    constant ap_const_lv32_17 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010111";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv16_96 : STD_LOGIC_VECTOR (15 downto 0) := "0000000010010110";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv16_1 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000001";
    constant ap_const_lv15_4D : STD_LOGIC_VECTOR (14 downto 0) := "000000001001101";
    constant ap_const_lv13_1D : STD_LOGIC_VECTOR (12 downto 0) := "0000000011101";
    constant ap_const_lv13_80 : STD_LOGIC_VECTOR (12 downto 0) := "0000010000000";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (1 downto 0) := "01";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_CS_fsm_pp0_stage1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage1 : signal is "none";
    signal icmp_ln532_reg_1037 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln534_reg_1047 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_predicate_op67_read_state2 : BOOLEAN;
    signal ap_block_state2_pp0_stage1_iter0 : BOOLEAN;
    signal ap_block_pp0_stage1_subdone : BOOLEAN;
    signal ap_condition_exit_pp0_iter0_stage1 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal in_stream_TDATA_blk_n : STD_LOGIC;
    signal ap_block_pp0_stage1 : BOOLEAN;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal cmp6_i_read_read_fu_252_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln532_fu_452_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln532_reg_1037_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln532_fu_464_p1 : STD_LOGIC_VECTOR (12 downto 0);
    signal trunc_ln532_reg_1041 : STD_LOGIC_VECTOR (12 downto 0);
    signal trunc_ln532_reg_1041_pp0_iter1_reg : STD_LOGIC_VECTOR (12 downto 0);
    signal trunc_ln532_reg_1041_pp0_iter2_reg : STD_LOGIC_VECTOR (12 downto 0);
    signal icmp_ln534_fu_472_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln534_reg_1047_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln124_fu_478_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln124_reg_1051 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln124_reg_1051_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln124_reg_1051_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln124_1_fu_484_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln124_1_reg_1056 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln124_1_reg_1056_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln124_1_reg_1056_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln538_1_fu_526_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln538_1_reg_1061 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln538_1_reg_1061_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln538_1_reg_1061_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln544_1_fu_568_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln544_1_reg_1065 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln544_1_reg_1065_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln544_1_reg_1065_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal gray_7_fu_583_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal gray_7_reg_1069 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_block_pp0_stage1_11001 : BOOLEAN;
    signal gray_7_reg_1069_pp0_iter1_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal lshr_ln4_reg_1074 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_s_reg_1079 : STD_LOGIC_VECTOR (4 downto 0);
    signal g_field_fu_627_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal g_field_reg_1084 : STD_LOGIC_VECTOR (7 downto 0);
    signal g_field_reg_1084_pp0_iter1_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal lshr_ln107_1_reg_1089 : STD_LOGIC_VECTOR (2 downto 0);
    signal trunc_ln107_fu_645_p1 : STD_LOGIC_VECTOR (4 downto 0);
    signal trunc_ln107_reg_1094 : STD_LOGIC_VECTOR (4 downto 0);
    signal g_reg_1104 : STD_LOGIC_VECTOR (7 downto 0);
    signal r_field_fu_681_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal r_field_reg_1119 : STD_LOGIC_VECTOR (7 downto 0);
    signal mul_ln118_2_fu_707_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal mul_ln118_5_fu_713_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_962_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln118_reg_1144 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_970_p3 : STD_LOGIC_VECTOR (12 downto 0);
    signal add_ln118_1_reg_1149 : STD_LOGIC_VECTOR (12 downto 0);
    signal grp_fu_978_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln118_3_reg_1154 : STD_LOGIC_VECTOR (15 downto 0);
    signal mul_ln118_7_fu_722_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln_reg_1164 : STD_LOGIC_VECTOR (1 downto 0);
    signal hist0_addr_reg_1169 : STD_LOGIC_VECTOR (3 downto 0);
    signal hist0_1_addr_reg_1174 : STD_LOGIC_VECTOR (3 downto 0);
    signal hist0_2_addr_reg_1179 : STD_LOGIC_VECTOR (3 downto 0);
    signal hist0_3_addr_reg_1184 : STD_LOGIC_VECTOR (3 downto 0);
    signal trunc_ln1_reg_1189 : STD_LOGIC_VECTOR (1 downto 0);
    signal hist1_addr_reg_1194 : STD_LOGIC_VECTOR (3 downto 0);
    signal hist1_1_addr_reg_1199 : STD_LOGIC_VECTOR (3 downto 0);
    signal hist1_2_addr_reg_1204 : STD_LOGIC_VECTOR (3 downto 0);
    signal hist1_3_addr_reg_1209 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_enable_reg_pp0_iter0_reg : STD_LOGIC := '0';
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal zext_ln540_fu_821_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln541_fu_846_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln546_fu_863_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln547_fu_888_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal x_fu_188 : STD_LOGIC_VECTOR (30 downto 0) := "0000000000000000000000000000000";
    signal add_ln532_fu_458_p2 : STD_LOGIC_VECTOR (30 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal ap_sig_allocacmp_x_2 : STD_LOGIC_VECTOR (30 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal gray_6_fu_802_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln542_fu_919_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln548_fu_952_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln532_fu_468_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal icmp_ln538_fu_490_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln538_fu_508_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln538_1_fu_502_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln538_2_fu_514_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln538_3_fu_520_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln538_fu_496_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln544_fu_532_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln544_fu_550_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln544_1_fu_544_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln544_2_fu_556_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln544_3_fu_562_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln544_fu_538_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_1_fu_617_p4 : STD_LOGIC_VECTOR (5 downto 0);
    signal lshr_ln5_fu_607_p4 : STD_LOGIC_VECTOR (1 downto 0);
    signal r_fu_653_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal b_field_fu_687_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal mul_ln118_2_fu_707_p0 : STD_LOGIC_VECTOR (7 downto 0);
    signal mul_ln118_2_fu_707_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal mul_ln118_5_fu_713_p0 : STD_LOGIC_VECTOR (7 downto 0);
    signal mul_ln118_5_fu_713_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal mul_ln118_7_fu_722_p0 : STD_LOGIC_VECTOR (7 downto 0);
    signal mul_ln118_7_fu_722_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal zext_ln118_9_fu_728_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal y_fu_731_p2 : STD_LOGIC_VECTOR (15 downto 0);
    attribute use_dsp48 : string;
    attribute use_dsp48 of y_fu_731_p2 : signal is "no";
    signal grp_fu_986_p3 : STD_LOGIC_VECTOR (12 downto 0);
    signal zext_ln118_11_fu_746_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal y_1_fu_749_p2 : STD_LOGIC_VECTOR (15 downto 0);
    attribute use_dsp48 of y_1_fu_749_p2 : signal is "no";
    signal grp_fu_995_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal y_2_fu_764_p2 : STD_LOGIC_VECTOR (15 downto 0);
    attribute use_dsp48 of y_2_fu_764_p2 : signal is "no";
    signal gray_fu_736_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal gray_2_fu_754_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal gray_4_fu_779_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal xor_ln124_fu_792_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln124_fu_797_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal gray_3_fu_769_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal gray_5_fu_785_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal sub_ln539_fu_812_p2 : STD_LOGIC_VECTOR (12 downto 0);
    signal add_ln540_fu_816_p2 : STD_LOGIC_VECTOR (12 downto 0);
    signal trunc_ln541_1_fu_836_p4 : STD_LOGIC_VECTOR (3 downto 0);
    signal sub_ln545_fu_854_p2 : STD_LOGIC_VECTOR (12 downto 0);
    signal add_ln546_fu_858_p2 : STD_LOGIC_VECTOR (12 downto 0);
    signal trunc_ln547_1_fu_878_p4 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_fu_896_p9 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_fu_896_p11 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_3_fu_929_p9 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_3_fu_929_p11 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_962_p0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_962_p1 : STD_LOGIC_VECTOR (6 downto 0);
    signal grp_fu_970_p0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_970_p1 : STD_LOGIC_VECTOR (4 downto 0);
    signal grp_fu_970_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_978_p0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_978_p1 : STD_LOGIC_VECTOR (6 downto 0);
    signal grp_fu_986_p0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_986_p1 : STD_LOGIC_VECTOR (4 downto 0);
    signal grp_fu_986_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_995_p0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_995_p1 : STD_LOGIC_VECTOR (6 downto 0);
    signal grp_fu_962_ce : STD_LOGIC;
    signal grp_fu_970_ce : STD_LOGIC;
    signal grp_fu_978_ce : STD_LOGIC;
    signal grp_fu_986_ce : STD_LOGIC;
    signal grp_fu_995_ce : STD_LOGIC;
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter1_reg : STD_LOGIC;
    signal ap_condition_exit_pp0_iter2_stage0 : STD_LOGIC;
    signal ap_idle_pp0_0to1 : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter2_reg : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_idle_pp0_1to3 : STD_LOGIC;
    signal ap_done_pending_pp0 : STD_LOGIC;
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal grp_fu_962_p00 : STD_LOGIC_VECTOR (14 downto 0);
    signal grp_fu_970_p00 : STD_LOGIC_VECTOR (12 downto 0);
    signal grp_fu_978_p00 : STD_LOGIC_VECTOR (14 downto 0);
    signal grp_fu_986_p00 : STD_LOGIC_VECTOR (12 downto 0);
    signal grp_fu_995_p00 : STD_LOGIC_VECTOR (14 downto 0);
    signal mul_ln118_2_fu_707_p00 : STD_LOGIC_VECTOR (15 downto 0);
    signal mul_ln118_5_fu_713_p00 : STD_LOGIC_VECTOR (15 downto 0);
    signal mul_ln118_7_fu_722_p00 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_condition_865 : BOOLEAN;
    signal tmp_fu_896_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_fu_896_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_fu_896_p5 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_fu_896_p7 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_3_fu_929_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_3_fu_929_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_3_fu_929_p5 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_3_fu_929_p7 : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_ce_reg : STD_LOGIC;

    component eye_feature_mul_8ns_9ns_16_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (7 downto 0);
        din1 : IN STD_LOGIC_VECTOR (8 downto 0);
        dout : OUT STD_LOGIC_VECTOR (15 downto 0) );
    end component;


    component eye_feature_sparsemux_9_2_16_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        CASE0 : STD_LOGIC_VECTOR (1 downto 0);
        din0_WIDTH : INTEGER;
        CASE1 : STD_LOGIC_VECTOR (1 downto 0);
        din1_WIDTH : INTEGER;
        CASE2 : STD_LOGIC_VECTOR (1 downto 0);
        din2_WIDTH : INTEGER;
        CASE3 : STD_LOGIC_VECTOR (1 downto 0);
        din3_WIDTH : INTEGER;
        def_WIDTH : INTEGER;
        sel_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (15 downto 0);
        din1 : IN STD_LOGIC_VECTOR (15 downto 0);
        din2 : IN STD_LOGIC_VECTOR (15 downto 0);
        din3 : IN STD_LOGIC_VECTOR (15 downto 0);
        def : IN STD_LOGIC_VECTOR (15 downto 0);
        sel : IN STD_LOGIC_VECTOR (1 downto 0);
        dout : OUT STD_LOGIC_VECTOR (15 downto 0) );
    end component;


    component eye_feature_mac_muladd_8ns_7ns_16ns_16_4_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (7 downto 0);
        din1 : IN STD_LOGIC_VECTOR (6 downto 0);
        din2 : IN STD_LOGIC_VECTOR (15 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (15 downto 0) );
    end component;


    component eye_feature_mac_muladd_8ns_5ns_8ns_13_4_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (7 downto 0);
        din1 : IN STD_LOGIC_VECTOR (4 downto 0);
        din2 : IN STD_LOGIC_VECTOR (7 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (12 downto 0) );
    end component;


    component eye_feature_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    mul_8ns_9ns_16_1_1_U9 : component eye_feature_mul_8ns_9ns_16_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 8,
        din1_WIDTH => 9,
        dout_WIDTH => 16)
    port map (
        din0 => mul_ln118_2_fu_707_p0,
        din1 => mul_ln118_2_fu_707_p1,
        dout => mul_ln118_2_fu_707_p2);

    mul_8ns_9ns_16_1_1_U10 : component eye_feature_mul_8ns_9ns_16_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 8,
        din1_WIDTH => 9,
        dout_WIDTH => 16)
    port map (
        din0 => mul_ln118_5_fu_713_p0,
        din1 => mul_ln118_5_fu_713_p1,
        dout => mul_ln118_5_fu_713_p2);

    mul_8ns_9ns_16_1_1_U11 : component eye_feature_mul_8ns_9ns_16_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 8,
        din1_WIDTH => 9,
        dout_WIDTH => 16)
    port map (
        din0 => mul_ln118_7_fu_722_p0,
        din1 => mul_ln118_7_fu_722_p1,
        dout => mul_ln118_7_fu_722_p2);

    sparsemux_9_2_16_1_1_U12 : component eye_feature_sparsemux_9_2_16_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "00",
        din0_WIDTH => 16,
        CASE1 => "01",
        din1_WIDTH => 16,
        CASE2 => "10",
        din2_WIDTH => 16,
        CASE3 => "11",
        din3_WIDTH => 16,
        def_WIDTH => 16,
        sel_WIDTH => 2,
        dout_WIDTH => 16)
    port map (
        din0 => hist0_q0,
        din1 => hist0_1_q0,
        din2 => hist0_2_q0,
        din3 => hist0_3_q0,
        def => tmp_fu_896_p9,
        sel => trunc_ln_reg_1164,
        dout => tmp_fu_896_p11);

    sparsemux_9_2_16_1_1_U13 : component eye_feature_sparsemux_9_2_16_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "00",
        din0_WIDTH => 16,
        CASE1 => "01",
        din1_WIDTH => 16,
        CASE2 => "10",
        din2_WIDTH => 16,
        CASE3 => "11",
        din3_WIDTH => 16,
        def_WIDTH => 16,
        sel_WIDTH => 2,
        dout_WIDTH => 16)
    port map (
        din0 => hist1_q0,
        din1 => hist1_1_q0,
        din2 => hist1_2_q0,
        din3 => hist1_3_q0,
        def => tmp_3_fu_929_p9,
        sel => trunc_ln1_reg_1189,
        dout => tmp_3_fu_929_p11);

    mac_muladd_8ns_7ns_16ns_16_4_1_U14 : component eye_feature_mac_muladd_8ns_7ns_16ns_16_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 8,
        din1_WIDTH => 7,
        din2_WIDTH => 16,
        dout_WIDTH => 16)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_962_p0,
        din1 => grp_fu_962_p1,
        din2 => mul_ln118_2_fu_707_p2,
        ce => grp_fu_962_ce,
        dout => grp_fu_962_p3);

    mac_muladd_8ns_5ns_8ns_13_4_1_U15 : component eye_feature_mac_muladd_8ns_5ns_8ns_13_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 8,
        din1_WIDTH => 5,
        din2_WIDTH => 8,
        dout_WIDTH => 13)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_970_p0,
        din1 => grp_fu_970_p1,
        din2 => grp_fu_970_p2,
        ce => grp_fu_970_ce,
        dout => grp_fu_970_p3);

    mac_muladd_8ns_7ns_16ns_16_4_1_U16 : component eye_feature_mac_muladd_8ns_7ns_16ns_16_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 8,
        din1_WIDTH => 7,
        din2_WIDTH => 16,
        dout_WIDTH => 16)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_978_p0,
        din1 => grp_fu_978_p1,
        din2 => mul_ln118_5_fu_713_p2,
        ce => grp_fu_978_ce,
        dout => grp_fu_978_p3);

    mac_muladd_8ns_5ns_8ns_13_4_1_U17 : component eye_feature_mac_muladd_8ns_5ns_8ns_13_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 8,
        din1_WIDTH => 5,
        din2_WIDTH => 8,
        dout_WIDTH => 13)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_986_p0,
        din1 => grp_fu_986_p1,
        din2 => grp_fu_986_p2,
        ce => grp_fu_986_ce,
        dout => grp_fu_986_p3);

    mac_muladd_8ns_7ns_16ns_16_4_1_U18 : component eye_feature_mac_muladd_8ns_7ns_16ns_16_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 8,
        din1_WIDTH => 7,
        din2_WIDTH => 16,
        dout_WIDTH => 16)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_995_p0,
        din1 => grp_fu_995_p1,
        din2 => mul_ln118_7_fu_722_p2,
        ce => grp_fu_995_ce,
        dout => grp_fu_995_p3);

    flow_control_loop_pipe_sequential_init_U : component eye_feature_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready,
        ap_done => ap_done,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage1,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_loop_exit_ready_pp0_iter2_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter0_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter0_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) then 
                    ap_enable_reg_pp0_iter0_reg <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage1)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage1_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                    ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage1_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage1_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                end if; 
            end if;
        end if;
    end process;


    ap_loop_exit_ready_pp0_iter1_reg_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_idle_pp0_0to1 = ap_const_logic_1) and (ap_const_logic_1 = ap_condition_exit_pp0_iter2_stage0))) then 
                ap_loop_exit_ready_pp0_iter1_reg <= ap_const_logic_0;
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
            end if; 
        end if;
    end process;

    ap_loop_exit_ready_pp0_iter2_reg_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_idle_pp0_0to1 = ap_const_logic_1) and (ap_const_logic_1 = ap_condition_exit_pp0_iter2_stage0))) then 
                ap_loop_exit_ready_pp0_iter2_reg <= ap_const_logic_0;
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
            end if; 
        end if;
    end process;

    x_fu_188_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_const_boolean_1 = ap_condition_865)) then 
                    x_fu_188 <= add_ln532_fu_458_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    x_fu_188 <= ap_const_lv31_0;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                add_ln118_1_reg_1149 <= grp_fu_970_p3;
                add_ln118_3_reg_1154 <= grp_fu_978_p3;
                add_ln118_reg_1144 <= grp_fu_962_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                and_ln538_1_reg_1061 <= and_ln538_1_fu_526_p2;
                and_ln538_1_reg_1061_pp0_iter1_reg <= and_ln538_1_reg_1061;
                and_ln538_1_reg_1061_pp0_iter2_reg <= and_ln538_1_reg_1061_pp0_iter1_reg;
                and_ln544_1_reg_1065 <= and_ln544_1_fu_568_p2;
                and_ln544_1_reg_1065_pp0_iter1_reg <= and_ln544_1_reg_1065;
                and_ln544_1_reg_1065_pp0_iter2_reg <= and_ln544_1_reg_1065_pp0_iter1_reg;
                icmp_ln124_1_reg_1056 <= icmp_ln124_1_fu_484_p2;
                icmp_ln124_1_reg_1056_pp0_iter1_reg <= icmp_ln124_1_reg_1056;
                icmp_ln124_1_reg_1056_pp0_iter2_reg <= icmp_ln124_1_reg_1056_pp0_iter1_reg;
                icmp_ln124_reg_1051 <= icmp_ln124_fu_478_p2;
                icmp_ln124_reg_1051_pp0_iter1_reg <= icmp_ln124_reg_1051;
                icmp_ln124_reg_1051_pp0_iter2_reg <= icmp_ln124_reg_1051_pp0_iter1_reg;
                icmp_ln532_reg_1037 <= icmp_ln532_fu_452_p2;
                icmp_ln532_reg_1037_pp0_iter1_reg <= icmp_ln532_reg_1037;
                icmp_ln534_reg_1047 <= icmp_ln534_fu_472_p2;
                icmp_ln534_reg_1047_pp0_iter1_reg <= icmp_ln534_reg_1047;
                r_field_reg_1119 <= r_field_fu_681_p3;
                trunc_ln532_reg_1041 <= trunc_ln532_fu_464_p1;
                trunc_ln532_reg_1041_pp0_iter1_reg <= trunc_ln532_reg_1041;
                trunc_ln532_reg_1041_pp0_iter2_reg <= trunc_ln532_reg_1041_pp0_iter1_reg;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then
                g_field_reg_1084 <= g_field_fu_627_p3;
                g_field_reg_1084_pp0_iter1_reg <= g_field_reg_1084;
                g_reg_1104 <= in_stream_TDATA(15 downto 8);
                gray_7_reg_1069 <= gray_7_fu_583_p1;
                gray_7_reg_1069_pp0_iter1_reg <= gray_7_reg_1069;
                hist0_1_addr_reg_1174 <= zext_ln541_fu_846_p1(4 - 1 downto 0);
                hist0_2_addr_reg_1179 <= zext_ln541_fu_846_p1(4 - 1 downto 0);
                hist0_3_addr_reg_1184 <= zext_ln541_fu_846_p1(4 - 1 downto 0);
                hist0_addr_reg_1169 <= zext_ln541_fu_846_p1(4 - 1 downto 0);
                hist1_1_addr_reg_1199 <= zext_ln547_fu_888_p1(4 - 1 downto 0);
                hist1_2_addr_reg_1204 <= zext_ln547_fu_888_p1(4 - 1 downto 0);
                hist1_3_addr_reg_1209 <= zext_ln547_fu_888_p1(4 - 1 downto 0);
                hist1_addr_reg_1194 <= zext_ln547_fu_888_p1(4 - 1 downto 0);
                lshr_ln107_1_reg_1089 <= in_stream_TDATA(4 downto 2);
                lshr_ln4_reg_1074 <= in_stream_TDATA(15 downto 13);
                tmp_s_reg_1079 <= in_stream_TDATA(15 downto 11);
                trunc_ln107_reg_1094 <= trunc_ln107_fu_645_p1;
                trunc_ln1_reg_1189 <= gray_6_fu_802_p3(3 downto 2);
                trunc_ln_reg_1164 <= gray_6_fu_802_p3(3 downto 2);
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_block_pp0_stage1_subdone, ap_block_pp0_stage0_subdone, ap_condition_exit_pp0_iter2_stage0, ap_idle_pp0_0to1, ap_idle_pp0_1to3, ap_done_pending_pp0, ap_start_int)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                if (((ap_idle_pp0_0to1 = ap_const_logic_1) and (ap_const_logic_1 = ap_condition_exit_pp0_iter2_stage0))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                elsif ((not(((ap_start_int = ap_const_logic_0) and (ap_done_pending_pp0 = ap_const_logic_0) and (ap_idle_pp0_1to3 = ap_const_logic_1))) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage1;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                end if;
            when ap_ST_fsm_pp0_stage1 => 
                if ((ap_const_boolean_0 = ap_block_pp0_stage1_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage1;
                end if;
            when others =>  
                ap_NS_fsm <= "XX";
        end case;
    end process;
    add_ln532_fu_458_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_x_2) + unsigned(ap_const_lv31_1));
    add_ln540_fu_816_p2 <= std_logic_vector(unsigned(zext_ln540_1) + unsigned(sub_ln539_fu_812_p2));
    add_ln542_fu_919_p2 <= std_logic_vector(unsigned(tmp_fu_896_p11) + unsigned(ap_const_lv16_1));
    add_ln546_fu_858_p2 <= std_logic_vector(unsigned(zext_ln546_1) + unsigned(sub_ln545_fu_854_p2));
    add_ln548_fu_952_p2 <= std_logic_vector(unsigned(tmp_3_fu_929_p11) + unsigned(ap_const_lv16_1));
    and_ln124_fu_797_p2 <= (xor_ln124_fu_792_p2 and icmp_ln124_1_reg_1056_pp0_iter2_reg);
    and_ln538_1_fu_526_p2 <= (xor_ln538_fu_496_p2 and and_ln538_3_fu_520_p2);
    and_ln538_2_fu_514_p2 <= (icmp_ln522_1 and and_ln538_fu_508_p2);
    and_ln538_3_fu_520_p2 <= (icmp_ln538_1_fu_502_p2 and and_ln538_2_fu_514_p2);
    and_ln538_fu_508_p2 <= (rev and c_valid_3);
    and_ln544_1_fu_568_p2 <= (xor_ln544_fu_538_p2 and and_ln544_3_fu_562_p2);
    and_ln544_2_fu_556_p2 <= (icmp_ln523_1 and and_ln544_fu_550_p2);
    and_ln544_3_fu_562_p2 <= (icmp_ln544_1_fu_544_p2 and and_ln544_2_fu_556_p2);
    and_ln544_fu_550_p2 <= (rev84 and c_valid_2);
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
    ap_CS_fsm_pp0_stage1 <= ap_CS_fsm(1);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage1 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage1_11001_assign_proc : process(ap_enable_reg_pp0_iter0, ap_block_state2_pp0_stage1_iter0)
    begin
                ap_block_pp0_stage1_11001 <= ((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state2_pp0_stage1_iter0));
    end process;


    ap_block_pp0_stage1_subdone_assign_proc : process(ap_enable_reg_pp0_iter0, ap_block_state2_pp0_stage1_iter0)
    begin
                ap_block_pp0_stage1_subdone <= ((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state2_pp0_stage1_iter0));
    end process;


    ap_block_state2_pp0_stage1_iter0_assign_proc : process(in_stream_TVALID, ap_predicate_op67_read_state2)
    begin
                ap_block_state2_pp0_stage1_iter0 <= ((ap_predicate_op67_read_state2 = ap_const_boolean_1) and (in_stream_TVALID = ap_const_logic_0));
    end process;


    ap_condition_865_assign_proc : process(ap_enable_reg_pp0_iter0, icmp_ln532_fu_452_p2, icmp_ln534_fu_472_p2)
    begin
                ap_condition_865 <= ((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (icmp_ln534_fu_472_p2 = ap_const_lv1_1) and (icmp_ln532_fu_452_p2 = ap_const_lv1_0));
    end process;


    ap_condition_exit_pp0_iter0_stage1_assign_proc : process(ap_enable_reg_pp0_iter0, ap_CS_fsm_pp0_stage1, icmp_ln532_reg_1037, icmp_ln534_reg_1047, ap_block_pp0_stage1_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage1_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and ((icmp_ln534_reg_1047 = ap_const_lv1_0) or (icmp_ln532_reg_1037 = ap_const_lv1_1)))) then 
            ap_condition_exit_pp0_iter0_stage1 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage1 <= ap_const_logic_0;
        end if; 
    end process;


    ap_condition_exit_pp0_iter2_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter2, icmp_ln532_reg_1037_pp0_iter1_reg, icmp_ln534_reg_1047_pp0_iter1_reg, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and ((icmp_ln534_reg_1047_pp0_iter1_reg = ap_const_lv1_0) or (icmp_ln532_reg_1037_pp0_iter1_reg = ap_const_lv1_1)))) then 
            ap_condition_exit_pp0_iter2_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter2_stage0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_subdone, ap_done_reg, ap_loop_exit_ready_pp0_iter2_reg)
    begin
        if (((ap_loop_exit_ready_pp0_iter2_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;


    ap_done_pending_pp0_assign_proc : process(ap_loop_exit_ready, ap_loop_exit_ready_pp0_iter1_reg, ap_loop_exit_ready_pp0_iter2_reg)
    begin
        if (not(((ap_loop_exit_ready_pp0_iter2_reg = ap_const_logic_0) and (ap_loop_exit_ready_pp0_iter1_reg = ap_const_logic_0) and (ap_loop_exit_ready = ap_const_logic_0)))) then 
            ap_done_pending_pp0 <= ap_const_logic_1;
        else 
            ap_done_pending_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);

    ap_enable_reg_pp0_iter0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0_reg, ap_start_int)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) then 
            ap_enable_reg_pp0_iter0 <= ap_start_int;
        else 
            ap_enable_reg_pp0_iter0 <= ap_enable_reg_pp0_iter0_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3)
    begin
        if (((ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_0to1_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0_0to1 <= ap_const_logic_1;
        else 
            ap_idle_pp0_0to1 <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_1to3_assign_proc : process(ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3)
    begin
        if (((ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0))) then 
            ap_idle_pp0_1to3 <= ap_const_logic_1;
        else 
            ap_idle_pp0_1to3 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage1;

    ap_predicate_op67_read_state2_assign_proc : process(icmp_ln532_reg_1037, icmp_ln534_reg_1047)
    begin
                ap_predicate_op67_read_state2 <= ((icmp_ln534_reg_1047 = ap_const_lv1_1) and (icmp_ln532_reg_1037 = ap_const_lv1_0));
    end process;


    ap_ready_int_assign_proc : process(ap_enable_reg_pp0_iter0, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage1_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_x_2_assign_proc : process(ap_CS_fsm_pp0_stage0, x_fu_188, ap_loop_init, ap_block_pp0_stage0)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_sig_allocacmp_x_2 <= ap_const_lv31_0;
        else 
            ap_sig_allocacmp_x_2 <= x_fu_188;
        end if; 
    end process;

    b_field_fu_687_p3 <= (trunc_ln107_reg_1094 & lshr_ln107_1_reg_1089);
    cmp6_i_read_read_fu_252_p2 <= cmp6_i;
    g_field_fu_627_p3 <= (tmp_1_fu_617_p4 & lshr_ln5_fu_607_p4);
    gray_2_fu_754_p4 <= y_1_fu_749_p2(15 downto 8);
    gray_3_fu_769_p4 <= y_2_fu_764_p2(15 downto 8);
    gray_4_fu_779_p3 <= 
        gray_fu_736_p4 when (icmp_ln124_reg_1051_pp0_iter2_reg(0) = '1') else 
        gray_7_reg_1069_pp0_iter1_reg;
    gray_5_fu_785_p3 <= 
        gray_2_fu_754_p4 when (cmp6_i(0) = '1') else 
        gray_4_fu_779_p3;
    gray_6_fu_802_p3 <= 
        gray_3_fu_769_p4 when (and_ln124_fu_797_p2(0) = '1') else 
        gray_5_fu_785_p3;
    gray_7_fu_583_p1 <= in_stream_TDATA(8 - 1 downto 0);
    gray_fu_736_p4 <= y_fu_731_p2(15 downto 8);

    grp_fu_962_ce_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage0_11001, ap_block_pp0_stage1_11001)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)))) then 
            grp_fu_962_ce <= ap_const_logic_1;
        else 
            grp_fu_962_ce <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_962_p0 <= grp_fu_962_p00(8 - 1 downto 0);
    grp_fu_962_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(r_fu_653_p4),15));
    grp_fu_962_p1 <= ap_const_lv15_4D(7 - 1 downto 0);

    grp_fu_970_ce_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage0_11001, ap_block_pp0_stage1_11001)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)))) then 
            grp_fu_970_ce <= ap_const_logic_1;
        else 
            grp_fu_970_ce <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_970_p0 <= grp_fu_970_p00(8 - 1 downto 0);
    grp_fu_970_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(gray_7_fu_583_p1),13));
    grp_fu_970_p1 <= ap_const_lv13_1D(5 - 1 downto 0);
    grp_fu_970_p2 <= ap_const_lv13_80(8 - 1 downto 0);

    grp_fu_978_ce_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage0_11001, ap_block_pp0_stage1_11001)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)))) then 
            grp_fu_978_ce <= ap_const_logic_1;
        else 
            grp_fu_978_ce <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_978_p0 <= grp_fu_978_p00(8 - 1 downto 0);
    grp_fu_978_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(g_field_fu_627_p3),15));
    grp_fu_978_p1 <= ap_const_lv15_4D(7 - 1 downto 0);

    grp_fu_986_ce_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage0_11001, ap_block_pp0_stage1_11001)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)))) then 
            grp_fu_986_ce <= ap_const_logic_1;
        else 
            grp_fu_986_ce <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_986_p0 <= grp_fu_986_p00(8 - 1 downto 0);
    grp_fu_986_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(b_field_fu_687_p3),13));
    grp_fu_986_p1 <= ap_const_lv13_1D(5 - 1 downto 0);
    grp_fu_986_p2 <= ap_const_lv13_80(8 - 1 downto 0);

    grp_fu_995_ce_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage0_11001, ap_block_pp0_stage1_11001)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)))) then 
            grp_fu_995_ce <= ap_const_logic_1;
        else 
            grp_fu_995_ce <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_995_p0 <= grp_fu_995_p00(8 - 1 downto 0);
    grp_fu_995_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(r_field_fu_681_p3),15));
    grp_fu_995_p1 <= ap_const_lv15_4D(7 - 1 downto 0);

    hist0_1_address0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1, hist0_1_addr_reg_1174, zext_ln541_fu_846_p1, ap_block_pp0_stage0)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            hist0_1_address0 <= hist0_1_addr_reg_1174;
        elsif (((ap_const_boolean_0 = ap_block_pp0_stage1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            hist0_1_address0 <= zext_ln541_fu_846_p1(4 - 1 downto 0);
        else 
            hist0_1_address0 <= "XXXX";
        end if; 
    end process;


    hist0_1_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage0_11001, ap_block_pp0_stage1_11001)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)))) then 
            hist0_1_ce0 <= ap_const_logic_1;
        else 
            hist0_1_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    hist0_1_d0 <= add_ln542_fu_919_p2;

    hist0_1_we0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter3, ap_block_pp0_stage0_11001, and_ln538_1_reg_1061_pp0_iter2_reg, trunc_ln_reg_1164)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_lv1_1 = and_ln538_1_reg_1061_pp0_iter2_reg) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (trunc_ln_reg_1164 = ap_const_lv2_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            hist0_1_we0 <= ap_const_logic_1;
        else 
            hist0_1_we0 <= ap_const_logic_0;
        end if; 
    end process;


    hist0_2_address0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1, hist0_2_addr_reg_1179, zext_ln541_fu_846_p1, ap_block_pp0_stage0)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            hist0_2_address0 <= hist0_2_addr_reg_1179;
        elsif (((ap_const_boolean_0 = ap_block_pp0_stage1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            hist0_2_address0 <= zext_ln541_fu_846_p1(4 - 1 downto 0);
        else 
            hist0_2_address0 <= "XXXX";
        end if; 
    end process;


    hist0_2_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage0_11001, ap_block_pp0_stage1_11001)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)))) then 
            hist0_2_ce0 <= ap_const_logic_1;
        else 
            hist0_2_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    hist0_2_d0 <= add_ln542_fu_919_p2;

    hist0_2_we0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter3, ap_block_pp0_stage0_11001, and_ln538_1_reg_1061_pp0_iter2_reg, trunc_ln_reg_1164)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_lv1_1 = and_ln538_1_reg_1061_pp0_iter2_reg) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (trunc_ln_reg_1164 = ap_const_lv2_2) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            hist0_2_we0 <= ap_const_logic_1;
        else 
            hist0_2_we0 <= ap_const_logic_0;
        end if; 
    end process;


    hist0_3_address0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1, hist0_3_addr_reg_1184, zext_ln541_fu_846_p1, ap_block_pp0_stage0)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            hist0_3_address0 <= hist0_3_addr_reg_1184;
        elsif (((ap_const_boolean_0 = ap_block_pp0_stage1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            hist0_3_address0 <= zext_ln541_fu_846_p1(4 - 1 downto 0);
        else 
            hist0_3_address0 <= "XXXX";
        end if; 
    end process;


    hist0_3_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage0_11001, ap_block_pp0_stage1_11001)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)))) then 
            hist0_3_ce0 <= ap_const_logic_1;
        else 
            hist0_3_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    hist0_3_d0 <= add_ln542_fu_919_p2;

    hist0_3_we0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter3, ap_block_pp0_stage0_11001, and_ln538_1_reg_1061_pp0_iter2_reg, trunc_ln_reg_1164)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_lv1_1 = and_ln538_1_reg_1061_pp0_iter2_reg) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (trunc_ln_reg_1164 = ap_const_lv2_3) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            hist0_3_we0 <= ap_const_logic_1;
        else 
            hist0_3_we0 <= ap_const_logic_0;
        end if; 
    end process;


    hist0_address0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1, hist0_addr_reg_1169, zext_ln541_fu_846_p1, ap_block_pp0_stage0)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            hist0_address0 <= hist0_addr_reg_1169;
        elsif (((ap_const_boolean_0 = ap_block_pp0_stage1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            hist0_address0 <= zext_ln541_fu_846_p1(4 - 1 downto 0);
        else 
            hist0_address0 <= "XXXX";
        end if; 
    end process;


    hist0_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage0_11001, ap_block_pp0_stage1_11001)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)))) then 
            hist0_ce0 <= ap_const_logic_1;
        else 
            hist0_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    hist0_d0 <= add_ln542_fu_919_p2;

    hist0_we0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter3, ap_block_pp0_stage0_11001, and_ln538_1_reg_1061_pp0_iter2_reg, trunc_ln_reg_1164)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_lv1_1 = and_ln538_1_reg_1061_pp0_iter2_reg) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (trunc_ln_reg_1164 = ap_const_lv2_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            hist0_we0 <= ap_const_logic_1;
        else 
            hist0_we0 <= ap_const_logic_0;
        end if; 
    end process;


    hist1_1_address0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1, hist1_1_addr_reg_1199, zext_ln547_fu_888_p1, ap_block_pp0_stage0)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            hist1_1_address0 <= hist1_1_addr_reg_1199;
        elsif (((ap_const_boolean_0 = ap_block_pp0_stage1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            hist1_1_address0 <= zext_ln547_fu_888_p1(4 - 1 downto 0);
        else 
            hist1_1_address0 <= "XXXX";
        end if; 
    end process;


    hist1_1_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage0_11001, ap_block_pp0_stage1_11001)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)))) then 
            hist1_1_ce0 <= ap_const_logic_1;
        else 
            hist1_1_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    hist1_1_d0 <= add_ln548_fu_952_p2;

    hist1_1_we0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter3, ap_block_pp0_stage0_11001, and_ln544_1_reg_1065_pp0_iter2_reg, trunc_ln1_reg_1189)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_lv1_1 = and_ln544_1_reg_1065_pp0_iter2_reg) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (trunc_ln1_reg_1189 = ap_const_lv2_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            hist1_1_we0 <= ap_const_logic_1;
        else 
            hist1_1_we0 <= ap_const_logic_0;
        end if; 
    end process;


    hist1_2_address0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1, hist1_2_addr_reg_1204, zext_ln547_fu_888_p1, ap_block_pp0_stage0)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            hist1_2_address0 <= hist1_2_addr_reg_1204;
        elsif (((ap_const_boolean_0 = ap_block_pp0_stage1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            hist1_2_address0 <= zext_ln547_fu_888_p1(4 - 1 downto 0);
        else 
            hist1_2_address0 <= "XXXX";
        end if; 
    end process;


    hist1_2_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage0_11001, ap_block_pp0_stage1_11001)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)))) then 
            hist1_2_ce0 <= ap_const_logic_1;
        else 
            hist1_2_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    hist1_2_d0 <= add_ln548_fu_952_p2;

    hist1_2_we0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter3, ap_block_pp0_stage0_11001, and_ln544_1_reg_1065_pp0_iter2_reg, trunc_ln1_reg_1189)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_lv1_1 = and_ln544_1_reg_1065_pp0_iter2_reg) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (trunc_ln1_reg_1189 = ap_const_lv2_2) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            hist1_2_we0 <= ap_const_logic_1;
        else 
            hist1_2_we0 <= ap_const_logic_0;
        end if; 
    end process;


    hist1_3_address0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1, hist1_3_addr_reg_1209, zext_ln547_fu_888_p1, ap_block_pp0_stage0)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            hist1_3_address0 <= hist1_3_addr_reg_1209;
        elsif (((ap_const_boolean_0 = ap_block_pp0_stage1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            hist1_3_address0 <= zext_ln547_fu_888_p1(4 - 1 downto 0);
        else 
            hist1_3_address0 <= "XXXX";
        end if; 
    end process;


    hist1_3_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage0_11001, ap_block_pp0_stage1_11001)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)))) then 
            hist1_3_ce0 <= ap_const_logic_1;
        else 
            hist1_3_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    hist1_3_d0 <= add_ln548_fu_952_p2;

    hist1_3_we0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter3, ap_block_pp0_stage0_11001, and_ln544_1_reg_1065_pp0_iter2_reg, trunc_ln1_reg_1189)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_lv1_1 = and_ln544_1_reg_1065_pp0_iter2_reg) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (trunc_ln1_reg_1189 = ap_const_lv2_3) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            hist1_3_we0 <= ap_const_logic_1;
        else 
            hist1_3_we0 <= ap_const_logic_0;
        end if; 
    end process;


    hist1_address0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1, hist1_addr_reg_1194, zext_ln547_fu_888_p1, ap_block_pp0_stage0)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            hist1_address0 <= hist1_addr_reg_1194;
        elsif (((ap_const_boolean_0 = ap_block_pp0_stage1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            hist1_address0 <= zext_ln547_fu_888_p1(4 - 1 downto 0);
        else 
            hist1_address0 <= "XXXX";
        end if; 
    end process;


    hist1_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage0_11001, ap_block_pp0_stage1_11001)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)))) then 
            hist1_ce0 <= ap_const_logic_1;
        else 
            hist1_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    hist1_d0 <= add_ln548_fu_952_p2;

    hist1_we0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter3, ap_block_pp0_stage0_11001, and_ln544_1_reg_1065_pp0_iter2_reg, trunc_ln1_reg_1189)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_lv1_1 = and_ln544_1_reg_1065_pp0_iter2_reg) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (trunc_ln1_reg_1189 = ap_const_lv2_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            hist1_we0 <= ap_const_logic_1;
        else 
            hist1_we0 <= ap_const_logic_0;
        end if; 
    end process;

    icmp_ln124_1_fu_484_p2 <= "1" when (pixel_format = ap_const_lv32_1) else "0";
    icmp_ln124_fu_478_p2 <= "1" when (pixel_format = ap_const_lv32_2) else "0";
    icmp_ln532_fu_452_p2 <= "1" when (ap_sig_allocacmp_x_2 = ap_const_lv31_280) else "0";
    icmp_ln534_fu_472_p2 <= "1" when (signed(zext_ln532_fu_468_p1) < signed(frame_width)) else "0";
    icmp_ln538_1_fu_502_p2 <= "1" when (signed(zext_ln532_fu_468_p1) < signed(ex0_1)) else "0";
    icmp_ln538_fu_490_p2 <= "1" when (signed(zext_ln532_fu_468_p1) < signed(c_cx0_3)) else "0";
    icmp_ln544_1_fu_544_p2 <= "1" when (signed(zext_ln532_fu_468_p1) < signed(ex1_1)) else "0";
    icmp_ln544_fu_532_p2 <= "1" when (signed(zext_ln532_fu_468_p1) < signed(c_cx0)) else "0";

    in_stream_TDATA_blk_n_assign_proc : process(ap_enable_reg_pp0_iter0, ap_CS_fsm_pp0_stage1, in_stream_TVALID, ap_predicate_op67_read_state2, ap_block_pp0_stage1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage1) and (ap_predicate_op67_read_state2 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            in_stream_TDATA_blk_n <= in_stream_TVALID;
        else 
            in_stream_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    in_stream_TREADY_assign_proc : process(ap_enable_reg_pp0_iter0, ap_CS_fsm_pp0_stage1, ap_predicate_op67_read_state2, ap_block_pp0_stage1_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_predicate_op67_read_state2 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            in_stream_TREADY <= ap_const_logic_1;
        else 
            in_stream_TREADY <= ap_const_logic_0;
        end if; 
    end process;

    lshr_ln5_fu_607_p4 <= in_stream_TDATA(10 downto 9);
    mul_ln118_2_fu_707_p0 <= mul_ln118_2_fu_707_p00(8 - 1 downto 0);
    mul_ln118_2_fu_707_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(g_reg_1104),16));
    mul_ln118_2_fu_707_p1 <= ap_const_lv16_96(9 - 1 downto 0);
    mul_ln118_5_fu_713_p0 <= mul_ln118_5_fu_713_p00(8 - 1 downto 0);
    mul_ln118_5_fu_713_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(r_field_reg_1119),16));
    mul_ln118_5_fu_713_p1 <= ap_const_lv16_96(9 - 1 downto 0);
    mul_ln118_7_fu_722_p0 <= mul_ln118_7_fu_722_p00(8 - 1 downto 0);
    mul_ln118_7_fu_722_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(g_field_reg_1084_pp0_iter1_reg),16));
    mul_ln118_7_fu_722_p1 <= ap_const_lv16_96(9 - 1 downto 0);
    pix0_address1 <= zext_ln540_fu_821_p1(13 - 1 downto 0);

    pix0_ce1_assign_proc : process(ap_enable_reg_pp0_iter2, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            pix0_ce1 <= ap_const_logic_1;
        else 
            pix0_ce1 <= ap_const_logic_0;
        end if; 
    end process;

    pix0_d1 <= gray_6_fu_802_p3;

    pix0_we1_assign_proc : process(ap_enable_reg_pp0_iter2, ap_CS_fsm_pp0_stage1, and_ln538_1_reg_1061_pp0_iter2_reg, ap_block_pp0_stage1_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_const_lv1_1 = and_ln538_1_reg_1061_pp0_iter2_reg) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            pix0_we1 <= ap_const_logic_1;
        else 
            pix0_we1 <= ap_const_logic_0;
        end if; 
    end process;

    pix1_address1 <= zext_ln546_fu_863_p1(13 - 1 downto 0);

    pix1_ce1_assign_proc : process(ap_enable_reg_pp0_iter2, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            pix1_ce1 <= ap_const_logic_1;
        else 
            pix1_ce1 <= ap_const_logic_0;
        end if; 
    end process;

    pix1_d1 <= gray_6_fu_802_p3;

    pix1_we1_assign_proc : process(ap_enable_reg_pp0_iter2, ap_CS_fsm_pp0_stage1, and_ln544_1_reg_1065_pp0_iter2_reg, ap_block_pp0_stage1_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_const_lv1_1 = and_ln544_1_reg_1065_pp0_iter2_reg) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            pix1_we1 <= ap_const_logic_1;
        else 
            pix1_we1 <= ap_const_logic_0;
        end if; 
    end process;

    r_field_fu_681_p3 <= (tmp_s_reg_1079 & lshr_ln4_reg_1074);
    r_fu_653_p4 <= in_stream_TDATA(23 downto 16);
    sub_ln539_fu_812_p2 <= std_logic_vector(unsigned(trunc_ln532_reg_1041_pp0_iter2_reg) - unsigned(empty_55));
    sub_ln545_fu_854_p2 <= std_logic_vector(unsigned(trunc_ln532_reg_1041_pp0_iter2_reg) - unsigned(empty));
    tmp_1_fu_617_p4 <= in_stream_TDATA(10 downto 5);
    tmp_3_fu_929_p9 <= "XXXXXXXXXXXXXXXX";
    tmp_fu_896_p9 <= "XXXXXXXXXXXXXXXX";
    trunc_ln107_fu_645_p1 <= in_stream_TDATA(5 - 1 downto 0);
    trunc_ln532_fu_464_p1 <= ap_sig_allocacmp_x_2(13 - 1 downto 0);
    trunc_ln541_1_fu_836_p4 <= gray_6_fu_802_p3(7 downto 4);
    trunc_ln547_1_fu_878_p4 <= gray_6_fu_802_p3(7 downto 4);
    xor_ln124_fu_792_p2 <= (cmp6_i xor ap_const_lv1_1);
    xor_ln538_fu_496_p2 <= (icmp_ln538_fu_490_p2 xor ap_const_lv1_1);
    xor_ln544_fu_538_p2 <= (icmp_ln544_fu_532_p2 xor ap_const_lv1_1);
    y_1_fu_749_p2 <= std_logic_vector(unsigned(zext_ln118_11_fu_746_p1) + unsigned(add_ln118_3_reg_1154));
    y_2_fu_764_p2 <= std_logic_vector(unsigned(zext_ln118_11_fu_746_p1) + unsigned(grp_fu_995_p3));
    y_fu_731_p2 <= std_logic_vector(unsigned(zext_ln118_9_fu_728_p1) + unsigned(add_ln118_reg_1144));
    zext_ln118_11_fu_746_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(grp_fu_986_p3),16));
    zext_ln118_9_fu_728_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln118_1_reg_1149),16));
    zext_ln532_fu_468_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(ap_sig_allocacmp_x_2),32));
    zext_ln540_fu_821_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln540_fu_816_p2),64));
    zext_ln541_fu_846_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(trunc_ln541_1_fu_836_p4),64));
    zext_ln546_fu_863_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln546_fu_858_p2),64));
    zext_ln547_fu_888_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(trunc_ln547_1_fu_878_p4),64));
end behav;
