-- ==============================================================
-- Generated by Vitis HLS v2023.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity eye_feature_topk_sum_hist_Pipeline_BUILD_HIST is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    cw : IN STD_LOGIC_VECTOR (7 downto 0);
    runs_0_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    runs_0_ce0 : OUT STD_LOGIC;
    runs_0_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
    runs_1_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    runs_1_ce0 : OUT STD_LOGIC;
    runs_1_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
    runs_2_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    runs_2_ce0 : OUT STD_LOGIC;
    runs_2_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
    runs_3_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    runs_3_ce0 : OUT STD_LOGIC;
    runs_3_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
    ch_cast : IN STD_LOGIC_VECTOR (6 downto 0);
    ch : IN STD_LOGIC_VECTOR (6 downto 0);
    hist_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    hist_ce0 : OUT STD_LOGIC;
    hist_we0 : OUT STD_LOGIC;
    hist_d0 : OUT STD_LOGIC_VECTOR (15 downto 0);
    hist_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
    hist_1_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    hist_1_ce0 : OUT STD_LOGIC;
    hist_1_we0 : OUT STD_LOGIC;
    hist_1_d0 : OUT STD_LOGIC_VECTOR (15 downto 0);
    hist_1_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
    hist_2_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    hist_2_ce0 : OUT STD_LOGIC;
    hist_2_we0 : OUT STD_LOGIC;
    hist_2_d0 : OUT STD_LOGIC_VECTOR (15 downto 0);
    hist_2_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
    hist_3_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    hist_3_ce0 : OUT STD_LOGIC;
    hist_3_we0 : OUT STD_LOGIC;
    hist_3_d0 : OUT STD_LOGIC_VECTOR (15 downto 0);
    hist_3_q0 : IN STD_LOGIC_VECTOR (15 downto 0) );
end;


architecture behav of eye_feature_topk_sum_hist_Pipeline_BUILD_HIST is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_ST_fsm_pp0_stage1 : STD_LOGIC_VECTOR (1 downto 0) := "10";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv2_1 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_const_lv2_2 : STD_LOGIC_VECTOR (1 downto 0) := "10";
    constant ap_const_lv2_3 : STD_LOGIC_VECTOR (1 downto 0) := "11";
    constant ap_const_lv8_80 : STD_LOGIC_VECTOR (7 downto 0) := "10000000";
    constant ap_const_lv8_1 : STD_LOGIC_VECTOR (7 downto 0) := "00000001";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";
    constant ap_const_lv16_1 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000001";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (1 downto 0) := "01";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln245_fu_210_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal ap_CS_fsm_pp0_stage1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage1 : signal is "none";
    signal ap_block_pp0_stage1_subdone : BOOLEAN;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal ch_cast_cast_fu_198_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal ch_cast_cast_reg_361 : STD_LOGIC_VECTOR (15 downto 0);
    signal icmp_ln245_reg_366 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln245_fu_222_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln245_reg_370 : STD_LOGIC_VECTOR (1 downto 0);
    signal icmp_ln247_fu_244_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln247_reg_375 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln248_1_fu_294_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln248_1_reg_399 : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_block_pp0_stage1_11001 : BOOLEAN;
    signal hist_addr_reg_404 : STD_LOGIC_VECTOR (4 downto 0);
    signal hist_1_addr_reg_409 : STD_LOGIC_VECTOR (4 downto 0);
    signal hist_2_addr_reg_414 : STD_LOGIC_VECTOR (4 downto 0);
    signal hist_3_addr_reg_419 : STD_LOGIC_VECTOR (4 downto 0);
    signal ap_enable_reg_pp0_iter0_reg : STD_LOGIC := '0';
    signal zext_ln245_fu_236_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal zext_ln248_fu_308_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage1 : BOOLEAN;
    signal x_fu_72 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal add_ln245_fu_216_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal ap_sig_allocacmp_x_1 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln251_fu_339_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal lshr_ln1_fu_226_p4 : STD_LOGIC_VECTOR (4 downto 0);
    signal r_fu_255_p9 : STD_LOGIC_VECTOR (15 downto 0);
    signal r_fu_255_p11 : STD_LOGIC_VECTOR (15 downto 0);
    signal icmp_ln250_fu_282_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln248_fu_278_p1 : STD_LOGIC_VECTOR (6 downto 0);
    signal r_1_fu_287_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal lshr_ln2_fu_298_p4 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_1_fu_316_p9 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_1_fu_316_p11 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_idle_pp0_1to1 : STD_LOGIC;
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal r_fu_255_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal r_fu_255_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal r_fu_255_p5 : STD_LOGIC_VECTOR (1 downto 0);
    signal r_fu_255_p7 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_1_fu_316_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_1_fu_316_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_1_fu_316_p5 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_1_fu_316_p7 : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_ce_reg : STD_LOGIC;

    component eye_feature_sparsemux_9_2_16_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        CASE0 : STD_LOGIC_VECTOR (1 downto 0);
        din0_WIDTH : INTEGER;
        CASE1 : STD_LOGIC_VECTOR (1 downto 0);
        din1_WIDTH : INTEGER;
        CASE2 : STD_LOGIC_VECTOR (1 downto 0);
        din2_WIDTH : INTEGER;
        CASE3 : STD_LOGIC_VECTOR (1 downto 0);
        din3_WIDTH : INTEGER;
        def_WIDTH : INTEGER;
        sel_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (15 downto 0);
        din1 : IN STD_LOGIC_VECTOR (15 downto 0);
        din2 : IN STD_LOGIC_VECTOR (15 downto 0);
        din3 : IN STD_LOGIC_VECTOR (15 downto 0);
        def : IN STD_LOGIC_VECTOR (15 downto 0);
        sel : IN STD_LOGIC_VECTOR (1 downto 0);
        dout : OUT STD_LOGIC_VECTOR (15 downto 0) );
    end component;


    component eye_feature_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    sparsemux_9_2_16_1_1_U127 : component eye_feature_sparsemux_9_2_16_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "00",
        din0_WIDTH => 16,
        CASE1 => "01",
        din1_WIDTH => 16,
        CASE2 => "10",
        din2_WIDTH => 16,
        CASE3 => "11",
        din3_WIDTH => 16,
        def_WIDTH => 16,
        sel_WIDTH => 2,
        dout_WIDTH => 16)
    port map (
        din0 => runs_0_q0,
        din1 => runs_1_q0,
        din2 => runs_2_q0,
        din3 => runs_3_q0,
        def => r_fu_255_p9,
        sel => trunc_ln245_reg_370,
        dout => r_fu_255_p11);

    sparsemux_9_2_16_1_1_U128 : component eye_feature_sparsemux_9_2_16_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "00",
        din0_WIDTH => 16,
        CASE1 => "01",
        din1_WIDTH => 16,
        CASE2 => "10",
        din2_WIDTH => 16,
        CASE3 => "11",
        din3_WIDTH => 16,
        def_WIDTH => 16,
        sel_WIDTH => 2,
        dout_WIDTH => 16)
    port map (
        din0 => hist_q0,
        din1 => hist_1_q0,
        din2 => hist_2_q0,
        din3 => hist_3_q0,
        def => tmp_1_fu_316_p9,
        sel => trunc_ln248_1_reg_399,
        dout => tmp_1_fu_316_p11);

    flow_control_loop_pipe_sequential_init_U : component eye_feature_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready,
        ap_done => ap_done,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_loop_exit_ready = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter0_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter0_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage0)) then 
                    ap_enable_reg_pp0_iter0_reg <= ap_const_logic_0;
                elsif ((ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) then 
                    ap_enable_reg_pp0_iter0_reg <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage1_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                    ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
                end if; 
            end if;
        end if;
    end process;


    x_fu_72_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln245_fu_210_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    x_fu_72 <= add_ln245_fu_216_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    x_fu_72 <= ap_const_lv8_0;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                    ch_cast_cast_reg_361(6 downto 0) <= ch_cast_cast_fu_198_p1(6 downto 0);
                icmp_ln245_reg_366 <= icmp_ln245_fu_210_p2;
                icmp_ln247_reg_375 <= icmp_ln247_fu_244_p2;
                trunc_ln245_reg_370 <= trunc_ln245_fu_222_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then
                hist_1_addr_reg_409 <= zext_ln248_fu_308_p1(5 - 1 downto 0);
                hist_2_addr_reg_414 <= zext_ln248_fu_308_p1(5 - 1 downto 0);
                hist_3_addr_reg_419 <= zext_ln248_fu_308_p1(5 - 1 downto 0);
                hist_addr_reg_404 <= zext_ln248_fu_308_p1(5 - 1 downto 0);
                trunc_ln248_1_reg_399 <= trunc_ln248_1_fu_294_p1;
            end if;
        end if;
    end process;
    ch_cast_cast_reg_361(15 downto 7) <= "000000000";

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_block_pp0_stage0_subdone, ap_condition_exit_pp0_iter0_stage0, ap_block_pp0_stage1_subdone, ap_idle_pp0_1to1, ap_start_int)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage0)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                elsif ((not(((ap_start_int = ap_const_logic_0) and (ap_idle_pp0_1to1 = ap_const_logic_1))) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage1;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                end if;
            when ap_ST_fsm_pp0_stage1 => 
                if ((ap_const_boolean_0 = ap_block_pp0_stage1_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage1;
                end if;
            when others =>  
                ap_NS_fsm <= "XX";
        end case;
    end process;
    add_ln245_fu_216_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_x_1) + unsigned(ap_const_lv8_1));
    add_ln251_fu_339_p2 <= std_logic_vector(unsigned(tmp_1_fu_316_p11) + unsigned(ap_const_lv16_1));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
    ap_CS_fsm_pp0_stage1 <= ap_CS_fsm(1);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage1 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage1_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage1_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone, icmp_ln245_fu_210_p2)
    begin
        if (((icmp_ln245_fu_210_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_subdone, ap_loop_exit_ready, ap_done_reg)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);

    ap_enable_reg_pp0_iter0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0_reg, ap_start_int)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) then 
            ap_enable_reg_pp0_iter0 <= ap_start_int;
        else 
            ap_enable_reg_pp0_iter0 <= ap_enable_reg_pp0_iter0_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_1to1_assign_proc : process(ap_enable_reg_pp0_iter1)
    begin
        if ((ap_enable_reg_pp0_iter1 = ap_const_logic_0)) then 
            ap_idle_pp0_1to1 <= ap_const_logic_1;
        else 
            ap_idle_pp0_1to1 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;

    ap_ready_int_assign_proc : process(ap_enable_reg_pp0_iter0, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage1_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_x_1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, x_fu_72, ap_loop_init)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
            ap_sig_allocacmp_x_1 <= ap_const_lv8_0;
        else 
            ap_sig_allocacmp_x_1 <= x_fu_72;
        end if; 
    end process;

    ch_cast_cast_fu_198_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(ch_cast),16));

    hist_1_address0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_CS_fsm_pp0_stage1, hist_1_addr_reg_409, ap_block_pp0_stage0, zext_ln248_fu_308_p1, ap_block_pp0_stage1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            hist_1_address0 <= hist_1_addr_reg_409;
        elsif (((ap_const_boolean_0 = ap_block_pp0_stage1) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            hist_1_address0 <= zext_ln248_fu_308_p1(5 - 1 downto 0);
        else 
            hist_1_address0 <= "XXXXX";
        end if; 
    end process;


    hist_1_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage0_11001, ap_block_pp0_stage1_11001)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)))) then 
            hist_1_ce0 <= ap_const_logic_1;
        else 
            hist_1_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    hist_1_d0 <= add_ln251_fu_339_p2;

    hist_1_we0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001, icmp_ln247_reg_375, trunc_ln248_1_reg_399)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (trunc_ln248_1_reg_399 = ap_const_lv2_1) and (icmp_ln247_reg_375 = ap_const_lv1_1))) then 
            hist_1_we0 <= ap_const_logic_1;
        else 
            hist_1_we0 <= ap_const_logic_0;
        end if; 
    end process;


    hist_2_address0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_CS_fsm_pp0_stage1, hist_2_addr_reg_414, ap_block_pp0_stage0, zext_ln248_fu_308_p1, ap_block_pp0_stage1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            hist_2_address0 <= hist_2_addr_reg_414;
        elsif (((ap_const_boolean_0 = ap_block_pp0_stage1) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            hist_2_address0 <= zext_ln248_fu_308_p1(5 - 1 downto 0);
        else 
            hist_2_address0 <= "XXXXX";
        end if; 
    end process;


    hist_2_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage0_11001, ap_block_pp0_stage1_11001)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)))) then 
            hist_2_ce0 <= ap_const_logic_1;
        else 
            hist_2_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    hist_2_d0 <= add_ln251_fu_339_p2;

    hist_2_we0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001, icmp_ln247_reg_375, trunc_ln248_1_reg_399)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (trunc_ln248_1_reg_399 = ap_const_lv2_2) and (icmp_ln247_reg_375 = ap_const_lv1_1))) then 
            hist_2_we0 <= ap_const_logic_1;
        else 
            hist_2_we0 <= ap_const_logic_0;
        end if; 
    end process;


    hist_3_address0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_CS_fsm_pp0_stage1, hist_3_addr_reg_419, ap_block_pp0_stage0, zext_ln248_fu_308_p1, ap_block_pp0_stage1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            hist_3_address0 <= hist_3_addr_reg_419;
        elsif (((ap_const_boolean_0 = ap_block_pp0_stage1) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            hist_3_address0 <= zext_ln248_fu_308_p1(5 - 1 downto 0);
        else 
            hist_3_address0 <= "XXXXX";
        end if; 
    end process;


    hist_3_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage0_11001, ap_block_pp0_stage1_11001)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)))) then 
            hist_3_ce0 <= ap_const_logic_1;
        else 
            hist_3_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    hist_3_d0 <= add_ln251_fu_339_p2;

    hist_3_we0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001, icmp_ln247_reg_375, trunc_ln248_1_reg_399)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (trunc_ln248_1_reg_399 = ap_const_lv2_3) and (icmp_ln247_reg_375 = ap_const_lv1_1))) then 
            hist_3_we0 <= ap_const_logic_1;
        else 
            hist_3_we0 <= ap_const_logic_0;
        end if; 
    end process;


    hist_address0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_CS_fsm_pp0_stage1, hist_addr_reg_404, ap_block_pp0_stage0, zext_ln248_fu_308_p1, ap_block_pp0_stage1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            hist_address0 <= hist_addr_reg_404;
        elsif (((ap_const_boolean_0 = ap_block_pp0_stage1) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            hist_address0 <= zext_ln248_fu_308_p1(5 - 1 downto 0);
        else 
            hist_address0 <= "XXXXX";
        end if; 
    end process;


    hist_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage0_11001, ap_block_pp0_stage1_11001)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)))) then 
            hist_ce0 <= ap_const_logic_1;
        else 
            hist_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    hist_d0 <= add_ln251_fu_339_p2;

    hist_we0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001, icmp_ln247_reg_375, trunc_ln248_1_reg_399)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (trunc_ln248_1_reg_399 = ap_const_lv2_0) and (icmp_ln247_reg_375 = ap_const_lv1_1))) then 
            hist_we0 <= ap_const_logic_1;
        else 
            hist_we0 <= ap_const_logic_0;
        end if; 
    end process;

    icmp_ln245_fu_210_p2 <= "1" when (ap_sig_allocacmp_x_1 = ap_const_lv8_80) else "0";
    icmp_ln247_fu_244_p2 <= "1" when (unsigned(ap_sig_allocacmp_x_1) < unsigned(cw)) else "0";
    icmp_ln250_fu_282_p2 <= "1" when (unsigned(r_fu_255_p11) > unsigned(ch_cast_cast_reg_361)) else "0";
    lshr_ln1_fu_226_p4 <= ap_sig_allocacmp_x_1(6 downto 2);
    lshr_ln2_fu_298_p4 <= r_1_fu_287_p3(6 downto 2);
    r_1_fu_287_p3 <= 
        ch when (icmp_ln250_fu_282_p2(0) = '1') else 
        trunc_ln248_fu_278_p1;
    r_fu_255_p9 <= "XXXXXXXXXXXXXXXX";
    runs_0_address0 <= zext_ln245_fu_236_p1(5 - 1 downto 0);

    runs_0_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            runs_0_ce0 <= ap_const_logic_1;
        else 
            runs_0_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    runs_1_address0 <= zext_ln245_fu_236_p1(5 - 1 downto 0);

    runs_1_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            runs_1_ce0 <= ap_const_logic_1;
        else 
            runs_1_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    runs_2_address0 <= zext_ln245_fu_236_p1(5 - 1 downto 0);

    runs_2_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            runs_2_ce0 <= ap_const_logic_1;
        else 
            runs_2_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    runs_3_address0 <= zext_ln245_fu_236_p1(5 - 1 downto 0);

    runs_3_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            runs_3_ce0 <= ap_const_logic_1;
        else 
            runs_3_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    tmp_1_fu_316_p9 <= "XXXXXXXXXXXXXXXX";
    trunc_ln245_fu_222_p1 <= ap_sig_allocacmp_x_1(2 - 1 downto 0);
    trunc_ln248_1_fu_294_p1 <= r_1_fu_287_p3(2 - 1 downto 0);
    trunc_ln248_fu_278_p1 <= r_fu_255_p11(7 - 1 downto 0);
    zext_ln245_fu_236_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(lshr_ln1_fu_226_p4),64));
    zext_ln248_fu_308_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(lshr_ln2_fu_298_p4),64));
end behav;
