// ==============================================================
// Generated by Vitis HLS v2023.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="classify_classify,hls_ip_2023_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg400-1,HLS_INPUT_CLOCK=20.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=14.551750,HLS_SYN_LAT=253,HLS_SYN_TPT=none,HLS_SYN_MEM=1,HLS_SYN_DSP=0,HLS_SYN_FF=544,HLS_SYN_LUT=1330,HLS_VERSION=2023_2}" *)

module classify (
        ap_clk,
        ap_rst_n,
        in_stream_TDATA,
        in_stream_TVALID,
        in_stream_TREADY,
        in_stream_TKEEP,
        in_stream_TSTRB,
        in_stream_TLAST,
        out_stream_TDATA,
        out_stream_TVALID,
        out_stream_TREADY,
        out_stream_TKEEP,
        out_stream_TSTRB,
        out_stream_TLAST,
        s_axi_CTRL_AWVALID,
        s_axi_CTRL_AWREADY,
        s_axi_CTRL_AWADDR,
        s_axi_CTRL_WVALID,
        s_axi_CTRL_WREADY,
        s_axi_CTRL_WDATA,
        s_axi_CTRL_WSTRB,
        s_axi_CTRL_ARVALID,
        s_axi_CTRL_ARREADY,
        s_axi_CTRL_ARADDR,
        s_axi_CTRL_RVALID,
        s_axi_CTRL_RREADY,
        s_axi_CTRL_RDATA,
        s_axi_CTRL_RRESP,
        s_axi_CTRL_BVALID,
        s_axi_CTRL_BREADY,
        s_axi_CTRL_BRESP,
        interrupt
);

parameter    ap_ST_fsm_state1 = 9'd1;
parameter    ap_ST_fsm_state2 = 9'd2;
parameter    ap_ST_fsm_state3 = 9'd4;
parameter    ap_ST_fsm_state4 = 9'd8;
parameter    ap_ST_fsm_state5 = 9'd16;
parameter    ap_ST_fsm_state6 = 9'd32;
parameter    ap_ST_fsm_state7 = 9'd64;
parameter    ap_ST_fsm_state8 = 9'd128;
parameter    ap_ST_fsm_state9 = 9'd256;
parameter    C_S_AXI_CTRL_DATA_WIDTH = 32;
parameter    C_S_AXI_CTRL_ADDR_WIDTH = 5;
parameter    C_S_AXI_DATA_WIDTH = 32;

parameter C_S_AXI_CTRL_WSTRB_WIDTH = (32 / 8);
parameter C_S_AXI_WSTRB_WIDTH = (32 / 8);

input   ap_clk;
input   ap_rst_n;
input  [31:0] in_stream_TDATA;
input   in_stream_TVALID;
output   in_stream_TREADY;
input  [3:0] in_stream_TKEEP;
input  [3:0] in_stream_TSTRB;
input  [0:0] in_stream_TLAST;
output  [31:0] out_stream_TDATA;
output   out_stream_TVALID;
input   out_stream_TREADY;
output  [3:0] out_stream_TKEEP;
output  [3:0] out_stream_TSTRB;
output  [0:0] out_stream_TLAST;
input   s_axi_CTRL_AWVALID;
output   s_axi_CTRL_AWREADY;
input  [C_S_AXI_CTRL_ADDR_WIDTH - 1:0] s_axi_CTRL_AWADDR;
input   s_axi_CTRL_WVALID;
output   s_axi_CTRL_WREADY;
input  [C_S_AXI_CTRL_DATA_WIDTH - 1:0] s_axi_CTRL_WDATA;
input  [C_S_AXI_CTRL_WSTRB_WIDTH - 1:0] s_axi_CTRL_WSTRB;
input   s_axi_CTRL_ARVALID;
output   s_axi_CTRL_ARREADY;
input  [C_S_AXI_CTRL_ADDR_WIDTH - 1:0] s_axi_CTRL_ARADDR;
output   s_axi_CTRL_RVALID;
input   s_axi_CTRL_RREADY;
output  [C_S_AXI_CTRL_DATA_WIDTH - 1:0] s_axi_CTRL_RDATA;
output  [1:0] s_axi_CTRL_RRESP;
output   s_axi_CTRL_BVALID;
input   s_axi_CTRL_BREADY;
output  [1:0] s_axi_CTRL_BRESP;
output   interrupt;

 reg    ap_rst_n_inv;
wire    ap_start;
reg    ap_done;
reg    ap_idle;
(* fsm_encoding = "none" *) reg   [8:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    ap_ready;
wire   [31:0] threshold_q;
reg    out_stream_TDATA_blk_n;
wire    ap_CS_fsm_state7;
wire    ap_CS_fsm_state8;
wire    ap_CS_fsm_state9;
reg   [31:0] threshold_q_read_reg_363;
wire   [31:0] score_q_fu_346_p3;
reg   [31:0] score_q_reg_374;
wire    ap_CS_fsm_state6;
wire   [0:0] pred_fu_354_p2;
reg   [0:0] pred_reg_379;
wire   [31:0] zext_ln93_fu_359_p1;
reg   [3:0] x_address0;
reg    x_ce0;
reg    x_we0;
wire   [31:0] x_q0;
reg   [3:0] x_1_address0;
reg    x_1_ce0;
reg    x_1_we0;
wire   [31:0] x_1_q0;
reg   [3:0] x_2_address0;
reg    x_2_ce0;
reg    x_2_we0;
wire   [31:0] x_2_q0;
reg   [3:0] x_3_address0;
reg    x_3_ce0;
reg    x_3_we0;
wire   [31:0] x_3_q0;
reg   [3:0] x_4_address0;
reg    x_4_ce0;
reg    x_4_we0;
wire   [31:0] x_4_q0;
reg   [3:0] x_5_address0;
reg    x_5_ce0;
reg    x_5_we0;
wire   [31:0] x_5_q0;
reg   [3:0] x_6_address0;
reg    x_6_ce0;
reg    x_6_we0;
wire   [31:0] x_6_q0;
reg   [3:0] x_7_address0;
reg    x_7_ce0;
reg    x_7_we0;
wire   [31:0] x_7_q0;
wire    grp_classify_Pipeline_READ_WINDOW_fu_164_ap_start;
wire    grp_classify_Pipeline_READ_WINDOW_fu_164_ap_done;
wire    grp_classify_Pipeline_READ_WINDOW_fu_164_ap_idle;
wire    grp_classify_Pipeline_READ_WINDOW_fu_164_ap_ready;
wire   [3:0] grp_classify_Pipeline_READ_WINDOW_fu_164_x_7_address0;
wire    grp_classify_Pipeline_READ_WINDOW_fu_164_x_7_ce0;
wire    grp_classify_Pipeline_READ_WINDOW_fu_164_x_7_we0;
wire   [31:0] grp_classify_Pipeline_READ_WINDOW_fu_164_x_7_d0;
wire   [3:0] grp_classify_Pipeline_READ_WINDOW_fu_164_x_6_address0;
wire    grp_classify_Pipeline_READ_WINDOW_fu_164_x_6_ce0;
wire    grp_classify_Pipeline_READ_WINDOW_fu_164_x_6_we0;
wire   [31:0] grp_classify_Pipeline_READ_WINDOW_fu_164_x_6_d0;
wire   [3:0] grp_classify_Pipeline_READ_WINDOW_fu_164_x_5_address0;
wire    grp_classify_Pipeline_READ_WINDOW_fu_164_x_5_ce0;
wire    grp_classify_Pipeline_READ_WINDOW_fu_164_x_5_we0;
wire   [31:0] grp_classify_Pipeline_READ_WINDOW_fu_164_x_5_d0;
wire   [3:0] grp_classify_Pipeline_READ_WINDOW_fu_164_x_4_address0;
wire    grp_classify_Pipeline_READ_WINDOW_fu_164_x_4_ce0;
wire    grp_classify_Pipeline_READ_WINDOW_fu_164_x_4_we0;
wire   [31:0] grp_classify_Pipeline_READ_WINDOW_fu_164_x_4_d0;
wire   [3:0] grp_classify_Pipeline_READ_WINDOW_fu_164_x_3_address0;
wire    grp_classify_Pipeline_READ_WINDOW_fu_164_x_3_ce0;
wire    grp_classify_Pipeline_READ_WINDOW_fu_164_x_3_we0;
wire   [31:0] grp_classify_Pipeline_READ_WINDOW_fu_164_x_3_d0;
wire   [3:0] grp_classify_Pipeline_READ_WINDOW_fu_164_x_2_address0;
wire    grp_classify_Pipeline_READ_WINDOW_fu_164_x_2_ce0;
wire    grp_classify_Pipeline_READ_WINDOW_fu_164_x_2_we0;
wire   [31:0] grp_classify_Pipeline_READ_WINDOW_fu_164_x_2_d0;
wire   [3:0] grp_classify_Pipeline_READ_WINDOW_fu_164_x_1_address0;
wire    grp_classify_Pipeline_READ_WINDOW_fu_164_x_1_ce0;
wire    grp_classify_Pipeline_READ_WINDOW_fu_164_x_1_we0;
wire   [31:0] grp_classify_Pipeline_READ_WINDOW_fu_164_x_1_d0;
wire   [3:0] grp_classify_Pipeline_READ_WINDOW_fu_164_x_address0;
wire    grp_classify_Pipeline_READ_WINDOW_fu_164_x_ce0;
wire    grp_classify_Pipeline_READ_WINDOW_fu_164_x_we0;
wire   [31:0] grp_classify_Pipeline_READ_WINDOW_fu_164_x_d0;
wire    grp_classify_Pipeline_READ_WINDOW_fu_164_in_stream_TREADY;
wire    grp_classify_Pipeline_MAC_LOOP_fu_184_ap_start;
wire    grp_classify_Pipeline_MAC_LOOP_fu_184_ap_done;
wire    grp_classify_Pipeline_MAC_LOOP_fu_184_ap_idle;
wire    grp_classify_Pipeline_MAC_LOOP_fu_184_ap_ready;
wire   [3:0] grp_classify_Pipeline_MAC_LOOP_fu_184_x_address0;
wire    grp_classify_Pipeline_MAC_LOOP_fu_184_x_ce0;
wire   [3:0] grp_classify_Pipeline_MAC_LOOP_fu_184_x_1_address0;
wire    grp_classify_Pipeline_MAC_LOOP_fu_184_x_1_ce0;
wire   [3:0] grp_classify_Pipeline_MAC_LOOP_fu_184_x_2_address0;
wire    grp_classify_Pipeline_MAC_LOOP_fu_184_x_2_ce0;
wire   [3:0] grp_classify_Pipeline_MAC_LOOP_fu_184_x_3_address0;
wire    grp_classify_Pipeline_MAC_LOOP_fu_184_x_3_ce0;
wire   [3:0] grp_classify_Pipeline_MAC_LOOP_fu_184_x_4_address0;
wire    grp_classify_Pipeline_MAC_LOOP_fu_184_x_4_ce0;
wire   [3:0] grp_classify_Pipeline_MAC_LOOP_fu_184_x_5_address0;
wire    grp_classify_Pipeline_MAC_LOOP_fu_184_x_5_ce0;
wire   [3:0] grp_classify_Pipeline_MAC_LOOP_fu_184_x_6_address0;
wire    grp_classify_Pipeline_MAC_LOOP_fu_184_x_6_ce0;
wire   [3:0] grp_classify_Pipeline_MAC_LOOP_fu_184_x_7_address0;
wire    grp_classify_Pipeline_MAC_LOOP_fu_184_x_7_ce0;
wire   [59:0] grp_classify_Pipeline_MAC_LOOP_fu_184_acc_out;
wire    grp_classify_Pipeline_MAC_LOOP_fu_184_acc_out_ap_vld;
reg    grp_classify_Pipeline_READ_WINDOW_fu_164_ap_start_reg;
wire    ap_CS_fsm_state2;
wire    ap_CS_fsm_state3;
reg    grp_classify_Pipeline_MAC_LOOP_fu_184_ap_start_reg;
wire    ap_CS_fsm_state4;
wire    ap_CS_fsm_state5;
wire   [47:0] tmp_1_fu_210_p4;
wire  signed [51:0] sext_ln43_fu_220_p1;
wire   [59:0] sub_ln47_fu_228_p2;
wire   [59:0] sub_ln47_1_fu_242_p2;
wire   [47:0] trunc_ln47_1_fu_248_p4;
wire  signed [51:0] sext_ln47_fu_258_p1;
wire   [47:0] trunc_ln47_2_fu_266_p4;
wire  signed [51:0] sext_ln47_1_fu_276_p1;
wire   [52:0] zext_ln47_1_fu_280_p1;
wire   [0:0] tmp_2_fu_234_p3;
wire   [52:0] zext_ln47_fu_262_p1;
wire   [52:0] sub_ln47_2_fu_284_p2;
wire   [0:0] tmp_fu_202_p3;
wire   [52:0] q_fu_290_p3;
wire   [52:0] zext_ln43_fu_224_p1;
wire   [52:0] q_1_fu_298_p3;
wire   [21:0] tmp_3_fu_306_p4;
wire   [0:0] icmp_ln34_fu_316_p2;
wire   [0:0] icmp_ln35_fu_322_p2;
wire   [0:0] or_ln34_fu_340_p2;
wire   [31:0] select_ln34_fu_332_p3;
wire   [31:0] trunc_ln36_fu_328_p1;
wire    regslice_both_out_stream_V_data_V_U_apdone_blk;
reg    ap_block_state9;
reg   [8:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
reg    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
reg    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
reg    ap_ST_fsm_state7_blk;
reg    ap_ST_fsm_state8_blk;
reg    ap_ST_fsm_state9_blk;
wire    regslice_both_in_stream_V_data_V_U_apdone_blk;
wire   [31:0] in_stream_TDATA_int_regslice;
wire    in_stream_TVALID_int_regslice;
reg    in_stream_TREADY_int_regslice;
wire    regslice_both_in_stream_V_data_V_U_ack_in;
wire    regslice_both_in_stream_V_keep_V_U_apdone_blk;
wire   [3:0] in_stream_TKEEP_int_regslice;
wire    regslice_both_in_stream_V_keep_V_U_vld_out;
wire    regslice_both_in_stream_V_keep_V_U_ack_in;
wire    regslice_both_in_stream_V_strb_V_U_apdone_blk;
wire   [3:0] in_stream_TSTRB_int_regslice;
wire    regslice_both_in_stream_V_strb_V_U_vld_out;
wire    regslice_both_in_stream_V_strb_V_U_ack_in;
wire    regslice_both_in_stream_V_last_V_U_apdone_blk;
wire   [0:0] in_stream_TLAST_int_regslice;
wire    regslice_both_in_stream_V_last_V_U_vld_out;
wire    regslice_both_in_stream_V_last_V_U_ack_in;
reg   [31:0] out_stream_TDATA_int_regslice;
reg    out_stream_TVALID_int_regslice;
wire    out_stream_TREADY_int_regslice;
wire    regslice_both_out_stream_V_data_V_U_vld_out;
wire    regslice_both_out_stream_V_keep_V_U_apdone_blk;
wire    regslice_both_out_stream_V_keep_V_U_ack_in_dummy;
wire    regslice_both_out_stream_V_keep_V_U_vld_out;
wire    regslice_both_out_stream_V_strb_V_U_apdone_blk;
wire    regslice_both_out_stream_V_strb_V_U_ack_in_dummy;
wire    regslice_both_out_stream_V_strb_V_U_vld_out;
wire    regslice_both_out_stream_V_last_V_U_apdone_blk;
reg   [0:0] out_stream_TLAST_int_regslice;
wire    regslice_both_out_stream_V_last_V_U_ack_in_dummy;
wire    regslice_both_out_stream_V_last_V_U_vld_out;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 9'd1;
#0 grp_classify_Pipeline_READ_WINDOW_fu_164_ap_start_reg = 1'b0;
#0 grp_classify_Pipeline_MAC_LOOP_fu_184_ap_start_reg = 1'b0;
end

classify_x_RAM_AUTO_1R1W #(
    .DataWidth( 32 ),
    .AddressRange( 15 ),
    .AddressWidth( 4 ))
x_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(x_address0),
    .ce0(x_ce0),
    .we0(x_we0),
    .d0(grp_classify_Pipeline_READ_WINDOW_fu_164_x_d0),
    .q0(x_q0)
);

classify_x_RAM_AUTO_1R1W #(
    .DataWidth( 32 ),
    .AddressRange( 15 ),
    .AddressWidth( 4 ))
x_1_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(x_1_address0),
    .ce0(x_1_ce0),
    .we0(x_1_we0),
    .d0(grp_classify_Pipeline_READ_WINDOW_fu_164_x_1_d0),
    .q0(x_1_q0)
);

classify_x_RAM_AUTO_1R1W #(
    .DataWidth( 32 ),
    .AddressRange( 15 ),
    .AddressWidth( 4 ))
x_2_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(x_2_address0),
    .ce0(x_2_ce0),
    .we0(x_2_we0),
    .d0(grp_classify_Pipeline_READ_WINDOW_fu_164_x_2_d0),
    .q0(x_2_q0)
);

classify_x_RAM_AUTO_1R1W #(
    .DataWidth( 32 ),
    .AddressRange( 15 ),
    .AddressWidth( 4 ))
x_3_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(x_3_address0),
    .ce0(x_3_ce0),
    .we0(x_3_we0),
    .d0(grp_classify_Pipeline_READ_WINDOW_fu_164_x_3_d0),
    .q0(x_3_q0)
);

classify_x_RAM_AUTO_1R1W #(
    .DataWidth( 32 ),
    .AddressRange( 15 ),
    .AddressWidth( 4 ))
x_4_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(x_4_address0),
    .ce0(x_4_ce0),
    .we0(x_4_we0),
    .d0(grp_classify_Pipeline_READ_WINDOW_fu_164_x_4_d0),
    .q0(x_4_q0)
);

classify_x_RAM_AUTO_1R1W #(
    .DataWidth( 32 ),
    .AddressRange( 15 ),
    .AddressWidth( 4 ))
x_5_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(x_5_address0),
    .ce0(x_5_ce0),
    .we0(x_5_we0),
    .d0(grp_classify_Pipeline_READ_WINDOW_fu_164_x_5_d0),
    .q0(x_5_q0)
);

classify_x_RAM_AUTO_1R1W #(
    .DataWidth( 32 ),
    .AddressRange( 15 ),
    .AddressWidth( 4 ))
x_6_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(x_6_address0),
    .ce0(x_6_ce0),
    .we0(x_6_we0),
    .d0(grp_classify_Pipeline_READ_WINDOW_fu_164_x_6_d0),
    .q0(x_6_q0)
);

classify_x_RAM_AUTO_1R1W #(
    .DataWidth( 32 ),
    .AddressRange( 15 ),
    .AddressWidth( 4 ))
x_7_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(x_7_address0),
    .ce0(x_7_ce0),
    .we0(x_7_we0),
    .d0(grp_classify_Pipeline_READ_WINDOW_fu_164_x_7_d0),
    .q0(x_7_q0)
);

classify_classify_Pipeline_READ_WINDOW grp_classify_Pipeline_READ_WINDOW_fu_164(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_classify_Pipeline_READ_WINDOW_fu_164_ap_start),
    .ap_done(grp_classify_Pipeline_READ_WINDOW_fu_164_ap_done),
    .ap_idle(grp_classify_Pipeline_READ_WINDOW_fu_164_ap_idle),
    .ap_ready(grp_classify_Pipeline_READ_WINDOW_fu_164_ap_ready),
    .in_stream_TVALID(in_stream_TVALID_int_regslice),
    .x_7_address0(grp_classify_Pipeline_READ_WINDOW_fu_164_x_7_address0),
    .x_7_ce0(grp_classify_Pipeline_READ_WINDOW_fu_164_x_7_ce0),
    .x_7_we0(grp_classify_Pipeline_READ_WINDOW_fu_164_x_7_we0),
    .x_7_d0(grp_classify_Pipeline_READ_WINDOW_fu_164_x_7_d0),
    .x_6_address0(grp_classify_Pipeline_READ_WINDOW_fu_164_x_6_address0),
    .x_6_ce0(grp_classify_Pipeline_READ_WINDOW_fu_164_x_6_ce0),
    .x_6_we0(grp_classify_Pipeline_READ_WINDOW_fu_164_x_6_we0),
    .x_6_d0(grp_classify_Pipeline_READ_WINDOW_fu_164_x_6_d0),
    .x_5_address0(grp_classify_Pipeline_READ_WINDOW_fu_164_x_5_address0),
    .x_5_ce0(grp_classify_Pipeline_READ_WINDOW_fu_164_x_5_ce0),
    .x_5_we0(grp_classify_Pipeline_READ_WINDOW_fu_164_x_5_we0),
    .x_5_d0(grp_classify_Pipeline_READ_WINDOW_fu_164_x_5_d0),
    .x_4_address0(grp_classify_Pipeline_READ_WINDOW_fu_164_x_4_address0),
    .x_4_ce0(grp_classify_Pipeline_READ_WINDOW_fu_164_x_4_ce0),
    .x_4_we0(grp_classify_Pipeline_READ_WINDOW_fu_164_x_4_we0),
    .x_4_d0(grp_classify_Pipeline_READ_WINDOW_fu_164_x_4_d0),
    .x_3_address0(grp_classify_Pipeline_READ_WINDOW_fu_164_x_3_address0),
    .x_3_ce0(grp_classify_Pipeline_READ_WINDOW_fu_164_x_3_ce0),
    .x_3_we0(grp_classify_Pipeline_READ_WINDOW_fu_164_x_3_we0),
    .x_3_d0(grp_classify_Pipeline_READ_WINDOW_fu_164_x_3_d0),
    .x_2_address0(grp_classify_Pipeline_READ_WINDOW_fu_164_x_2_address0),
    .x_2_ce0(grp_classify_Pipeline_READ_WINDOW_fu_164_x_2_ce0),
    .x_2_we0(grp_classify_Pipeline_READ_WINDOW_fu_164_x_2_we0),
    .x_2_d0(grp_classify_Pipeline_READ_WINDOW_fu_164_x_2_d0),
    .x_1_address0(grp_classify_Pipeline_READ_WINDOW_fu_164_x_1_address0),
    .x_1_ce0(grp_classify_Pipeline_READ_WINDOW_fu_164_x_1_ce0),
    .x_1_we0(grp_classify_Pipeline_READ_WINDOW_fu_164_x_1_we0),
    .x_1_d0(grp_classify_Pipeline_READ_WINDOW_fu_164_x_1_d0),
    .x_address0(grp_classify_Pipeline_READ_WINDOW_fu_164_x_address0),
    .x_ce0(grp_classify_Pipeline_READ_WINDOW_fu_164_x_ce0),
    .x_we0(grp_classify_Pipeline_READ_WINDOW_fu_164_x_we0),
    .x_d0(grp_classify_Pipeline_READ_WINDOW_fu_164_x_d0),
    .in_stream_TDATA(in_stream_TDATA_int_regslice),
    .in_stream_TREADY(grp_classify_Pipeline_READ_WINDOW_fu_164_in_stream_TREADY),
    .in_stream_TKEEP(in_stream_TKEEP_int_regslice),
    .in_stream_TSTRB(in_stream_TSTRB_int_regslice),
    .in_stream_TLAST(in_stream_TLAST_int_regslice)
);

classify_classify_Pipeline_MAC_LOOP grp_classify_Pipeline_MAC_LOOP_fu_184(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_classify_Pipeline_MAC_LOOP_fu_184_ap_start),
    .ap_done(grp_classify_Pipeline_MAC_LOOP_fu_184_ap_done),
    .ap_idle(grp_classify_Pipeline_MAC_LOOP_fu_184_ap_idle),
    .ap_ready(grp_classify_Pipeline_MAC_LOOP_fu_184_ap_ready),
    .x_address0(grp_classify_Pipeline_MAC_LOOP_fu_184_x_address0),
    .x_ce0(grp_classify_Pipeline_MAC_LOOP_fu_184_x_ce0),
    .x_q0(x_q0),
    .x_1_address0(grp_classify_Pipeline_MAC_LOOP_fu_184_x_1_address0),
    .x_1_ce0(grp_classify_Pipeline_MAC_LOOP_fu_184_x_1_ce0),
    .x_1_q0(x_1_q0),
    .x_2_address0(grp_classify_Pipeline_MAC_LOOP_fu_184_x_2_address0),
    .x_2_ce0(grp_classify_Pipeline_MAC_LOOP_fu_184_x_2_ce0),
    .x_2_q0(x_2_q0),
    .x_3_address0(grp_classify_Pipeline_MAC_LOOP_fu_184_x_3_address0),
    .x_3_ce0(grp_classify_Pipeline_MAC_LOOP_fu_184_x_3_ce0),
    .x_3_q0(x_3_q0),
    .x_4_address0(grp_classify_Pipeline_MAC_LOOP_fu_184_x_4_address0),
    .x_4_ce0(grp_classify_Pipeline_MAC_LOOP_fu_184_x_4_ce0),
    .x_4_q0(x_4_q0),
    .x_5_address0(grp_classify_Pipeline_MAC_LOOP_fu_184_x_5_address0),
    .x_5_ce0(grp_classify_Pipeline_MAC_LOOP_fu_184_x_5_ce0),
    .x_5_q0(x_5_q0),
    .x_6_address0(grp_classify_Pipeline_MAC_LOOP_fu_184_x_6_address0),
    .x_6_ce0(grp_classify_Pipeline_MAC_LOOP_fu_184_x_6_ce0),
    .x_6_q0(x_6_q0),
    .x_7_address0(grp_classify_Pipeline_MAC_LOOP_fu_184_x_7_address0),
    .x_7_ce0(grp_classify_Pipeline_MAC_LOOP_fu_184_x_7_ce0),
    .x_7_q0(x_7_q0),
    .acc_out(grp_classify_Pipeline_MAC_LOOP_fu_184_acc_out),
    .acc_out_ap_vld(grp_classify_Pipeline_MAC_LOOP_fu_184_acc_out_ap_vld)
);

classify_CTRL_s_axi #(
    .C_S_AXI_ADDR_WIDTH( C_S_AXI_CTRL_ADDR_WIDTH ),
    .C_S_AXI_DATA_WIDTH( C_S_AXI_CTRL_DATA_WIDTH ))
CTRL_s_axi_U(
    .AWVALID(s_axi_CTRL_AWVALID),
    .AWREADY(s_axi_CTRL_AWREADY),
    .AWADDR(s_axi_CTRL_AWADDR),
    .WVALID(s_axi_CTRL_WVALID),
    .WREADY(s_axi_CTRL_WREADY),
    .WDATA(s_axi_CTRL_WDATA),
    .WSTRB(s_axi_CTRL_WSTRB),
    .ARVALID(s_axi_CTRL_ARVALID),
    .ARREADY(s_axi_CTRL_ARREADY),
    .ARADDR(s_axi_CTRL_ARADDR),
    .RVALID(s_axi_CTRL_RVALID),
    .RREADY(s_axi_CTRL_RREADY),
    .RDATA(s_axi_CTRL_RDATA),
    .RRESP(s_axi_CTRL_RRESP),
    .BVALID(s_axi_CTRL_BVALID),
    .BREADY(s_axi_CTRL_BREADY),
    .BRESP(s_axi_CTRL_BRESP),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .threshold_q(threshold_q),
    .ap_start(ap_start),
    .interrupt(interrupt),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_idle(ap_idle)
);

classify_regslice_both #(
    .DataWidth( 32 ))
regslice_both_in_stream_V_data_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(in_stream_TDATA),
    .vld_in(in_stream_TVALID),
    .ack_in(regslice_both_in_stream_V_data_V_U_ack_in),
    .data_out(in_stream_TDATA_int_regslice),
    .vld_out(in_stream_TVALID_int_regslice),
    .ack_out(in_stream_TREADY_int_regslice),
    .apdone_blk(regslice_both_in_stream_V_data_V_U_apdone_blk)
);

classify_regslice_both #(
    .DataWidth( 4 ))
regslice_both_in_stream_V_keep_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(in_stream_TKEEP),
    .vld_in(in_stream_TVALID),
    .ack_in(regslice_both_in_stream_V_keep_V_U_ack_in),
    .data_out(in_stream_TKEEP_int_regslice),
    .vld_out(regslice_both_in_stream_V_keep_V_U_vld_out),
    .ack_out(in_stream_TREADY_int_regslice),
    .apdone_blk(regslice_both_in_stream_V_keep_V_U_apdone_blk)
);

classify_regslice_both #(
    .DataWidth( 4 ))
regslice_both_in_stream_V_strb_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(in_stream_TSTRB),
    .vld_in(in_stream_TVALID),
    .ack_in(regslice_both_in_stream_V_strb_V_U_ack_in),
    .data_out(in_stream_TSTRB_int_regslice),
    .vld_out(regslice_both_in_stream_V_strb_V_U_vld_out),
    .ack_out(in_stream_TREADY_int_regslice),
    .apdone_blk(regslice_both_in_stream_V_strb_V_U_apdone_blk)
);

classify_regslice_both #(
    .DataWidth( 1 ))
regslice_both_in_stream_V_last_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(in_stream_TLAST),
    .vld_in(in_stream_TVALID),
    .ack_in(regslice_both_in_stream_V_last_V_U_ack_in),
    .data_out(in_stream_TLAST_int_regslice),
    .vld_out(regslice_both_in_stream_V_last_V_U_vld_out),
    .ack_out(in_stream_TREADY_int_regslice),
    .apdone_blk(regslice_both_in_stream_V_last_V_U_apdone_blk)
);

classify_regslice_both #(
    .DataWidth( 32 ))
regslice_both_out_stream_V_data_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(out_stream_TDATA_int_regslice),
    .vld_in(out_stream_TVALID_int_regslice),
    .ack_in(out_stream_TREADY_int_regslice),
    .data_out(out_stream_TDATA),
    .vld_out(regslice_both_out_stream_V_data_V_U_vld_out),
    .ack_out(out_stream_TREADY),
    .apdone_blk(regslice_both_out_stream_V_data_V_U_apdone_blk)
);

classify_regslice_both #(
    .DataWidth( 4 ))
regslice_both_out_stream_V_keep_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(4'd15),
    .vld_in(out_stream_TVALID_int_regslice),
    .ack_in(regslice_both_out_stream_V_keep_V_U_ack_in_dummy),
    .data_out(out_stream_TKEEP),
    .vld_out(regslice_both_out_stream_V_keep_V_U_vld_out),
    .ack_out(out_stream_TREADY),
    .apdone_blk(regslice_both_out_stream_V_keep_V_U_apdone_blk)
);

classify_regslice_both #(
    .DataWidth( 4 ))
regslice_both_out_stream_V_strb_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(4'd15),
    .vld_in(out_stream_TVALID_int_regslice),
    .ack_in(regslice_both_out_stream_V_strb_V_U_ack_in_dummy),
    .data_out(out_stream_TSTRB),
    .vld_out(regslice_both_out_stream_V_strb_V_U_vld_out),
    .ack_out(out_stream_TREADY),
    .apdone_blk(regslice_both_out_stream_V_strb_V_U_apdone_blk)
);

classify_regslice_both #(
    .DataWidth( 1 ))
regslice_both_out_stream_V_last_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(out_stream_TLAST_int_regslice),
    .vld_in(out_stream_TVALID_int_regslice),
    .ack_in(regslice_both_out_stream_V_last_V_U_ack_in_dummy),
    .data_out(out_stream_TLAST),
    .vld_out(regslice_both_out_stream_V_last_V_U_vld_out),
    .ack_out(out_stream_TREADY),
    .apdone_blk(regslice_both_out_stream_V_last_V_U_apdone_blk)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_classify_Pipeline_MAC_LOOP_fu_184_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state4)) begin
            grp_classify_Pipeline_MAC_LOOP_fu_184_ap_start_reg <= 1'b1;
        end else if ((grp_classify_Pipeline_MAC_LOOP_fu_184_ap_ready == 1'b1)) begin
            grp_classify_Pipeline_MAC_LOOP_fu_184_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_classify_Pipeline_READ_WINDOW_fu_164_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state2)) begin
            grp_classify_Pipeline_READ_WINDOW_fu_164_ap_start_reg <= 1'b1;
        end else if ((grp_classify_Pipeline_READ_WINDOW_fu_164_ap_ready == 1'b1)) begin
            grp_classify_Pipeline_READ_WINDOW_fu_164_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        pred_reg_379 <= pred_fu_354_p2;
        score_q_reg_374 <= score_q_fu_346_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        threshold_q_read_reg_363 <= threshold_q;
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

always @ (*) begin
    if ((grp_classify_Pipeline_READ_WINDOW_fu_164_ap_done == 1'b0)) begin
        ap_ST_fsm_state3_blk = 1'b1;
    end else begin
        ap_ST_fsm_state3_blk = 1'b0;
    end
end

assign ap_ST_fsm_state4_blk = 1'b0;

always @ (*) begin
    if ((grp_classify_Pipeline_MAC_LOOP_fu_184_ap_done == 1'b0)) begin
        ap_ST_fsm_state5_blk = 1'b1;
    end else begin
        ap_ST_fsm_state5_blk = 1'b0;
    end
end

assign ap_ST_fsm_state6_blk = 1'b0;

always @ (*) begin
    if ((out_stream_TREADY_int_regslice == 1'b0)) begin
        ap_ST_fsm_state7_blk = 1'b1;
    end else begin
        ap_ST_fsm_state7_blk = 1'b0;
    end
end

always @ (*) begin
    if ((out_stream_TREADY_int_regslice == 1'b0)) begin
        ap_ST_fsm_state8_blk = 1'b1;
    end else begin
        ap_ST_fsm_state8_blk = 1'b0;
    end
end

always @ (*) begin
    if (((out_stream_TREADY_int_regslice == 1'b0) | (1'b1 == ap_block_state9))) begin
        ap_ST_fsm_state9_blk = 1'b1;
    end else begin
        ap_ST_fsm_state9_blk = 1'b0;
    end
end

always @ (*) begin
    if ((~((out_stream_TREADY_int_regslice == 1'b0) | (1'b1 == ap_block_state9)) & (1'b1 == ap_CS_fsm_state9))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((~((out_stream_TREADY_int_regslice == 1'b0) | (1'b1 == ap_block_state9)) & (1'b1 == ap_CS_fsm_state9))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        in_stream_TREADY_int_regslice = grp_classify_Pipeline_READ_WINDOW_fu_164_in_stream_TREADY;
    end else begin
        in_stream_TREADY_int_regslice = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state7))) begin
        out_stream_TDATA_blk_n = out_stream_TREADY_int_regslice;
    end else begin
        out_stream_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((out_stream_TREADY_int_regslice == 1'b1)) begin
        if ((1'b1 == ap_CS_fsm_state8)) begin
            out_stream_TDATA_int_regslice = score_q_reg_374;
        end else if ((1'b1 == ap_CS_fsm_state7)) begin
            out_stream_TDATA_int_regslice = zext_ln93_fu_359_p1;
        end else begin
            out_stream_TDATA_int_regslice = 'bx;
        end
    end else begin
        out_stream_TDATA_int_regslice = 'bx;
    end
end

always @ (*) begin
    if ((out_stream_TREADY_int_regslice == 1'b1)) begin
        if ((1'b1 == ap_CS_fsm_state8)) begin
            out_stream_TLAST_int_regslice = 1'd1;
        end else if ((1'b1 == ap_CS_fsm_state7)) begin
            out_stream_TLAST_int_regslice = 1'd0;
        end else begin
            out_stream_TLAST_int_regslice = 'bx;
        end
    end else begin
        out_stream_TLAST_int_regslice = 'bx;
    end
end

always @ (*) begin
    if ((((out_stream_TREADY_int_regslice == 1'b1) & (1'b1 == ap_CS_fsm_state8)) | ((out_stream_TREADY_int_regslice == 1'b1) & (1'b1 == ap_CS_fsm_state7)))) begin
        out_stream_TVALID_int_regslice = 1'b1;
    end else begin
        out_stream_TVALID_int_regslice = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        x_1_address0 = grp_classify_Pipeline_MAC_LOOP_fu_184_x_1_address0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        x_1_address0 = grp_classify_Pipeline_READ_WINDOW_fu_164_x_1_address0;
    end else begin
        x_1_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        x_1_ce0 = grp_classify_Pipeline_MAC_LOOP_fu_184_x_1_ce0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        x_1_ce0 = grp_classify_Pipeline_READ_WINDOW_fu_164_x_1_ce0;
    end else begin
        x_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        x_1_we0 = grp_classify_Pipeline_READ_WINDOW_fu_164_x_1_we0;
    end else begin
        x_1_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        x_2_address0 = grp_classify_Pipeline_MAC_LOOP_fu_184_x_2_address0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        x_2_address0 = grp_classify_Pipeline_READ_WINDOW_fu_164_x_2_address0;
    end else begin
        x_2_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        x_2_ce0 = grp_classify_Pipeline_MAC_LOOP_fu_184_x_2_ce0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        x_2_ce0 = grp_classify_Pipeline_READ_WINDOW_fu_164_x_2_ce0;
    end else begin
        x_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        x_2_we0 = grp_classify_Pipeline_READ_WINDOW_fu_164_x_2_we0;
    end else begin
        x_2_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        x_3_address0 = grp_classify_Pipeline_MAC_LOOP_fu_184_x_3_address0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        x_3_address0 = grp_classify_Pipeline_READ_WINDOW_fu_164_x_3_address0;
    end else begin
        x_3_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        x_3_ce0 = grp_classify_Pipeline_MAC_LOOP_fu_184_x_3_ce0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        x_3_ce0 = grp_classify_Pipeline_READ_WINDOW_fu_164_x_3_ce0;
    end else begin
        x_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        x_3_we0 = grp_classify_Pipeline_READ_WINDOW_fu_164_x_3_we0;
    end else begin
        x_3_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        x_4_address0 = grp_classify_Pipeline_MAC_LOOP_fu_184_x_4_address0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        x_4_address0 = grp_classify_Pipeline_READ_WINDOW_fu_164_x_4_address0;
    end else begin
        x_4_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        x_4_ce0 = grp_classify_Pipeline_MAC_LOOP_fu_184_x_4_ce0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        x_4_ce0 = grp_classify_Pipeline_READ_WINDOW_fu_164_x_4_ce0;
    end else begin
        x_4_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        x_4_we0 = grp_classify_Pipeline_READ_WINDOW_fu_164_x_4_we0;
    end else begin
        x_4_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        x_5_address0 = grp_classify_Pipeline_MAC_LOOP_fu_184_x_5_address0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        x_5_address0 = grp_classify_Pipeline_READ_WINDOW_fu_164_x_5_address0;
    end else begin
        x_5_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        x_5_ce0 = grp_classify_Pipeline_MAC_LOOP_fu_184_x_5_ce0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        x_5_ce0 = grp_classify_Pipeline_READ_WINDOW_fu_164_x_5_ce0;
    end else begin
        x_5_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        x_5_we0 = grp_classify_Pipeline_READ_WINDOW_fu_164_x_5_we0;
    end else begin
        x_5_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        x_6_address0 = grp_classify_Pipeline_MAC_LOOP_fu_184_x_6_address0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        x_6_address0 = grp_classify_Pipeline_READ_WINDOW_fu_164_x_6_address0;
    end else begin
        x_6_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        x_6_ce0 = grp_classify_Pipeline_MAC_LOOP_fu_184_x_6_ce0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        x_6_ce0 = grp_classify_Pipeline_READ_WINDOW_fu_164_x_6_ce0;
    end else begin
        x_6_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        x_6_we0 = grp_classify_Pipeline_READ_WINDOW_fu_164_x_6_we0;
    end else begin
        x_6_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        x_7_address0 = grp_classify_Pipeline_MAC_LOOP_fu_184_x_7_address0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        x_7_address0 = grp_classify_Pipeline_READ_WINDOW_fu_164_x_7_address0;
    end else begin
        x_7_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        x_7_ce0 = grp_classify_Pipeline_MAC_LOOP_fu_184_x_7_ce0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        x_7_ce0 = grp_classify_Pipeline_READ_WINDOW_fu_164_x_7_ce0;
    end else begin
        x_7_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        x_7_we0 = grp_classify_Pipeline_READ_WINDOW_fu_164_x_7_we0;
    end else begin
        x_7_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        x_address0 = grp_classify_Pipeline_MAC_LOOP_fu_184_x_address0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        x_address0 = grp_classify_Pipeline_READ_WINDOW_fu_164_x_address0;
    end else begin
        x_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        x_ce0 = grp_classify_Pipeline_MAC_LOOP_fu_184_x_ce0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        x_ce0 = grp_classify_Pipeline_READ_WINDOW_fu_164_x_ce0;
    end else begin
        x_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        x_we0 = grp_classify_Pipeline_READ_WINDOW_fu_164_x_we0;
    end else begin
        x_we0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            if (((1'b1 == ap_CS_fsm_state3) & (grp_classify_Pipeline_READ_WINDOW_fu_164_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            if (((1'b1 == ap_CS_fsm_state5) & (grp_classify_Pipeline_MAC_LOOP_fu_184_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            if (((out_stream_TREADY_int_regslice == 1'b1) & (1'b1 == ap_CS_fsm_state7))) begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end
        end
        ap_ST_fsm_state8 : begin
            if (((out_stream_TREADY_int_regslice == 1'b1) & (1'b1 == ap_CS_fsm_state8))) begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end
        end
        ap_ST_fsm_state9 : begin
            if ((~((out_stream_TREADY_int_regslice == 1'b0) | (1'b1 == ap_block_state9)) & (1'b1 == ap_CS_fsm_state9))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

always @ (*) begin
    ap_block_state9 = ((out_stream_TREADY_int_regslice == 1'b0) | (regslice_both_out_stream_V_data_V_U_apdone_blk == 1'b1));
end

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign grp_classify_Pipeline_MAC_LOOP_fu_184_ap_start = grp_classify_Pipeline_MAC_LOOP_fu_184_ap_start_reg;

assign grp_classify_Pipeline_READ_WINDOW_fu_164_ap_start = grp_classify_Pipeline_READ_WINDOW_fu_164_ap_start_reg;

assign icmp_ln34_fu_316_p2 = (($signed(tmp_3_fu_306_p4) > $signed(22'd0)) ? 1'b1 : 1'b0);

assign icmp_ln35_fu_322_p2 = (($signed(q_1_fu_298_p3) < $signed(53'd9007197107257344)) ? 1'b1 : 1'b0);

assign in_stream_TREADY = regslice_both_in_stream_V_data_V_U_ack_in;

assign or_ln34_fu_340_p2 = (icmp_ln35_fu_322_p2 | icmp_ln34_fu_316_p2);

assign out_stream_TVALID = regslice_both_out_stream_V_data_V_U_vld_out;

assign pred_fu_354_p2 = (($signed(score_q_fu_346_p3) > $signed(threshold_q_read_reg_363)) ? 1'b1 : 1'b0);

assign q_1_fu_298_p3 = ((tmp_fu_202_p3[0:0] == 1'b1) ? q_fu_290_p3 : zext_ln43_fu_224_p1);

assign q_fu_290_p3 = ((tmp_2_fu_234_p3[0:0] == 1'b1) ? zext_ln47_fu_262_p1 : sub_ln47_2_fu_284_p2);

assign score_q_fu_346_p3 = ((or_ln34_fu_340_p2[0:0] == 1'b1) ? select_ln34_fu_332_p3 : trunc_ln36_fu_328_p1);

assign select_ln34_fu_332_p3 = ((icmp_ln34_fu_316_p2[0:0] == 1'b1) ? 32'd2147483647 : 32'd2147483648);

assign sext_ln43_fu_220_p1 = $signed(tmp_1_fu_210_p4);

assign sext_ln47_1_fu_276_p1 = $signed(trunc_ln47_2_fu_266_p4);

assign sext_ln47_fu_258_p1 = $signed(trunc_ln47_1_fu_248_p4);

assign sub_ln47_1_fu_242_p2 = (60'd0 - sub_ln47_fu_228_p2);

assign sub_ln47_2_fu_284_p2 = (53'd0 - zext_ln47_1_fu_280_p1);

assign sub_ln47_fu_228_p2 = (60'd4095 - grp_classify_Pipeline_MAC_LOOP_fu_184_acc_out);

assign tmp_1_fu_210_p4 = {{grp_classify_Pipeline_MAC_LOOP_fu_184_acc_out[59:12]}};

assign tmp_2_fu_234_p3 = sub_ln47_fu_228_p2[32'd59];

assign tmp_3_fu_306_p4 = {{q_1_fu_298_p3[52:31]}};

assign tmp_fu_202_p3 = grp_classify_Pipeline_MAC_LOOP_fu_184_acc_out[32'd59];

assign trunc_ln36_fu_328_p1 = q_1_fu_298_p3[31:0];

assign trunc_ln47_1_fu_248_p4 = {{sub_ln47_1_fu_242_p2[59:12]}};

assign trunc_ln47_2_fu_266_p4 = {{sub_ln47_fu_228_p2[59:12]}};

assign zext_ln43_fu_224_p1 = $unsigned(sext_ln43_fu_220_p1);

assign zext_ln47_1_fu_280_p1 = $unsigned(sext_ln47_1_fu_276_p1);

assign zext_ln47_fu_262_p1 = $unsigned(sext_ln47_fu_258_p1);

assign zext_ln93_fu_359_p1 = pred_reg_379;


reg find_kernel_block = 0;
// synthesis translate_off
`include "classify_hls_deadlock_kernel_monitor_top.vh"
// synthesis translate_on

endmodule //classify

