-- ==============================================================
-- Generated by Vitis HLS v2023.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity eye_feature_topk_sum_hist is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    runs_0_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    runs_0_ce0 : OUT STD_LOGIC;
    runs_0_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
    runs_1_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    runs_1_ce0 : OUT STD_LOGIC;
    runs_1_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
    runs_2_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    runs_2_ce0 : OUT STD_LOGIC;
    runs_2_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
    runs_3_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    runs_3_ce0 : OUT STD_LOGIC;
    runs_3_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
    cw : IN STD_LOGIC_VECTOR (7 downto 0);
    ch : IN STD_LOGIC_VECTOR (6 downto 0);
    k : IN STD_LOGIC_VECTOR (5 downto 0);
    ap_return : OUT STD_LOGIC_VECTOR (31 downto 0) );
end;


architecture behav of eye_feature_topk_sum_hist is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (6 downto 0) := "0000001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (6 downto 0) := "0000010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (6 downto 0) := "0000100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (6 downto 0) := "0001000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (6 downto 0) := "0010000";
    constant ap_ST_fsm_state6 : STD_LOGIC_VECTOR (6 downto 0) := "0100000";
    constant ap_ST_fsm_state7 : STD_LOGIC_VECTOR (6 downto 0) := "1000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (6 downto 0) := "0000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal hist_address0 : STD_LOGIC_VECTOR (4 downto 0);
    signal hist_ce0 : STD_LOGIC;
    signal hist_we0 : STD_LOGIC;
    signal hist_d0 : STD_LOGIC_VECTOR (15 downto 0);
    signal hist_q0 : STD_LOGIC_VECTOR (15 downto 0);
    signal hist_1_address0 : STD_LOGIC_VECTOR (4 downto 0);
    signal hist_1_ce0 : STD_LOGIC;
    signal hist_1_we0 : STD_LOGIC;
    signal hist_1_d0 : STD_LOGIC_VECTOR (15 downto 0);
    signal hist_1_q0 : STD_LOGIC_VECTOR (15 downto 0);
    signal hist_2_address0 : STD_LOGIC_VECTOR (4 downto 0);
    signal hist_2_ce0 : STD_LOGIC;
    signal hist_2_we0 : STD_LOGIC;
    signal hist_2_d0 : STD_LOGIC_VECTOR (15 downto 0);
    signal hist_2_q0 : STD_LOGIC_VECTOR (15 downto 0);
    signal hist_3_address0 : STD_LOGIC_VECTOR (4 downto 0);
    signal hist_3_ce0 : STD_LOGIC;
    signal hist_3_we0 : STD_LOGIC;
    signal hist_3_d0 : STD_LOGIC_VECTOR (15 downto 0);
    signal hist_3_q0 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_topk_sum_hist_Pipeline_INIT_HIST_fu_66_ap_start : STD_LOGIC;
    signal grp_topk_sum_hist_Pipeline_INIT_HIST_fu_66_ap_done : STD_LOGIC;
    signal grp_topk_sum_hist_Pipeline_INIT_HIST_fu_66_ap_idle : STD_LOGIC;
    signal grp_topk_sum_hist_Pipeline_INIT_HIST_fu_66_ap_ready : STD_LOGIC;
    signal grp_topk_sum_hist_Pipeline_INIT_HIST_fu_66_hist_3_address0 : STD_LOGIC_VECTOR (4 downto 0);
    signal grp_topk_sum_hist_Pipeline_INIT_HIST_fu_66_hist_3_ce0 : STD_LOGIC;
    signal grp_topk_sum_hist_Pipeline_INIT_HIST_fu_66_hist_3_we0 : STD_LOGIC;
    signal grp_topk_sum_hist_Pipeline_INIT_HIST_fu_66_hist_3_d0 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_topk_sum_hist_Pipeline_INIT_HIST_fu_66_hist_2_address0 : STD_LOGIC_VECTOR (4 downto 0);
    signal grp_topk_sum_hist_Pipeline_INIT_HIST_fu_66_hist_2_ce0 : STD_LOGIC;
    signal grp_topk_sum_hist_Pipeline_INIT_HIST_fu_66_hist_2_we0 : STD_LOGIC;
    signal grp_topk_sum_hist_Pipeline_INIT_HIST_fu_66_hist_2_d0 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_topk_sum_hist_Pipeline_INIT_HIST_fu_66_hist_1_address0 : STD_LOGIC_VECTOR (4 downto 0);
    signal grp_topk_sum_hist_Pipeline_INIT_HIST_fu_66_hist_1_ce0 : STD_LOGIC;
    signal grp_topk_sum_hist_Pipeline_INIT_HIST_fu_66_hist_1_we0 : STD_LOGIC;
    signal grp_topk_sum_hist_Pipeline_INIT_HIST_fu_66_hist_1_d0 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_topk_sum_hist_Pipeline_INIT_HIST_fu_66_hist_address0 : STD_LOGIC_VECTOR (4 downto 0);
    signal grp_topk_sum_hist_Pipeline_INIT_HIST_fu_66_hist_ce0 : STD_LOGIC;
    signal grp_topk_sum_hist_Pipeline_INIT_HIST_fu_66_hist_we0 : STD_LOGIC;
    signal grp_topk_sum_hist_Pipeline_INIT_HIST_fu_66_hist_d0 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_topk_sum_hist_Pipeline_BUILD_HIST_fu_78_ap_start : STD_LOGIC;
    signal grp_topk_sum_hist_Pipeline_BUILD_HIST_fu_78_ap_done : STD_LOGIC;
    signal grp_topk_sum_hist_Pipeline_BUILD_HIST_fu_78_ap_idle : STD_LOGIC;
    signal grp_topk_sum_hist_Pipeline_BUILD_HIST_fu_78_ap_ready : STD_LOGIC;
    signal grp_topk_sum_hist_Pipeline_BUILD_HIST_fu_78_runs_0_address0 : STD_LOGIC_VECTOR (4 downto 0);
    signal grp_topk_sum_hist_Pipeline_BUILD_HIST_fu_78_runs_0_ce0 : STD_LOGIC;
    signal grp_topk_sum_hist_Pipeline_BUILD_HIST_fu_78_runs_1_address0 : STD_LOGIC_VECTOR (4 downto 0);
    signal grp_topk_sum_hist_Pipeline_BUILD_HIST_fu_78_runs_1_ce0 : STD_LOGIC;
    signal grp_topk_sum_hist_Pipeline_BUILD_HIST_fu_78_runs_2_address0 : STD_LOGIC_VECTOR (4 downto 0);
    signal grp_topk_sum_hist_Pipeline_BUILD_HIST_fu_78_runs_2_ce0 : STD_LOGIC;
    signal grp_topk_sum_hist_Pipeline_BUILD_HIST_fu_78_runs_3_address0 : STD_LOGIC_VECTOR (4 downto 0);
    signal grp_topk_sum_hist_Pipeline_BUILD_HIST_fu_78_runs_3_ce0 : STD_LOGIC;
    signal grp_topk_sum_hist_Pipeline_BUILD_HIST_fu_78_hist_address0 : STD_LOGIC_VECTOR (4 downto 0);
    signal grp_topk_sum_hist_Pipeline_BUILD_HIST_fu_78_hist_ce0 : STD_LOGIC;
    signal grp_topk_sum_hist_Pipeline_BUILD_HIST_fu_78_hist_we0 : STD_LOGIC;
    signal grp_topk_sum_hist_Pipeline_BUILD_HIST_fu_78_hist_d0 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_topk_sum_hist_Pipeline_BUILD_HIST_fu_78_hist_1_address0 : STD_LOGIC_VECTOR (4 downto 0);
    signal grp_topk_sum_hist_Pipeline_BUILD_HIST_fu_78_hist_1_ce0 : STD_LOGIC;
    signal grp_topk_sum_hist_Pipeline_BUILD_HIST_fu_78_hist_1_we0 : STD_LOGIC;
    signal grp_topk_sum_hist_Pipeline_BUILD_HIST_fu_78_hist_1_d0 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_topk_sum_hist_Pipeline_BUILD_HIST_fu_78_hist_2_address0 : STD_LOGIC_VECTOR (4 downto 0);
    signal grp_topk_sum_hist_Pipeline_BUILD_HIST_fu_78_hist_2_ce0 : STD_LOGIC;
    signal grp_topk_sum_hist_Pipeline_BUILD_HIST_fu_78_hist_2_we0 : STD_LOGIC;
    signal grp_topk_sum_hist_Pipeline_BUILD_HIST_fu_78_hist_2_d0 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_topk_sum_hist_Pipeline_BUILD_HIST_fu_78_hist_3_address0 : STD_LOGIC_VECTOR (4 downto 0);
    signal grp_topk_sum_hist_Pipeline_BUILD_HIST_fu_78_hist_3_ce0 : STD_LOGIC;
    signal grp_topk_sum_hist_Pipeline_BUILD_HIST_fu_78_hist_3_we0 : STD_LOGIC;
    signal grp_topk_sum_hist_Pipeline_BUILD_HIST_fu_78_hist_3_d0 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_topk_sum_hist_Pipeline_ACCUM_TOPK_fu_100_ap_start : STD_LOGIC;
    signal grp_topk_sum_hist_Pipeline_ACCUM_TOPK_fu_100_ap_done : STD_LOGIC;
    signal grp_topk_sum_hist_Pipeline_ACCUM_TOPK_fu_100_ap_idle : STD_LOGIC;
    signal grp_topk_sum_hist_Pipeline_ACCUM_TOPK_fu_100_ap_ready : STD_LOGIC;
    signal grp_topk_sum_hist_Pipeline_ACCUM_TOPK_fu_100_hist_address0 : STD_LOGIC_VECTOR (4 downto 0);
    signal grp_topk_sum_hist_Pipeline_ACCUM_TOPK_fu_100_hist_ce0 : STD_LOGIC;
    signal grp_topk_sum_hist_Pipeline_ACCUM_TOPK_fu_100_hist_1_address0 : STD_LOGIC_VECTOR (4 downto 0);
    signal grp_topk_sum_hist_Pipeline_ACCUM_TOPK_fu_100_hist_1_ce0 : STD_LOGIC;
    signal grp_topk_sum_hist_Pipeline_ACCUM_TOPK_fu_100_hist_2_address0 : STD_LOGIC_VECTOR (4 downto 0);
    signal grp_topk_sum_hist_Pipeline_ACCUM_TOPK_fu_100_hist_2_ce0 : STD_LOGIC;
    signal grp_topk_sum_hist_Pipeline_ACCUM_TOPK_fu_100_hist_3_address0 : STD_LOGIC_VECTOR (4 downto 0);
    signal grp_topk_sum_hist_Pipeline_ACCUM_TOPK_fu_100_hist_3_ce0 : STD_LOGIC;
    signal grp_topk_sum_hist_Pipeline_ACCUM_TOPK_fu_100_sum_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_topk_sum_hist_Pipeline_ACCUM_TOPK_fu_100_sum_out_ap_vld : STD_LOGIC;
    signal grp_topk_sum_hist_Pipeline_INIT_HIST_fu_66_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal grp_topk_sum_hist_Pipeline_BUILD_HIST_fu_78_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal grp_topk_sum_hist_Pipeline_ACCUM_TOPK_fu_100_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state6 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state6 : signal is "none";
    signal ap_CS_fsm_state7 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state7 : signal is "none";
    signal ap_NS_fsm : STD_LOGIC_VECTOR (6 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_ST_fsm_state5_blk : STD_LOGIC;
    signal ap_ST_fsm_state6_blk : STD_LOGIC;
    signal ap_ST_fsm_state7_blk : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component eye_feature_topk_sum_hist_Pipeline_INIT_HIST IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        hist_3_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
        hist_3_ce0 : OUT STD_LOGIC;
        hist_3_we0 : OUT STD_LOGIC;
        hist_3_d0 : OUT STD_LOGIC_VECTOR (15 downto 0);
        hist_2_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
        hist_2_ce0 : OUT STD_LOGIC;
        hist_2_we0 : OUT STD_LOGIC;
        hist_2_d0 : OUT STD_LOGIC_VECTOR (15 downto 0);
        hist_1_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
        hist_1_ce0 : OUT STD_LOGIC;
        hist_1_we0 : OUT STD_LOGIC;
        hist_1_d0 : OUT STD_LOGIC_VECTOR (15 downto 0);
        hist_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
        hist_ce0 : OUT STD_LOGIC;
        hist_we0 : OUT STD_LOGIC;
        hist_d0 : OUT STD_LOGIC_VECTOR (15 downto 0) );
    end component;


    component eye_feature_topk_sum_hist_Pipeline_BUILD_HIST IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        cw : IN STD_LOGIC_VECTOR (7 downto 0);
        runs_0_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
        runs_0_ce0 : OUT STD_LOGIC;
        runs_0_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
        runs_1_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
        runs_1_ce0 : OUT STD_LOGIC;
        runs_1_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
        runs_2_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
        runs_2_ce0 : OUT STD_LOGIC;
        runs_2_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
        runs_3_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
        runs_3_ce0 : OUT STD_LOGIC;
        runs_3_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
        ch_cast : IN STD_LOGIC_VECTOR (6 downto 0);
        ch : IN STD_LOGIC_VECTOR (6 downto 0);
        hist_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
        hist_ce0 : OUT STD_LOGIC;
        hist_we0 : OUT STD_LOGIC;
        hist_d0 : OUT STD_LOGIC_VECTOR (15 downto 0);
        hist_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
        hist_1_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
        hist_1_ce0 : OUT STD_LOGIC;
        hist_1_we0 : OUT STD_LOGIC;
        hist_1_d0 : OUT STD_LOGIC_VECTOR (15 downto 0);
        hist_1_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
        hist_2_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
        hist_2_ce0 : OUT STD_LOGIC;
        hist_2_we0 : OUT STD_LOGIC;
        hist_2_d0 : OUT STD_LOGIC_VECTOR (15 downto 0);
        hist_2_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
        hist_3_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
        hist_3_ce0 : OUT STD_LOGIC;
        hist_3_we0 : OUT STD_LOGIC;
        hist_3_d0 : OUT STD_LOGIC_VECTOR (15 downto 0);
        hist_3_q0 : IN STD_LOGIC_VECTOR (15 downto 0) );
    end component;


    component eye_feature_topk_sum_hist_Pipeline_ACCUM_TOPK IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        k_cast : IN STD_LOGIC_VECTOR (5 downto 0);
        zext_ln258 : IN STD_LOGIC_VECTOR (6 downto 0);
        hist_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
        hist_ce0 : OUT STD_LOGIC;
        hist_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
        hist_1_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
        hist_1_ce0 : OUT STD_LOGIC;
        hist_1_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
        hist_2_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
        hist_2_ce0 : OUT STD_LOGIC;
        hist_2_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
        hist_3_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
        hist_3_ce0 : OUT STD_LOGIC;
        hist_3_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
        sum_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        sum_out_ap_vld : OUT STD_LOGIC );
    end component;


    component eye_feature_topk_sum_hist_hist_RAM_AUTO_1R1W IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (4 downto 0);
        ce0 : IN STD_LOGIC;
        we0 : IN STD_LOGIC;
        d0 : IN STD_LOGIC_VECTOR (15 downto 0);
        q0 : OUT STD_LOGIC_VECTOR (15 downto 0) );
    end component;



begin
    hist_U : component eye_feature_topk_sum_hist_hist_RAM_AUTO_1R1W
    generic map (
        DataWidth => 16,
        AddressRange => 17,
        AddressWidth => 5)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => hist_address0,
        ce0 => hist_ce0,
        we0 => hist_we0,
        d0 => hist_d0,
        q0 => hist_q0);

    hist_1_U : component eye_feature_topk_sum_hist_hist_RAM_AUTO_1R1W
    generic map (
        DataWidth => 16,
        AddressRange => 17,
        AddressWidth => 5)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => hist_1_address0,
        ce0 => hist_1_ce0,
        we0 => hist_1_we0,
        d0 => hist_1_d0,
        q0 => hist_1_q0);

    hist_2_U : component eye_feature_topk_sum_hist_hist_RAM_AUTO_1R1W
    generic map (
        DataWidth => 16,
        AddressRange => 17,
        AddressWidth => 5)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => hist_2_address0,
        ce0 => hist_2_ce0,
        we0 => hist_2_we0,
        d0 => hist_2_d0,
        q0 => hist_2_q0);

    hist_3_U : component eye_feature_topk_sum_hist_hist_RAM_AUTO_1R1W
    generic map (
        DataWidth => 16,
        AddressRange => 17,
        AddressWidth => 5)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => hist_3_address0,
        ce0 => hist_3_ce0,
        we0 => hist_3_we0,
        d0 => hist_3_d0,
        q0 => hist_3_q0);

    grp_topk_sum_hist_Pipeline_INIT_HIST_fu_66 : component eye_feature_topk_sum_hist_Pipeline_INIT_HIST
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_topk_sum_hist_Pipeline_INIT_HIST_fu_66_ap_start,
        ap_done => grp_topk_sum_hist_Pipeline_INIT_HIST_fu_66_ap_done,
        ap_idle => grp_topk_sum_hist_Pipeline_INIT_HIST_fu_66_ap_idle,
        ap_ready => grp_topk_sum_hist_Pipeline_INIT_HIST_fu_66_ap_ready,
        hist_3_address0 => grp_topk_sum_hist_Pipeline_INIT_HIST_fu_66_hist_3_address0,
        hist_3_ce0 => grp_topk_sum_hist_Pipeline_INIT_HIST_fu_66_hist_3_ce0,
        hist_3_we0 => grp_topk_sum_hist_Pipeline_INIT_HIST_fu_66_hist_3_we0,
        hist_3_d0 => grp_topk_sum_hist_Pipeline_INIT_HIST_fu_66_hist_3_d0,
        hist_2_address0 => grp_topk_sum_hist_Pipeline_INIT_HIST_fu_66_hist_2_address0,
        hist_2_ce0 => grp_topk_sum_hist_Pipeline_INIT_HIST_fu_66_hist_2_ce0,
        hist_2_we0 => grp_topk_sum_hist_Pipeline_INIT_HIST_fu_66_hist_2_we0,
        hist_2_d0 => grp_topk_sum_hist_Pipeline_INIT_HIST_fu_66_hist_2_d0,
        hist_1_address0 => grp_topk_sum_hist_Pipeline_INIT_HIST_fu_66_hist_1_address0,
        hist_1_ce0 => grp_topk_sum_hist_Pipeline_INIT_HIST_fu_66_hist_1_ce0,
        hist_1_we0 => grp_topk_sum_hist_Pipeline_INIT_HIST_fu_66_hist_1_we0,
        hist_1_d0 => grp_topk_sum_hist_Pipeline_INIT_HIST_fu_66_hist_1_d0,
        hist_address0 => grp_topk_sum_hist_Pipeline_INIT_HIST_fu_66_hist_address0,
        hist_ce0 => grp_topk_sum_hist_Pipeline_INIT_HIST_fu_66_hist_ce0,
        hist_we0 => grp_topk_sum_hist_Pipeline_INIT_HIST_fu_66_hist_we0,
        hist_d0 => grp_topk_sum_hist_Pipeline_INIT_HIST_fu_66_hist_d0);

    grp_topk_sum_hist_Pipeline_BUILD_HIST_fu_78 : component eye_feature_topk_sum_hist_Pipeline_BUILD_HIST
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_topk_sum_hist_Pipeline_BUILD_HIST_fu_78_ap_start,
        ap_done => grp_topk_sum_hist_Pipeline_BUILD_HIST_fu_78_ap_done,
        ap_idle => grp_topk_sum_hist_Pipeline_BUILD_HIST_fu_78_ap_idle,
        ap_ready => grp_topk_sum_hist_Pipeline_BUILD_HIST_fu_78_ap_ready,
        cw => cw,
        runs_0_address0 => grp_topk_sum_hist_Pipeline_BUILD_HIST_fu_78_runs_0_address0,
        runs_0_ce0 => grp_topk_sum_hist_Pipeline_BUILD_HIST_fu_78_runs_0_ce0,
        runs_0_q0 => runs_0_q0,
        runs_1_address0 => grp_topk_sum_hist_Pipeline_BUILD_HIST_fu_78_runs_1_address0,
        runs_1_ce0 => grp_topk_sum_hist_Pipeline_BUILD_HIST_fu_78_runs_1_ce0,
        runs_1_q0 => runs_1_q0,
        runs_2_address0 => grp_topk_sum_hist_Pipeline_BUILD_HIST_fu_78_runs_2_address0,
        runs_2_ce0 => grp_topk_sum_hist_Pipeline_BUILD_HIST_fu_78_runs_2_ce0,
        runs_2_q0 => runs_2_q0,
        runs_3_address0 => grp_topk_sum_hist_Pipeline_BUILD_HIST_fu_78_runs_3_address0,
        runs_3_ce0 => grp_topk_sum_hist_Pipeline_BUILD_HIST_fu_78_runs_3_ce0,
        runs_3_q0 => runs_3_q0,
        ch_cast => ch,
        ch => ch,
        hist_address0 => grp_topk_sum_hist_Pipeline_BUILD_HIST_fu_78_hist_address0,
        hist_ce0 => grp_topk_sum_hist_Pipeline_BUILD_HIST_fu_78_hist_ce0,
        hist_we0 => grp_topk_sum_hist_Pipeline_BUILD_HIST_fu_78_hist_we0,
        hist_d0 => grp_topk_sum_hist_Pipeline_BUILD_HIST_fu_78_hist_d0,
        hist_q0 => hist_q0,
        hist_1_address0 => grp_topk_sum_hist_Pipeline_BUILD_HIST_fu_78_hist_1_address0,
        hist_1_ce0 => grp_topk_sum_hist_Pipeline_BUILD_HIST_fu_78_hist_1_ce0,
        hist_1_we0 => grp_topk_sum_hist_Pipeline_BUILD_HIST_fu_78_hist_1_we0,
        hist_1_d0 => grp_topk_sum_hist_Pipeline_BUILD_HIST_fu_78_hist_1_d0,
        hist_1_q0 => hist_1_q0,
        hist_2_address0 => grp_topk_sum_hist_Pipeline_BUILD_HIST_fu_78_hist_2_address0,
        hist_2_ce0 => grp_topk_sum_hist_Pipeline_BUILD_HIST_fu_78_hist_2_ce0,
        hist_2_we0 => grp_topk_sum_hist_Pipeline_BUILD_HIST_fu_78_hist_2_we0,
        hist_2_d0 => grp_topk_sum_hist_Pipeline_BUILD_HIST_fu_78_hist_2_d0,
        hist_2_q0 => hist_2_q0,
        hist_3_address0 => grp_topk_sum_hist_Pipeline_BUILD_HIST_fu_78_hist_3_address0,
        hist_3_ce0 => grp_topk_sum_hist_Pipeline_BUILD_HIST_fu_78_hist_3_ce0,
        hist_3_we0 => grp_topk_sum_hist_Pipeline_BUILD_HIST_fu_78_hist_3_we0,
        hist_3_d0 => grp_topk_sum_hist_Pipeline_BUILD_HIST_fu_78_hist_3_d0,
        hist_3_q0 => hist_3_q0);

    grp_topk_sum_hist_Pipeline_ACCUM_TOPK_fu_100 : component eye_feature_topk_sum_hist_Pipeline_ACCUM_TOPK
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_topk_sum_hist_Pipeline_ACCUM_TOPK_fu_100_ap_start,
        ap_done => grp_topk_sum_hist_Pipeline_ACCUM_TOPK_fu_100_ap_done,
        ap_idle => grp_topk_sum_hist_Pipeline_ACCUM_TOPK_fu_100_ap_idle,
        ap_ready => grp_topk_sum_hist_Pipeline_ACCUM_TOPK_fu_100_ap_ready,
        k_cast => k,
        zext_ln258 => ch,
        hist_address0 => grp_topk_sum_hist_Pipeline_ACCUM_TOPK_fu_100_hist_address0,
        hist_ce0 => grp_topk_sum_hist_Pipeline_ACCUM_TOPK_fu_100_hist_ce0,
        hist_q0 => hist_q0,
        hist_1_address0 => grp_topk_sum_hist_Pipeline_ACCUM_TOPK_fu_100_hist_1_address0,
        hist_1_ce0 => grp_topk_sum_hist_Pipeline_ACCUM_TOPK_fu_100_hist_1_ce0,
        hist_1_q0 => hist_1_q0,
        hist_2_address0 => grp_topk_sum_hist_Pipeline_ACCUM_TOPK_fu_100_hist_2_address0,
        hist_2_ce0 => grp_topk_sum_hist_Pipeline_ACCUM_TOPK_fu_100_hist_2_ce0,
        hist_2_q0 => hist_2_q0,
        hist_3_address0 => grp_topk_sum_hist_Pipeline_ACCUM_TOPK_fu_100_hist_3_address0,
        hist_3_ce0 => grp_topk_sum_hist_Pipeline_ACCUM_TOPK_fu_100_hist_3_ce0,
        hist_3_q0 => hist_3_q0,
        sum_out => grp_topk_sum_hist_Pipeline_ACCUM_TOPK_fu_100_sum_out,
        sum_out_ap_vld => grp_topk_sum_hist_Pipeline_ACCUM_TOPK_fu_100_sum_out_ap_vld);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    grp_topk_sum_hist_Pipeline_ACCUM_TOPK_fu_100_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_topk_sum_hist_Pipeline_ACCUM_TOPK_fu_100_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
                    grp_topk_sum_hist_Pipeline_ACCUM_TOPK_fu_100_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_topk_sum_hist_Pipeline_ACCUM_TOPK_fu_100_ap_ready = ap_const_logic_1)) then 
                    grp_topk_sum_hist_Pipeline_ACCUM_TOPK_fu_100_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_topk_sum_hist_Pipeline_BUILD_HIST_fu_78_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_topk_sum_hist_Pipeline_BUILD_HIST_fu_78_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
                    grp_topk_sum_hist_Pipeline_BUILD_HIST_fu_78_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_topk_sum_hist_Pipeline_BUILD_HIST_fu_78_ap_ready = ap_const_logic_1)) then 
                    grp_topk_sum_hist_Pipeline_BUILD_HIST_fu_78_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_topk_sum_hist_Pipeline_INIT_HIST_fu_66_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_topk_sum_hist_Pipeline_INIT_HIST_fu_66_ap_start_reg <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                    grp_topk_sum_hist_Pipeline_INIT_HIST_fu_66_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_topk_sum_hist_Pipeline_INIT_HIST_fu_66_ap_ready = ap_const_logic_1)) then 
                    grp_topk_sum_hist_Pipeline_INIT_HIST_fu_66_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, grp_topk_sum_hist_Pipeline_INIT_HIST_fu_66_ap_done, grp_topk_sum_hist_Pipeline_BUILD_HIST_fu_78_ap_done, grp_topk_sum_hist_Pipeline_ACCUM_TOPK_fu_100_ap_done, ap_CS_fsm_state2, ap_CS_fsm_state4, ap_CS_fsm_state6)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state2) and (grp_topk_sum_hist_Pipeline_INIT_HIST_fu_66_ap_done = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state3;
                else
                    ap_NS_fsm <= ap_ST_fsm_state2;
                end if;
            when ap_ST_fsm_state3 => 
                ap_NS_fsm <= ap_ST_fsm_state4;
            when ap_ST_fsm_state4 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state4) and (grp_topk_sum_hist_Pipeline_BUILD_HIST_fu_78_ap_done = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state5;
                else
                    ap_NS_fsm <= ap_ST_fsm_state4;
                end if;
            when ap_ST_fsm_state5 => 
                ap_NS_fsm <= ap_ST_fsm_state6;
            when ap_ST_fsm_state6 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state6) and (grp_topk_sum_hist_Pipeline_ACCUM_TOPK_fu_100_ap_done = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state7;
                else
                    ap_NS_fsm <= ap_ST_fsm_state6;
                end if;
            when ap_ST_fsm_state7 => 
                ap_NS_fsm <= ap_ST_fsm_state1;
            when others =>  
                ap_NS_fsm <= "XXXXXXX";
        end case;
    end process;
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_CS_fsm_state5 <= ap_CS_fsm(4);
    ap_CS_fsm_state6 <= ap_CS_fsm(5);
    ap_CS_fsm_state7 <= ap_CS_fsm(6);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_start)
    begin
        if ((ap_start = ap_const_logic_0)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state2_blk_assign_proc : process(grp_topk_sum_hist_Pipeline_INIT_HIST_fu_66_ap_done)
    begin
        if ((grp_topk_sum_hist_Pipeline_INIT_HIST_fu_66_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state2_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state2_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state3_blk <= ap_const_logic_0;

    ap_ST_fsm_state4_blk_assign_proc : process(grp_topk_sum_hist_Pipeline_BUILD_HIST_fu_78_ap_done)
    begin
        if ((grp_topk_sum_hist_Pipeline_BUILD_HIST_fu_78_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state4_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state4_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state5_blk <= ap_const_logic_0;

    ap_ST_fsm_state6_blk_assign_proc : process(grp_topk_sum_hist_Pipeline_ACCUM_TOPK_fu_100_ap_done)
    begin
        if ((grp_topk_sum_hist_Pipeline_ACCUM_TOPK_fu_100_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state6_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state6_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state7_blk <= ap_const_logic_0;

    ap_done_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_CS_fsm_state7)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state7) or ((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_0)))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state7)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    ap_return <= grp_topk_sum_hist_Pipeline_ACCUM_TOPK_fu_100_sum_out;
    grp_topk_sum_hist_Pipeline_ACCUM_TOPK_fu_100_ap_start <= grp_topk_sum_hist_Pipeline_ACCUM_TOPK_fu_100_ap_start_reg;
    grp_topk_sum_hist_Pipeline_BUILD_HIST_fu_78_ap_start <= grp_topk_sum_hist_Pipeline_BUILD_HIST_fu_78_ap_start_reg;
    grp_topk_sum_hist_Pipeline_INIT_HIST_fu_66_ap_start <= grp_topk_sum_hist_Pipeline_INIT_HIST_fu_66_ap_start_reg;

    hist_1_address0_assign_proc : process(grp_topk_sum_hist_Pipeline_INIT_HIST_fu_66_hist_1_address0, grp_topk_sum_hist_Pipeline_BUILD_HIST_fu_78_hist_1_address0, grp_topk_sum_hist_Pipeline_ACCUM_TOPK_fu_100_hist_1_address0, ap_CS_fsm_state2, ap_CS_fsm_state4, ap_CS_fsm_state6)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            hist_1_address0 <= grp_topk_sum_hist_Pipeline_ACCUM_TOPK_fu_100_hist_1_address0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            hist_1_address0 <= grp_topk_sum_hist_Pipeline_BUILD_HIST_fu_78_hist_1_address0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            hist_1_address0 <= grp_topk_sum_hist_Pipeline_INIT_HIST_fu_66_hist_1_address0;
        else 
            hist_1_address0 <= "XXXXX";
        end if; 
    end process;


    hist_1_ce0_assign_proc : process(grp_topk_sum_hist_Pipeline_INIT_HIST_fu_66_hist_1_ce0, grp_topk_sum_hist_Pipeline_BUILD_HIST_fu_78_hist_1_ce0, grp_topk_sum_hist_Pipeline_ACCUM_TOPK_fu_100_hist_1_ce0, ap_CS_fsm_state2, ap_CS_fsm_state4, ap_CS_fsm_state6)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            hist_1_ce0 <= grp_topk_sum_hist_Pipeline_ACCUM_TOPK_fu_100_hist_1_ce0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            hist_1_ce0 <= grp_topk_sum_hist_Pipeline_BUILD_HIST_fu_78_hist_1_ce0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            hist_1_ce0 <= grp_topk_sum_hist_Pipeline_INIT_HIST_fu_66_hist_1_ce0;
        else 
            hist_1_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    hist_1_d0_assign_proc : process(grp_topk_sum_hist_Pipeline_INIT_HIST_fu_66_hist_1_d0, grp_topk_sum_hist_Pipeline_BUILD_HIST_fu_78_hist_1_d0, ap_CS_fsm_state2, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            hist_1_d0 <= grp_topk_sum_hist_Pipeline_BUILD_HIST_fu_78_hist_1_d0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            hist_1_d0 <= grp_topk_sum_hist_Pipeline_INIT_HIST_fu_66_hist_1_d0;
        else 
            hist_1_d0 <= "XXXXXXXXXXXXXXXX";
        end if; 
    end process;


    hist_1_we0_assign_proc : process(grp_topk_sum_hist_Pipeline_INIT_HIST_fu_66_hist_1_we0, grp_topk_sum_hist_Pipeline_BUILD_HIST_fu_78_hist_1_we0, ap_CS_fsm_state2, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            hist_1_we0 <= grp_topk_sum_hist_Pipeline_BUILD_HIST_fu_78_hist_1_we0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            hist_1_we0 <= grp_topk_sum_hist_Pipeline_INIT_HIST_fu_66_hist_1_we0;
        else 
            hist_1_we0 <= ap_const_logic_0;
        end if; 
    end process;


    hist_2_address0_assign_proc : process(grp_topk_sum_hist_Pipeline_INIT_HIST_fu_66_hist_2_address0, grp_topk_sum_hist_Pipeline_BUILD_HIST_fu_78_hist_2_address0, grp_topk_sum_hist_Pipeline_ACCUM_TOPK_fu_100_hist_2_address0, ap_CS_fsm_state2, ap_CS_fsm_state4, ap_CS_fsm_state6)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            hist_2_address0 <= grp_topk_sum_hist_Pipeline_ACCUM_TOPK_fu_100_hist_2_address0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            hist_2_address0 <= grp_topk_sum_hist_Pipeline_BUILD_HIST_fu_78_hist_2_address0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            hist_2_address0 <= grp_topk_sum_hist_Pipeline_INIT_HIST_fu_66_hist_2_address0;
        else 
            hist_2_address0 <= "XXXXX";
        end if; 
    end process;


    hist_2_ce0_assign_proc : process(grp_topk_sum_hist_Pipeline_INIT_HIST_fu_66_hist_2_ce0, grp_topk_sum_hist_Pipeline_BUILD_HIST_fu_78_hist_2_ce0, grp_topk_sum_hist_Pipeline_ACCUM_TOPK_fu_100_hist_2_ce0, ap_CS_fsm_state2, ap_CS_fsm_state4, ap_CS_fsm_state6)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            hist_2_ce0 <= grp_topk_sum_hist_Pipeline_ACCUM_TOPK_fu_100_hist_2_ce0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            hist_2_ce0 <= grp_topk_sum_hist_Pipeline_BUILD_HIST_fu_78_hist_2_ce0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            hist_2_ce0 <= grp_topk_sum_hist_Pipeline_INIT_HIST_fu_66_hist_2_ce0;
        else 
            hist_2_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    hist_2_d0_assign_proc : process(grp_topk_sum_hist_Pipeline_INIT_HIST_fu_66_hist_2_d0, grp_topk_sum_hist_Pipeline_BUILD_HIST_fu_78_hist_2_d0, ap_CS_fsm_state2, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            hist_2_d0 <= grp_topk_sum_hist_Pipeline_BUILD_HIST_fu_78_hist_2_d0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            hist_2_d0 <= grp_topk_sum_hist_Pipeline_INIT_HIST_fu_66_hist_2_d0;
        else 
            hist_2_d0 <= "XXXXXXXXXXXXXXXX";
        end if; 
    end process;


    hist_2_we0_assign_proc : process(grp_topk_sum_hist_Pipeline_INIT_HIST_fu_66_hist_2_we0, grp_topk_sum_hist_Pipeline_BUILD_HIST_fu_78_hist_2_we0, ap_CS_fsm_state2, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            hist_2_we0 <= grp_topk_sum_hist_Pipeline_BUILD_HIST_fu_78_hist_2_we0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            hist_2_we0 <= grp_topk_sum_hist_Pipeline_INIT_HIST_fu_66_hist_2_we0;
        else 
            hist_2_we0 <= ap_const_logic_0;
        end if; 
    end process;


    hist_3_address0_assign_proc : process(grp_topk_sum_hist_Pipeline_INIT_HIST_fu_66_hist_3_address0, grp_topk_sum_hist_Pipeline_BUILD_HIST_fu_78_hist_3_address0, grp_topk_sum_hist_Pipeline_ACCUM_TOPK_fu_100_hist_3_address0, ap_CS_fsm_state2, ap_CS_fsm_state4, ap_CS_fsm_state6)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            hist_3_address0 <= grp_topk_sum_hist_Pipeline_ACCUM_TOPK_fu_100_hist_3_address0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            hist_3_address0 <= grp_topk_sum_hist_Pipeline_BUILD_HIST_fu_78_hist_3_address0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            hist_3_address0 <= grp_topk_sum_hist_Pipeline_INIT_HIST_fu_66_hist_3_address0;
        else 
            hist_3_address0 <= "XXXXX";
        end if; 
    end process;


    hist_3_ce0_assign_proc : process(grp_topk_sum_hist_Pipeline_INIT_HIST_fu_66_hist_3_ce0, grp_topk_sum_hist_Pipeline_BUILD_HIST_fu_78_hist_3_ce0, grp_topk_sum_hist_Pipeline_ACCUM_TOPK_fu_100_hist_3_ce0, ap_CS_fsm_state2, ap_CS_fsm_state4, ap_CS_fsm_state6)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            hist_3_ce0 <= grp_topk_sum_hist_Pipeline_ACCUM_TOPK_fu_100_hist_3_ce0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            hist_3_ce0 <= grp_topk_sum_hist_Pipeline_BUILD_HIST_fu_78_hist_3_ce0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            hist_3_ce0 <= grp_topk_sum_hist_Pipeline_INIT_HIST_fu_66_hist_3_ce0;
        else 
            hist_3_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    hist_3_d0_assign_proc : process(grp_topk_sum_hist_Pipeline_INIT_HIST_fu_66_hist_3_d0, grp_topk_sum_hist_Pipeline_BUILD_HIST_fu_78_hist_3_d0, ap_CS_fsm_state2, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            hist_3_d0 <= grp_topk_sum_hist_Pipeline_BUILD_HIST_fu_78_hist_3_d0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            hist_3_d0 <= grp_topk_sum_hist_Pipeline_INIT_HIST_fu_66_hist_3_d0;
        else 
            hist_3_d0 <= "XXXXXXXXXXXXXXXX";
        end if; 
    end process;


    hist_3_we0_assign_proc : process(grp_topk_sum_hist_Pipeline_INIT_HIST_fu_66_hist_3_we0, grp_topk_sum_hist_Pipeline_BUILD_HIST_fu_78_hist_3_we0, ap_CS_fsm_state2, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            hist_3_we0 <= grp_topk_sum_hist_Pipeline_BUILD_HIST_fu_78_hist_3_we0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            hist_3_we0 <= grp_topk_sum_hist_Pipeline_INIT_HIST_fu_66_hist_3_we0;
        else 
            hist_3_we0 <= ap_const_logic_0;
        end if; 
    end process;


    hist_address0_assign_proc : process(grp_topk_sum_hist_Pipeline_INIT_HIST_fu_66_hist_address0, grp_topk_sum_hist_Pipeline_BUILD_HIST_fu_78_hist_address0, grp_topk_sum_hist_Pipeline_ACCUM_TOPK_fu_100_hist_address0, ap_CS_fsm_state2, ap_CS_fsm_state4, ap_CS_fsm_state6)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            hist_address0 <= grp_topk_sum_hist_Pipeline_ACCUM_TOPK_fu_100_hist_address0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            hist_address0 <= grp_topk_sum_hist_Pipeline_BUILD_HIST_fu_78_hist_address0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            hist_address0 <= grp_topk_sum_hist_Pipeline_INIT_HIST_fu_66_hist_address0;
        else 
            hist_address0 <= "XXXXX";
        end if; 
    end process;


    hist_ce0_assign_proc : process(grp_topk_sum_hist_Pipeline_INIT_HIST_fu_66_hist_ce0, grp_topk_sum_hist_Pipeline_BUILD_HIST_fu_78_hist_ce0, grp_topk_sum_hist_Pipeline_ACCUM_TOPK_fu_100_hist_ce0, ap_CS_fsm_state2, ap_CS_fsm_state4, ap_CS_fsm_state6)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            hist_ce0 <= grp_topk_sum_hist_Pipeline_ACCUM_TOPK_fu_100_hist_ce0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            hist_ce0 <= grp_topk_sum_hist_Pipeline_BUILD_HIST_fu_78_hist_ce0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            hist_ce0 <= grp_topk_sum_hist_Pipeline_INIT_HIST_fu_66_hist_ce0;
        else 
            hist_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    hist_d0_assign_proc : process(grp_topk_sum_hist_Pipeline_INIT_HIST_fu_66_hist_d0, grp_topk_sum_hist_Pipeline_BUILD_HIST_fu_78_hist_d0, ap_CS_fsm_state2, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            hist_d0 <= grp_topk_sum_hist_Pipeline_BUILD_HIST_fu_78_hist_d0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            hist_d0 <= grp_topk_sum_hist_Pipeline_INIT_HIST_fu_66_hist_d0;
        else 
            hist_d0 <= "XXXXXXXXXXXXXXXX";
        end if; 
    end process;


    hist_we0_assign_proc : process(grp_topk_sum_hist_Pipeline_INIT_HIST_fu_66_hist_we0, grp_topk_sum_hist_Pipeline_BUILD_HIST_fu_78_hist_we0, ap_CS_fsm_state2, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            hist_we0 <= grp_topk_sum_hist_Pipeline_BUILD_HIST_fu_78_hist_we0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            hist_we0 <= grp_topk_sum_hist_Pipeline_INIT_HIST_fu_66_hist_we0;
        else 
            hist_we0 <= ap_const_logic_0;
        end if; 
    end process;

    runs_0_address0 <= grp_topk_sum_hist_Pipeline_BUILD_HIST_fu_78_runs_0_address0;
    runs_0_ce0 <= grp_topk_sum_hist_Pipeline_BUILD_HIST_fu_78_runs_0_ce0;
    runs_1_address0 <= grp_topk_sum_hist_Pipeline_BUILD_HIST_fu_78_runs_1_address0;
    runs_1_ce0 <= grp_topk_sum_hist_Pipeline_BUILD_HIST_fu_78_runs_1_ce0;
    runs_2_address0 <= grp_topk_sum_hist_Pipeline_BUILD_HIST_fu_78_runs_2_address0;
    runs_2_ce0 <= grp_topk_sum_hist_Pipeline_BUILD_HIST_fu_78_runs_2_ce0;
    runs_3_address0 <= grp_topk_sum_hist_Pipeline_BUILD_HIST_fu_78_runs_3_address0;
    runs_3_ce0 <= grp_topk_sum_hist_Pipeline_BUILD_HIST_fu_78_runs_3_ce0;
end behav;
