// ==============================================================
// Generated by Vitis HLS v2023.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module eye_feature_compute_robust_stats_Pipeline_MAX_LOW (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        cw,
        run_low_address0,
        run_low_ce0,
        run_low_q0,
        run_low_1_address0,
        run_low_1_ce0,
        run_low_1_q0,
        run_low_2_address0,
        run_low_2_ce0,
        run_low_2_q0,
        run_low_3_address0,
        run_low_3_ce0,
        run_low_3_q0,
        max_low_out,
        max_low_out_ap_vld
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [7:0] cw;
output  [4:0] run_low_address0;
output   run_low_ce0;
input  [15:0] run_low_q0;
output  [4:0] run_low_1_address0;
output   run_low_1_ce0;
input  [15:0] run_low_1_q0;
output  [4:0] run_low_2_address0;
output   run_low_2_ce0;
input  [15:0] run_low_2_q0;
output  [4:0] run_low_3_address0;
output   run_low_3_ce0;
input  [15:0] run_low_3_q0;
output  [31:0] max_low_out;
output   max_low_out_ap_vld;

reg ap_idle;
reg run_low_ce0;
reg run_low_1_ce0;
reg run_low_2_ce0;
reg run_low_3_ce0;
reg max_low_out_ap_vld;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_idle_pp0;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln368_fu_144_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire   [1:0] trunc_ln368_1_fu_156_p1;
reg   [1:0] trunc_ln368_1_reg_279;
wire    ap_block_pp0_stage0_11001;
wire   [0:0] icmp_ln370_fu_178_p2;
reg   [0:0] icmp_ln370_reg_284;
wire   [63:0] zext_ln366_fu_170_p1;
wire    ap_block_pp0_stage0;
reg   [31:0] max_low_fu_58;
wire   [31:0] max_low_1_fu_245_p3;
wire    ap_loop_init;
reg   [7:0] x_2_fu_62;
wire   [7:0] add_ln368_fu_150_p2;
reg   [7:0] ap_sig_allocacmp_x;
wire    ap_block_pp0_stage0_01001;
wire   [4:0] lshr_ln7_fu_160_p4;
wire   [15:0] tmp_fu_196_p9;
wire   [15:0] tmp_fu_196_p11;
wire   [31:0] zext_ln370_fu_219_p1;
wire   [0:0] icmp_ln370_1_fu_227_p2;
wire   [30:0] zext_ln370_1_fu_223_p1;
wire   [30:0] trunc_ln368_fu_192_p1;
wire   [30:0] select_ln370_fu_233_p3;
wire   [31:0] zext_ln370_2_fu_241_p1;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire   [1:0] tmp_fu_196_p1;
wire   [1:0] tmp_fu_196_p3;
wire  signed [1:0] tmp_fu_196_p5;
wire  signed [1:0] tmp_fu_196_p7;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 max_low_fu_58 = 32'd0;
#0 x_2_fu_62 = 8'd0;
#0 ap_done_reg = 1'b0;
end

eye_feature_sparsemux_9_2_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 2'h0 ),
    .din0_WIDTH( 16 ),
    .CASE1( 2'h1 ),
    .din1_WIDTH( 16 ),
    .CASE2( 2'h2 ),
    .din2_WIDTH( 16 ),
    .CASE3( 2'h3 ),
    .din3_WIDTH( 16 ),
    .def_WIDTH( 16 ),
    .sel_WIDTH( 2 ),
    .dout_WIDTH( 16 ))
sparsemux_9_2_16_1_1_U116(
    .din0(run_low_q0),
    .din1(run_low_1_q0),
    .din2(run_low_2_q0),
    .din3(run_low_3_q0),
    .def(tmp_fu_196_p9),
    .sel(trunc_ln368_1_reg_279),
    .dout(tmp_fu_196_p11)
);

eye_feature_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            max_low_fu_58 <= 32'd0;
        end else if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
            max_low_fu_58 <= max_low_1_fu_245_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln368_fu_144_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            x_2_fu_62 <= add_ln368_fu_150_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            x_2_fu_62 <= 8'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        icmp_ln370_reg_284 <= icmp_ln370_fu_178_p2;
        trunc_ln368_1_reg_279 <= trunc_ln368_1_fu_156_p1;
    end
end

always @ (*) begin
    if (((icmp_ln368_fu_144_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_x = 8'd0;
    end else begin
        ap_sig_allocacmp_x = x_2_fu_62;
    end
end

always @ (*) begin
    if (((icmp_ln368_fu_144_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        max_low_out_ap_vld = 1'b1;
    end else begin
        max_low_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        run_low_1_ce0 = 1'b1;
    end else begin
        run_low_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        run_low_2_ce0 = 1'b1;
    end else begin
        run_low_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        run_low_3_ce0 = 1'b1;
    end else begin
        run_low_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        run_low_ce0 = 1'b1;
    end else begin
        run_low_ce0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln368_fu_150_p2 = (ap_sig_allocacmp_x + 8'd1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_01001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign icmp_ln368_fu_144_p2 = ((ap_sig_allocacmp_x == 8'd128) ? 1'b1 : 1'b0);

assign icmp_ln370_1_fu_227_p2 = (($signed(zext_ln370_fu_219_p1) > $signed(max_low_fu_58)) ? 1'b1 : 1'b0);

assign icmp_ln370_fu_178_p2 = ((ap_sig_allocacmp_x < cw) ? 1'b1 : 1'b0);

assign lshr_ln7_fu_160_p4 = {{ap_sig_allocacmp_x[6:2]}};

assign max_low_1_fu_245_p3 = ((icmp_ln370_reg_284[0:0] == 1'b1) ? zext_ln370_2_fu_241_p1 : max_low_fu_58);

assign max_low_out = max_low_fu_58;

assign run_low_1_address0 = zext_ln366_fu_170_p1;

assign run_low_2_address0 = zext_ln366_fu_170_p1;

assign run_low_3_address0 = zext_ln366_fu_170_p1;

assign run_low_address0 = zext_ln366_fu_170_p1;

assign select_ln370_fu_233_p3 = ((icmp_ln370_1_fu_227_p2[0:0] == 1'b1) ? zext_ln370_1_fu_223_p1 : trunc_ln368_fu_192_p1);

assign tmp_fu_196_p9 = 'bx;

assign trunc_ln368_1_fu_156_p1 = ap_sig_allocacmp_x[1:0];

assign trunc_ln368_fu_192_p1 = max_low_fu_58[30:0];

assign zext_ln366_fu_170_p1 = lshr_ln7_fu_160_p4;

assign zext_ln370_1_fu_223_p1 = tmp_fu_196_p11;

assign zext_ln370_2_fu_241_p1 = select_ln370_fu_233_p3;

assign zext_ln370_fu_219_p1 = tmp_fu_196_p11;

endmodule //eye_feature_compute_robust_stats_Pipeline_MAX_LOW
