// ==============================================================
// Generated by Vitis HLS v2023.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module eye_feature_compute_adapt_stats_Pipeline_ADAPT_COLS (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        adapt_runs_address0,
        adapt_runs_ce0,
        adapt_runs_we0,
        adapt_runs_d0,
        adapt_runs_address1,
        adapt_runs_ce1,
        adapt_runs_q1,
        adapt_runs_1_address0,
        adapt_runs_1_ce0,
        adapt_runs_1_we0,
        adapt_runs_1_d0,
        adapt_runs_1_address1,
        adapt_runs_1_ce1,
        adapt_runs_1_q1,
        adapt_runs_2_address0,
        adapt_runs_2_ce0,
        adapt_runs_2_we0,
        adapt_runs_2_d0,
        adapt_runs_2_address1,
        adapt_runs_2_ce1,
        adapt_runs_2_q1,
        adapt_runs_3_address0,
        adapt_runs_3_ce0,
        adapt_runs_3_we0,
        adapt_runs_3_d0,
        adapt_runs_3_address1,
        adapt_runs_3_ce1,
        adapt_runs_3_q1,
        t_adapt,
        cur_address0,
        cur_ce0,
        cur_we0,
        cur_d0,
        cur_address1,
        cur_ce1,
        cur_we1,
        cur_d1,
        cur_q1,
        cur_1_address0,
        cur_1_ce0,
        cur_1_we0,
        cur_1_d0,
        cur_1_address1,
        cur_1_ce1,
        cur_1_we1,
        cur_1_d1,
        cur_1_q1,
        cur_2_address0,
        cur_2_ce0,
        cur_2_we0,
        cur_2_d0,
        cur_2_address1,
        cur_2_ce1,
        cur_2_we1,
        cur_2_d1,
        cur_2_q1,
        cur_3_address0,
        cur_3_ce0,
        cur_3_we0,
        cur_3_d0,
        cur_3_address1,
        cur_3_ce1,
        cur_3_we1,
        cur_3_d1,
        cur_3_q1,
        zext_ln246,
        pix_buf_address0,
        pix_buf_ce0,
        pix_buf_q0,
        cw
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [4:0] adapt_runs_address0;
output   adapt_runs_ce0;
output   adapt_runs_we0;
output  [15:0] adapt_runs_d0;
output  [4:0] adapt_runs_address1;
output   adapt_runs_ce1;
input  [15:0] adapt_runs_q1;
output  [4:0] adapt_runs_1_address0;
output   adapt_runs_1_ce0;
output   adapt_runs_1_we0;
output  [15:0] adapt_runs_1_d0;
output  [4:0] adapt_runs_1_address1;
output   adapt_runs_1_ce1;
input  [15:0] adapt_runs_1_q1;
output  [4:0] adapt_runs_2_address0;
output   adapt_runs_2_ce0;
output   adapt_runs_2_we0;
output  [15:0] adapt_runs_2_d0;
output  [4:0] adapt_runs_2_address1;
output   adapt_runs_2_ce1;
input  [15:0] adapt_runs_2_q1;
output  [4:0] adapt_runs_3_address0;
output   adapt_runs_3_ce0;
output   adapt_runs_3_we0;
output  [15:0] adapt_runs_3_d0;
output  [4:0] adapt_runs_3_address1;
output   adapt_runs_3_ce1;
input  [15:0] adapt_runs_3_q1;
input  [7:0] t_adapt;
output  [4:0] cur_address0;
output   cur_ce0;
output   cur_we0;
output  [15:0] cur_d0;
output  [4:0] cur_address1;
output   cur_ce1;
output   cur_we1;
output  [15:0] cur_d1;
input  [15:0] cur_q1;
output  [4:0] cur_1_address0;
output   cur_1_ce0;
output   cur_1_we0;
output  [15:0] cur_1_d0;
output  [4:0] cur_1_address1;
output   cur_1_ce1;
output   cur_1_we1;
output  [15:0] cur_1_d1;
input  [15:0] cur_1_q1;
output  [4:0] cur_2_address0;
output   cur_2_ce0;
output   cur_2_we0;
output  [15:0] cur_2_d0;
output  [4:0] cur_2_address1;
output   cur_2_ce1;
output   cur_2_we1;
output  [15:0] cur_2_d1;
input  [15:0] cur_2_q1;
output  [4:0] cur_3_address0;
output   cur_3_ce0;
output   cur_3_we0;
output  [15:0] cur_3_d0;
output  [4:0] cur_3_address1;
output   cur_3_ce1;
output   cur_3_we1;
output  [15:0] cur_3_d1;
input  [15:0] cur_3_q1;
input  [12:0] zext_ln246;
output  [12:0] pix_buf_address0;
output   pix_buf_ce0;
input  [7:0] pix_buf_q0;
input  [7:0] cw;

reg ap_idle;
reg adapt_runs_ce0;
reg adapt_runs_we0;
reg adapt_runs_ce1;
reg adapt_runs_1_ce0;
reg adapt_runs_1_we0;
reg adapt_runs_1_ce1;
reg adapt_runs_2_ce0;
reg adapt_runs_2_we0;
reg adapt_runs_2_ce1;
reg adapt_runs_3_ce0;
reg adapt_runs_3_we0;
reg adapt_runs_3_ce1;
reg cur_ce0;
reg cur_we0;
reg cur_ce1;
reg cur_we1;
reg cur_1_ce0;
reg cur_1_we0;
reg cur_1_ce1;
reg cur_1_we1;
reg cur_2_ce0;
reg cur_2_we0;
reg cur_2_ce1;
reg cur_2_we1;
reg cur_3_ce0;
reg cur_3_we0;
reg cur_3_ce1;
reg cur_3_we1;
reg pix_buf_ce0;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_idle_pp0;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln245_fu_308_p2;
wire   [0:0] icmp_ln243_fu_267_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire    ap_block_pp0_stage0_11001;
reg   [0:0] icmp_ln243_reg_413;
wire   [1:0] trunc_ln243_fu_294_p1;
reg   [1:0] trunc_ln243_reg_422;
reg   [1:0] trunc_ln243_reg_422_pp0_iter1_reg;
reg   [4:0] lshr_ln_reg_428;
reg   [0:0] icmp_ln245_reg_433;
wire   [0:0] dark_fu_330_p2;
reg   [0:0] dark_reg_437;
reg   [4:0] cur_addr_reg_441;
reg   [4:0] cur_1_addr_reg_447;
reg   [4:0] cur_2_addr_reg_453;
reg   [4:0] cur_3_addr_reg_459;
reg   [4:0] adapt_runs_addr_reg_465;
reg   [4:0] adapt_runs_1_addr_reg_471;
reg   [4:0] adapt_runs_2_addr_reg_477;
reg   [4:0] adapt_runs_3_addr_reg_483;
reg    ap_condition_exit_pp0_iter1_stage0;
wire   [63:0] zext_ln246_2_fu_289_p1;
wire    ap_block_pp0_stage0;
wire   [63:0] zext_ln243_fu_319_p1;
reg   [7:0] x_2_fu_84;
wire   [7:0] add_ln243_fu_273_p2;
wire    ap_loop_init;
reg   [7:0] ap_sig_allocacmp_x;
wire   [15:0] add_ln248_fu_358_p2;
wire   [0:0] icmp_ln249_fu_395_p2;
wire   [12:0] zext_ln246_1_fu_279_p1;
wire   [12:0] add_ln246_fu_283_p2;
wire   [15:0] tmp_7_fu_335_p9;
wire   [15:0] tmp_7_fu_335_p11;
wire   [15:0] tmp_8_fu_372_p9;
wire   [15:0] tmp_8_fu_372_p11;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
reg    ap_condition_396;
wire   [1:0] tmp_7_fu_335_p1;
wire   [1:0] tmp_7_fu_335_p3;
wire  signed [1:0] tmp_7_fu_335_p5;
wire  signed [1:0] tmp_7_fu_335_p7;
wire   [1:0] tmp_8_fu_372_p1;
wire   [1:0] tmp_8_fu_372_p3;
wire  signed [1:0] tmp_8_fu_372_p5;
wire  signed [1:0] tmp_8_fu_372_p7;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 x_2_fu_84 = 8'd0;
#0 ap_done_reg = 1'b0;
end

eye_feature_sparsemux_9_2_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 2'h0 ),
    .din0_WIDTH( 16 ),
    .CASE1( 2'h1 ),
    .din1_WIDTH( 16 ),
    .CASE2( 2'h2 ),
    .din2_WIDTH( 16 ),
    .CASE3( 2'h3 ),
    .din3_WIDTH( 16 ),
    .def_WIDTH( 16 ),
    .sel_WIDTH( 2 ),
    .dout_WIDTH( 16 ))
sparsemux_9_2_16_1_1_U80(
    .din0(cur_q1),
    .din1(cur_1_q1),
    .din2(cur_2_q1),
    .din3(cur_3_q1),
    .def(tmp_7_fu_335_p9),
    .sel(trunc_ln243_reg_422_pp0_iter1_reg),
    .dout(tmp_7_fu_335_p11)
);

eye_feature_sparsemux_9_2_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 2'h0 ),
    .din0_WIDTH( 16 ),
    .CASE1( 2'h1 ),
    .din1_WIDTH( 16 ),
    .CASE2( 2'h2 ),
    .din2_WIDTH( 16 ),
    .CASE3( 2'h3 ),
    .din3_WIDTH( 16 ),
    .def_WIDTH( 16 ),
    .sel_WIDTH( 2 ),
    .dout_WIDTH( 16 ))
sparsemux_9_2_16_1_1_U81(
    .din0(adapt_runs_q1),
    .din1(adapt_runs_1_q1),
    .din2(adapt_runs_2_q1),
    .din3(adapt_runs_3_q1),
    .def(tmp_8_fu_372_p9),
    .sel(trunc_ln243_reg_422_pp0_iter1_reg),
    .dout(tmp_8_fu_372_p11)
);

eye_feature_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter1_stage0)) begin
            ap_enable_reg_pp0_iter2 <= 1'b0;
        end else if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((1'b1 == ap_condition_396)) begin
            x_2_fu_84 <= add_ln243_fu_273_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            x_2_fu_84 <= 8'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        adapt_runs_1_addr_reg_471 <= zext_ln243_fu_319_p1;
        adapt_runs_2_addr_reg_477 <= zext_ln243_fu_319_p1;
        adapt_runs_3_addr_reg_483 <= zext_ln243_fu_319_p1;
        adapt_runs_addr_reg_465 <= zext_ln243_fu_319_p1;
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        cur_1_addr_reg_447 <= zext_ln243_fu_319_p1;
        cur_2_addr_reg_453 <= zext_ln243_fu_319_p1;
        cur_3_addr_reg_459 <= zext_ln243_fu_319_p1;
        cur_addr_reg_441 <= zext_ln243_fu_319_p1;
        dark_reg_437 <= dark_fu_330_p2;
        icmp_ln243_reg_413 <= icmp_ln243_fu_267_p2;
        icmp_ln245_reg_433 <= icmp_ln245_fu_308_p2;
        lshr_ln_reg_428 <= {{ap_sig_allocacmp_x[6:2]}};
        trunc_ln243_reg_422 <= trunc_ln243_fu_294_p1;
        trunc_ln243_reg_422_pp0_iter1_reg <= trunc_ln243_reg_422;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        adapt_runs_1_ce0 = 1'b1;
    end else begin
        adapt_runs_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        adapt_runs_1_ce1 = 1'b1;
    end else begin
        adapt_runs_1_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln249_fu_395_p2 == 1'd1) & (ap_enable_reg_pp0_iter2 == 1'b1) & (dark_reg_437 == 1'd1) & (trunc_ln243_reg_422_pp0_iter1_reg == 2'd1))) begin
        adapt_runs_1_we0 = 1'b1;
    end else begin
        adapt_runs_1_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        adapt_runs_2_ce0 = 1'b1;
    end else begin
        adapt_runs_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        adapt_runs_2_ce1 = 1'b1;
    end else begin
        adapt_runs_2_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln249_fu_395_p2 == 1'd1) & (ap_enable_reg_pp0_iter2 == 1'b1) & (dark_reg_437 == 1'd1) & (trunc_ln243_reg_422_pp0_iter1_reg == 2'd2))) begin
        adapt_runs_2_we0 = 1'b1;
    end else begin
        adapt_runs_2_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        adapt_runs_3_ce0 = 1'b1;
    end else begin
        adapt_runs_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        adapt_runs_3_ce1 = 1'b1;
    end else begin
        adapt_runs_3_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln249_fu_395_p2 == 1'd1) & (ap_enable_reg_pp0_iter2 == 1'b1) & (dark_reg_437 == 1'd1) & (trunc_ln243_reg_422_pp0_iter1_reg == 2'd3))) begin
        adapt_runs_3_we0 = 1'b1;
    end else begin
        adapt_runs_3_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        adapt_runs_ce0 = 1'b1;
    end else begin
        adapt_runs_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        adapt_runs_ce1 = 1'b1;
    end else begin
        adapt_runs_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln249_fu_395_p2 == 1'd1) & (ap_enable_reg_pp0_iter2 == 1'b1) & (dark_reg_437 == 1'd1) & (trunc_ln243_reg_422_pp0_iter1_reg == 2'd0))) begin
        adapt_runs_we0 = 1'b1;
    end else begin
        adapt_runs_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & ((icmp_ln243_fu_267_p2 == 1'd1) | (icmp_ln245_fu_308_p2 == 1'd0)))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & ((icmp_ln245_reg_433 == 1'd0) | (icmp_ln243_reg_413 == 1'd1)))) begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_x = 8'd0;
    end else begin
        ap_sig_allocacmp_x = x_2_fu_84;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        cur_1_ce0 = 1'b1;
    end else begin
        cur_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (dark_fu_330_p2 == 1'd0) & (icmp_ln245_reg_433 == 1'd1) & (trunc_ln243_reg_422 == 2'd1) & (icmp_ln243_reg_413 == 1'd0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (dark_fu_330_p2 == 1'd1) & (icmp_ln245_reg_433 == 1'd1) & (trunc_ln243_reg_422 == 2'd1) & (icmp_ln243_reg_413 == 1'd0)))) begin
        cur_1_ce1 = 1'b1;
    end else begin
        cur_1_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (dark_reg_437 == 1'd1) & (trunc_ln243_reg_422_pp0_iter1_reg == 2'd1))) begin
        cur_1_we0 = 1'b1;
    end else begin
        cur_1_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (dark_fu_330_p2 == 1'd0) & (icmp_ln245_reg_433 == 1'd1) & (trunc_ln243_reg_422 == 2'd1) & (icmp_ln243_reg_413 == 1'd0))) begin
        cur_1_we1 = 1'b1;
    end else begin
        cur_1_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        cur_2_ce0 = 1'b1;
    end else begin
        cur_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (dark_fu_330_p2 == 1'd0) & (icmp_ln245_reg_433 == 1'd1) & (trunc_ln243_reg_422 == 2'd2) & (icmp_ln243_reg_413 == 1'd0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (dark_fu_330_p2 == 1'd1) & (icmp_ln245_reg_433 == 1'd1) & (trunc_ln243_reg_422 == 2'd2) & (icmp_ln243_reg_413 == 1'd0)))) begin
        cur_2_ce1 = 1'b1;
    end else begin
        cur_2_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (dark_reg_437 == 1'd1) & (trunc_ln243_reg_422_pp0_iter1_reg == 2'd2))) begin
        cur_2_we0 = 1'b1;
    end else begin
        cur_2_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (dark_fu_330_p2 == 1'd0) & (icmp_ln245_reg_433 == 1'd1) & (trunc_ln243_reg_422 == 2'd2) & (icmp_ln243_reg_413 == 1'd0))) begin
        cur_2_we1 = 1'b1;
    end else begin
        cur_2_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        cur_3_ce0 = 1'b1;
    end else begin
        cur_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (dark_fu_330_p2 == 1'd0) & (icmp_ln245_reg_433 == 1'd1) & (trunc_ln243_reg_422 == 2'd3) & (icmp_ln243_reg_413 == 1'd0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (dark_fu_330_p2 == 1'd1) & (icmp_ln245_reg_433 == 1'd1) & (trunc_ln243_reg_422 == 2'd3) & (icmp_ln243_reg_413 == 1'd0)))) begin
        cur_3_ce1 = 1'b1;
    end else begin
        cur_3_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (dark_reg_437 == 1'd1) & (trunc_ln243_reg_422_pp0_iter1_reg == 2'd3))) begin
        cur_3_we0 = 1'b1;
    end else begin
        cur_3_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (dark_fu_330_p2 == 1'd0) & (icmp_ln245_reg_433 == 1'd1) & (trunc_ln243_reg_422 == 2'd3) & (icmp_ln243_reg_413 == 1'd0))) begin
        cur_3_we1 = 1'b1;
    end else begin
        cur_3_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        cur_ce0 = 1'b1;
    end else begin
        cur_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (dark_fu_330_p2 == 1'd0) & (icmp_ln245_reg_433 == 1'd1) & (trunc_ln243_reg_422 == 2'd0) & (icmp_ln243_reg_413 == 1'd0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (dark_fu_330_p2 == 1'd1) & (icmp_ln245_reg_433 == 1'd1) & (trunc_ln243_reg_422 == 2'd0) & (icmp_ln243_reg_413 == 1'd0)))) begin
        cur_ce1 = 1'b1;
    end else begin
        cur_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (dark_reg_437 == 1'd1) & (trunc_ln243_reg_422_pp0_iter1_reg == 2'd0))) begin
        cur_we0 = 1'b1;
    end else begin
        cur_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (dark_fu_330_p2 == 1'd0) & (icmp_ln245_reg_433 == 1'd1) & (trunc_ln243_reg_422 == 2'd0) & (icmp_ln243_reg_413 == 1'd0))) begin
        cur_we1 = 1'b1;
    end else begin
        cur_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        pix_buf_ce0 = 1'b1;
    end else begin
        pix_buf_ce0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign adapt_runs_1_address0 = adapt_runs_1_addr_reg_471;

assign adapt_runs_1_address1 = zext_ln243_fu_319_p1;

assign adapt_runs_1_d0 = add_ln248_fu_358_p2;

assign adapt_runs_2_address0 = adapt_runs_2_addr_reg_477;

assign adapt_runs_2_address1 = zext_ln243_fu_319_p1;

assign adapt_runs_2_d0 = add_ln248_fu_358_p2;

assign adapt_runs_3_address0 = adapt_runs_3_addr_reg_483;

assign adapt_runs_3_address1 = zext_ln243_fu_319_p1;

assign adapt_runs_3_d0 = add_ln248_fu_358_p2;

assign adapt_runs_address0 = adapt_runs_addr_reg_465;

assign adapt_runs_address1 = zext_ln243_fu_319_p1;

assign adapt_runs_d0 = add_ln248_fu_358_p2;

assign add_ln243_fu_273_p2 = (ap_sig_allocacmp_x + 8'd1);

assign add_ln246_fu_283_p2 = (zext_ln246 + zext_ln246_1_fu_279_p1);

assign add_ln248_fu_358_p2 = (tmp_7_fu_335_p11 + 16'd1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_condition_396 = ((icmp_ln243_fu_267_p2 == 1'd0) & (icmp_ln245_fu_308_p2 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign cur_1_address0 = cur_1_addr_reg_447;

assign cur_1_address1 = zext_ln243_fu_319_p1;

assign cur_1_d0 = add_ln248_fu_358_p2;

assign cur_1_d1 = 16'd0;

assign cur_2_address0 = cur_2_addr_reg_453;

assign cur_2_address1 = zext_ln243_fu_319_p1;

assign cur_2_d0 = add_ln248_fu_358_p2;

assign cur_2_d1 = 16'd0;

assign cur_3_address0 = cur_3_addr_reg_459;

assign cur_3_address1 = zext_ln243_fu_319_p1;

assign cur_3_d0 = add_ln248_fu_358_p2;

assign cur_3_d1 = 16'd0;

assign cur_address0 = cur_addr_reg_441;

assign cur_address1 = zext_ln243_fu_319_p1;

assign cur_d0 = add_ln248_fu_358_p2;

assign cur_d1 = 16'd0;

assign dark_fu_330_p2 = ((pix_buf_q0 < t_adapt) ? 1'b1 : 1'b0);

assign icmp_ln243_fu_267_p2 = ((ap_sig_allocacmp_x == 8'd128) ? 1'b1 : 1'b0);

assign icmp_ln245_fu_308_p2 = ((ap_sig_allocacmp_x < cw) ? 1'b1 : 1'b0);

assign icmp_ln249_fu_395_p2 = ((add_ln248_fu_358_p2 > tmp_8_fu_372_p11) ? 1'b1 : 1'b0);

assign pix_buf_address0 = zext_ln246_2_fu_289_p1;

assign tmp_7_fu_335_p9 = 'bx;

assign tmp_8_fu_372_p9 = 'bx;

assign trunc_ln243_fu_294_p1 = ap_sig_allocacmp_x[1:0];

assign zext_ln243_fu_319_p1 = lshr_ln_reg_428;

assign zext_ln246_1_fu_279_p1 = ap_sig_allocacmp_x;

assign zext_ln246_2_fu_289_p1 = add_ln246_fu_283_p2;

endmodule //eye_feature_compute_adapt_stats_Pipeline_ADAPT_COLS
