// ==============================================================
// Generated by Vitis HLS v2023.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module eye_feature_compute_adapt_stats_Pipeline_INIT_ADAPT (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        cur_3_address0,
        cur_3_ce0,
        cur_3_we0,
        cur_3_d0,
        cur_2_address0,
        cur_2_ce0,
        cur_2_we0,
        cur_2_d0,
        cur_1_address0,
        cur_1_ce0,
        cur_1_we0,
        cur_1_d0,
        cur_address0,
        cur_ce0,
        cur_we0,
        cur_d0,
        adapt_runs_3_address0,
        adapt_runs_3_ce0,
        adapt_runs_3_we0,
        adapt_runs_3_d0,
        adapt_runs_2_address0,
        adapt_runs_2_ce0,
        adapt_runs_2_we0,
        adapt_runs_2_d0,
        adapt_runs_1_address0,
        adapt_runs_1_ce0,
        adapt_runs_1_we0,
        adapt_runs_1_d0,
        adapt_runs_address0,
        adapt_runs_ce0,
        adapt_runs_we0,
        adapt_runs_d0
);

parameter    ap_ST_fsm_state1 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [4:0] cur_3_address0;
output   cur_3_ce0;
output   cur_3_we0;
output  [15:0] cur_3_d0;
output  [4:0] cur_2_address0;
output   cur_2_ce0;
output   cur_2_we0;
output  [15:0] cur_2_d0;
output  [4:0] cur_1_address0;
output   cur_1_ce0;
output   cur_1_we0;
output  [15:0] cur_1_d0;
output  [4:0] cur_address0;
output   cur_ce0;
output   cur_we0;
output  [15:0] cur_d0;
output  [4:0] adapt_runs_3_address0;
output   adapt_runs_3_ce0;
output   adapt_runs_3_we0;
output  [15:0] adapt_runs_3_d0;
output  [4:0] adapt_runs_2_address0;
output   adapt_runs_2_ce0;
output   adapt_runs_2_we0;
output  [15:0] adapt_runs_2_d0;
output  [4:0] adapt_runs_1_address0;
output   adapt_runs_1_ce0;
output   adapt_runs_1_we0;
output  [15:0] adapt_runs_1_d0;
output  [4:0] adapt_runs_address0;
output   adapt_runs_ce0;
output   adapt_runs_we0;
output  [15:0] adapt_runs_d0;

reg ap_idle;
reg cur_3_ce0;
reg cur_3_we0;
reg cur_2_ce0;
reg cur_2_we0;
reg cur_1_ce0;
reg cur_1_we0;
reg cur_ce0;
reg cur_we0;
reg adapt_runs_3_ce0;
reg adapt_runs_3_we0;
reg adapt_runs_2_ce0;
reg adapt_runs_2_we0;
reg adapt_runs_1_ce0;
reg adapt_runs_1_we0;
reg adapt_runs_ce0;
reg adapt_runs_we0;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    ap_block_state1_pp0_stage0_iter0;
wire   [0:0] icmp_ln233_fu_178_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire   [63:0] zext_ln233_fu_204_p1;
reg   [7:0] x_1_fu_54;
wire   [7:0] add_ln233_fu_184_p2;
wire    ap_loop_init;
reg   [7:0] ap_sig_allocacmp_x;
wire   [1:0] trunc_ln233_fu_190_p1;
wire   [4:0] lshr_ln9_fu_194_p4;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_start_int;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 x_1_fu_54 = 8'd0;
#0 ap_done_reg = 1'b0;
end

eye_feature_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        if ((icmp_ln233_fu_178_p2 == 1'd0)) begin
            x_1_fu_54 <= add_ln233_fu_184_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            x_1_fu_54 <= 8'd0;
        end
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        adapt_runs_1_ce0 = 1'b1;
    end else begin
        adapt_runs_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln233_fu_178_p2 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1) & (trunc_ln233_fu_190_p1 == 2'd1))) begin
        adapt_runs_1_we0 = 1'b1;
    end else begin
        adapt_runs_1_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        adapt_runs_2_ce0 = 1'b1;
    end else begin
        adapt_runs_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln233_fu_178_p2 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1) & (trunc_ln233_fu_190_p1 == 2'd2))) begin
        adapt_runs_2_we0 = 1'b1;
    end else begin
        adapt_runs_2_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        adapt_runs_3_ce0 = 1'b1;
    end else begin
        adapt_runs_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln233_fu_178_p2 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1) & (trunc_ln233_fu_190_p1 == 2'd3))) begin
        adapt_runs_3_we0 = 1'b1;
    end else begin
        adapt_runs_3_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        adapt_runs_ce0 = 1'b1;
    end else begin
        adapt_runs_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln233_fu_178_p2 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1) & (trunc_ln233_fu_190_p1 == 2'd0))) begin
        adapt_runs_we0 = 1'b1;
    end else begin
        adapt_runs_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state1_pp0_stage0_iter0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln233_fu_178_p2 == 1'd1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_x = 8'd0;
    end else begin
        ap_sig_allocacmp_x = x_1_fu_54;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        cur_1_ce0 = 1'b1;
    end else begin
        cur_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln233_fu_178_p2 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1) & (trunc_ln233_fu_190_p1 == 2'd1))) begin
        cur_1_we0 = 1'b1;
    end else begin
        cur_1_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        cur_2_ce0 = 1'b1;
    end else begin
        cur_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln233_fu_178_p2 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1) & (trunc_ln233_fu_190_p1 == 2'd2))) begin
        cur_2_we0 = 1'b1;
    end else begin
        cur_2_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        cur_3_ce0 = 1'b1;
    end else begin
        cur_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln233_fu_178_p2 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1) & (trunc_ln233_fu_190_p1 == 2'd3))) begin
        cur_3_we0 = 1'b1;
    end else begin
        cur_3_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        cur_ce0 = 1'b1;
    end else begin
        cur_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln233_fu_178_p2 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1) & (trunc_ln233_fu_190_p1 == 2'd0))) begin
        cur_we0 = 1'b1;
    end else begin
        cur_we0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign adapt_runs_1_address0 = zext_ln233_fu_204_p1;

assign adapt_runs_1_d0 = 16'd0;

assign adapt_runs_2_address0 = zext_ln233_fu_204_p1;

assign adapt_runs_2_d0 = 16'd0;

assign adapt_runs_3_address0 = zext_ln233_fu_204_p1;

assign adapt_runs_3_d0 = 16'd0;

assign adapt_runs_address0 = zext_ln233_fu_204_p1;

assign adapt_runs_d0 = 16'd0;

assign add_ln233_fu_184_p2 = (ap_sig_allocacmp_x + 8'd1);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = (ap_start_int == 1'b0);
end

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign cur_1_address0 = zext_ln233_fu_204_p1;

assign cur_1_d0 = 16'd0;

assign cur_2_address0 = zext_ln233_fu_204_p1;

assign cur_2_d0 = 16'd0;

assign cur_3_address0 = zext_ln233_fu_204_p1;

assign cur_3_d0 = 16'd0;

assign cur_address0 = zext_ln233_fu_204_p1;

assign cur_d0 = 16'd0;

assign icmp_ln233_fu_178_p2 = ((ap_sig_allocacmp_x == 8'd128) ? 1'b1 : 1'b0);

assign lshr_ln9_fu_194_p4 = {{ap_sig_allocacmp_x[6:2]}};

assign trunc_ln233_fu_190_p1 = ap_sig_allocacmp_x[1:0];

assign zext_ln233_fu_204_p1 = lshr_ln9_fu_194_p4;

endmodule //eye_feature_compute_adapt_stats_Pipeline_INIT_ADAPT
