// ==============================================================
// Generated by Vitis HLS v2023.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module eye_feature_compute_adapt_stats (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        valid,
        cw,
        ch,
        sum_center_val,
        pix_buf_address0,
        pix_buf_ce0,
        pix_buf_q0,
        fixed_runs_0_address0,
        fixed_runs_0_ce0,
        fixed_runs_0_q0,
        fixed_runs_1_address0,
        fixed_runs_1_ce0,
        fixed_runs_1_q0,
        fixed_runs_2_address0,
        fixed_runs_2_ce0,
        fixed_runs_2_q0,
        fixed_runs_3_address0,
        fixed_runs_3_ce0,
        fixed_runs_3_q0,
        adapt_offset,
        ap_return_0,
        ap_return_1,
        ap_return_2,
        ap_return_3,
        ap_return_4,
        ap_return_5
);

parameter    ap_ST_fsm_state1 = 42'd1;
parameter    ap_ST_fsm_state2 = 42'd2;
parameter    ap_ST_fsm_state3 = 42'd4;
parameter    ap_ST_fsm_state4 = 42'd8;
parameter    ap_ST_fsm_state5 = 42'd16;
parameter    ap_ST_fsm_state6 = 42'd32;
parameter    ap_ST_fsm_state7 = 42'd64;
parameter    ap_ST_fsm_state8 = 42'd128;
parameter    ap_ST_fsm_state9 = 42'd256;
parameter    ap_ST_fsm_state10 = 42'd512;
parameter    ap_ST_fsm_state11 = 42'd1024;
parameter    ap_ST_fsm_state12 = 42'd2048;
parameter    ap_ST_fsm_state13 = 42'd4096;
parameter    ap_ST_fsm_state14 = 42'd8192;
parameter    ap_ST_fsm_state15 = 42'd16384;
parameter    ap_ST_fsm_state16 = 42'd32768;
parameter    ap_ST_fsm_state17 = 42'd65536;
parameter    ap_ST_fsm_state18 = 42'd131072;
parameter    ap_ST_fsm_state19 = 42'd262144;
parameter    ap_ST_fsm_state20 = 42'd524288;
parameter    ap_ST_fsm_state21 = 42'd1048576;
parameter    ap_ST_fsm_state22 = 42'd2097152;
parameter    ap_ST_fsm_state23 = 42'd4194304;
parameter    ap_ST_fsm_state24 = 42'd8388608;
parameter    ap_ST_fsm_state25 = 42'd16777216;
parameter    ap_ST_fsm_state26 = 42'd33554432;
parameter    ap_ST_fsm_state27 = 42'd67108864;
parameter    ap_ST_fsm_state28 = 42'd134217728;
parameter    ap_ST_fsm_state29 = 42'd268435456;
parameter    ap_ST_fsm_state30 = 42'd536870912;
parameter    ap_ST_fsm_state31 = 42'd1073741824;
parameter    ap_ST_fsm_state32 = 42'd2147483648;
parameter    ap_ST_fsm_state33 = 42'd4294967296;
parameter    ap_ST_fsm_state34 = 42'd8589934592;
parameter    ap_ST_fsm_state35 = 42'd17179869184;
parameter    ap_ST_fsm_state36 = 42'd34359738368;
parameter    ap_ST_fsm_state37 = 42'd68719476736;
parameter    ap_ST_fsm_state38 = 42'd137438953472;
parameter    ap_ST_fsm_state39 = 42'd274877906944;
parameter    ap_ST_fsm_state40 = 42'd549755813888;
parameter    ap_ST_fsm_state41 = 42'd1099511627776;
parameter    ap_ST_fsm_state42 = 42'd2199023255552;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [0:0] valid;
input  [7:0] cw;
input  [6:0] ch;
input  [31:0] sum_center_val;
output  [12:0] pix_buf_address0;
output   pix_buf_ce0;
input  [7:0] pix_buf_q0;
output  [4:0] fixed_runs_0_address0;
output   fixed_runs_0_ce0;
input  [15:0] fixed_runs_0_q0;
output  [4:0] fixed_runs_1_address0;
output   fixed_runs_1_ce0;
input  [15:0] fixed_runs_1_q0;
output  [4:0] fixed_runs_2_address0;
output   fixed_runs_2_ce0;
input  [15:0] fixed_runs_2_q0;
output  [4:0] fixed_runs_3_address0;
output   fixed_runs_3_ce0;
input  [15:0] fixed_runs_3_q0;
input  [7:0] adapt_offset;
output  [0:0] ap_return_0;
output  [31:0] ap_return_1;
output  [31:0] ap_return_2;
output  [31:0] ap_return_3;
output  [31:0] ap_return_4;
output  [31:0] ap_return_5;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg[0:0] ap_return_0;
reg[31:0] ap_return_1;
reg[31:0] ap_return_2;
reg[31:0] ap_return_3;
reg[31:0] ap_return_4;
reg[31:0] ap_return_5;

(* fsm_encoding = "none" *) reg   [41:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [31:0] adapt_offset_cast_fu_303_p1;
reg   [31:0] adapt_offset_cast_reg_616;
wire   [31:0] ch_cast10_fu_307_p1;
reg   [31:0] ch_cast10_reg_621;
wire   [0:0] or_ln214_3_fu_367_p2;
reg   [0:0] or_ln214_3_reg_626;
wire   [14:0] count_fu_373_p2;
reg   [14:0] count_reg_630;
wire    ap_CS_fsm_state3;
wire   [0:0] icmp_ln82_fu_385_p2;
reg   [0:0] icmp_ln82_reg_645;
wire   [31:0] grp_fu_408_p2;
wire    ap_CS_fsm_state38;
wire   [7:0] t_adapt_fu_472_p3;
reg   [7:0] t_adapt_reg_666;
wire    ap_CS_fsm_state39;
wire   [12:0] tmp_s_fu_499_p3;
reg   [12:0] tmp_s_reg_675;
wire    ap_CS_fsm_state40;
wire   [5:0] k_1_fu_539_p3;
reg   [5:0] k_1_reg_683;
reg   [4:0] adapt_runs_address0;
reg    adapt_runs_ce0;
reg    adapt_runs_we0;
reg   [15:0] adapt_runs_d0;
wire   [15:0] adapt_runs_q0;
reg    adapt_runs_ce1;
wire   [15:0] adapt_runs_q1;
reg   [4:0] adapt_runs_1_address0;
reg    adapt_runs_1_ce0;
reg    adapt_runs_1_we0;
reg   [15:0] adapt_runs_1_d0;
wire   [15:0] adapt_runs_1_q0;
reg    adapt_runs_1_ce1;
wire   [15:0] adapt_runs_1_q1;
reg   [4:0] adapt_runs_2_address0;
reg    adapt_runs_2_ce0;
reg    adapt_runs_2_we0;
reg   [15:0] adapt_runs_2_d0;
wire   [15:0] adapt_runs_2_q0;
reg    adapt_runs_2_ce1;
wire   [15:0] adapt_runs_2_q1;
reg   [4:0] adapt_runs_3_address0;
reg    adapt_runs_3_ce0;
reg    adapt_runs_3_we0;
reg   [15:0] adapt_runs_3_d0;
wire   [15:0] adapt_runs_3_q0;
reg    adapt_runs_3_ce1;
wire   [15:0] adapt_runs_3_q1;
reg   [4:0] cur_address0;
reg    cur_ce0;
reg    cur_we0;
reg   [15:0] cur_d0;
reg    cur_ce1;
reg    cur_we1;
wire   [15:0] cur_q1;
reg   [4:0] cur_1_address0;
reg    cur_1_ce0;
reg    cur_1_we0;
reg   [15:0] cur_1_d0;
reg    cur_1_ce1;
reg    cur_1_we1;
wire   [15:0] cur_1_q1;
reg   [4:0] cur_2_address0;
reg    cur_2_ce0;
reg    cur_2_we0;
reg   [15:0] cur_2_d0;
reg    cur_2_ce1;
reg    cur_2_we1;
wire   [15:0] cur_2_q1;
reg   [4:0] cur_3_address0;
reg    cur_3_ce0;
reg    cur_3_we0;
reg   [15:0] cur_3_d0;
reg    cur_3_ce1;
reg    cur_3_we1;
wire   [15:0] cur_3_q1;
wire    grp_compute_adapt_stats_Pipeline_FIXED_MAX_LOOP_fu_247_ap_start;
wire    grp_compute_adapt_stats_Pipeline_FIXED_MAX_LOOP_fu_247_ap_done;
wire    grp_compute_adapt_stats_Pipeline_FIXED_MAX_LOOP_fu_247_ap_idle;
wire    grp_compute_adapt_stats_Pipeline_FIXED_MAX_LOOP_fu_247_ap_ready;
wire   [4:0] grp_compute_adapt_stats_Pipeline_FIXED_MAX_LOOP_fu_247_fixed_runs_0_address0;
wire    grp_compute_adapt_stats_Pipeline_FIXED_MAX_LOOP_fu_247_fixed_runs_0_ce0;
wire   [4:0] grp_compute_adapt_stats_Pipeline_FIXED_MAX_LOOP_fu_247_fixed_runs_1_address0;
wire    grp_compute_adapt_stats_Pipeline_FIXED_MAX_LOOP_fu_247_fixed_runs_1_ce0;
wire   [4:0] grp_compute_adapt_stats_Pipeline_FIXED_MAX_LOOP_fu_247_fixed_runs_2_address0;
wire    grp_compute_adapt_stats_Pipeline_FIXED_MAX_LOOP_fu_247_fixed_runs_2_ce0;
wire   [4:0] grp_compute_adapt_stats_Pipeline_FIXED_MAX_LOOP_fu_247_fixed_runs_3_address0;
wire    grp_compute_adapt_stats_Pipeline_FIXED_MAX_LOOP_fu_247_fixed_runs_3_ce0;
wire   [31:0] grp_compute_adapt_stats_Pipeline_FIXED_MAX_LOOP_fu_247_fixed_max_out;
wire    grp_compute_adapt_stats_Pipeline_FIXED_MAX_LOOP_fu_247_fixed_max_out_ap_vld;
wire    grp_compute_adapt_stats_Pipeline_INIT_ADAPT_fu_262_ap_start;
wire    grp_compute_adapt_stats_Pipeline_INIT_ADAPT_fu_262_ap_done;
wire    grp_compute_adapt_stats_Pipeline_INIT_ADAPT_fu_262_ap_idle;
wire    grp_compute_adapt_stats_Pipeline_INIT_ADAPT_fu_262_ap_ready;
wire   [4:0] grp_compute_adapt_stats_Pipeline_INIT_ADAPT_fu_262_cur_3_address0;
wire    grp_compute_adapt_stats_Pipeline_INIT_ADAPT_fu_262_cur_3_ce0;
wire    grp_compute_adapt_stats_Pipeline_INIT_ADAPT_fu_262_cur_3_we0;
wire   [15:0] grp_compute_adapt_stats_Pipeline_INIT_ADAPT_fu_262_cur_3_d0;
wire   [4:0] grp_compute_adapt_stats_Pipeline_INIT_ADAPT_fu_262_cur_2_address0;
wire    grp_compute_adapt_stats_Pipeline_INIT_ADAPT_fu_262_cur_2_ce0;
wire    grp_compute_adapt_stats_Pipeline_INIT_ADAPT_fu_262_cur_2_we0;
wire   [15:0] grp_compute_adapt_stats_Pipeline_INIT_ADAPT_fu_262_cur_2_d0;
wire   [4:0] grp_compute_adapt_stats_Pipeline_INIT_ADAPT_fu_262_cur_1_address0;
wire    grp_compute_adapt_stats_Pipeline_INIT_ADAPT_fu_262_cur_1_ce0;
wire    grp_compute_adapt_stats_Pipeline_INIT_ADAPT_fu_262_cur_1_we0;
wire   [15:0] grp_compute_adapt_stats_Pipeline_INIT_ADAPT_fu_262_cur_1_d0;
wire   [4:0] grp_compute_adapt_stats_Pipeline_INIT_ADAPT_fu_262_cur_address0;
wire    grp_compute_adapt_stats_Pipeline_INIT_ADAPT_fu_262_cur_ce0;
wire    grp_compute_adapt_stats_Pipeline_INIT_ADAPT_fu_262_cur_we0;
wire   [15:0] grp_compute_adapt_stats_Pipeline_INIT_ADAPT_fu_262_cur_d0;
wire   [4:0] grp_compute_adapt_stats_Pipeline_INIT_ADAPT_fu_262_adapt_runs_3_address0;
wire    grp_compute_adapt_stats_Pipeline_INIT_ADAPT_fu_262_adapt_runs_3_ce0;
wire    grp_compute_adapt_stats_Pipeline_INIT_ADAPT_fu_262_adapt_runs_3_we0;
wire   [15:0] grp_compute_adapt_stats_Pipeline_INIT_ADAPT_fu_262_adapt_runs_3_d0;
wire   [4:0] grp_compute_adapt_stats_Pipeline_INIT_ADAPT_fu_262_adapt_runs_2_address0;
wire    grp_compute_adapt_stats_Pipeline_INIT_ADAPT_fu_262_adapt_runs_2_ce0;
wire    grp_compute_adapt_stats_Pipeline_INIT_ADAPT_fu_262_adapt_runs_2_we0;
wire   [15:0] grp_compute_adapt_stats_Pipeline_INIT_ADAPT_fu_262_adapt_runs_2_d0;
wire   [4:0] grp_compute_adapt_stats_Pipeline_INIT_ADAPT_fu_262_adapt_runs_1_address0;
wire    grp_compute_adapt_stats_Pipeline_INIT_ADAPT_fu_262_adapt_runs_1_ce0;
wire    grp_compute_adapt_stats_Pipeline_INIT_ADAPT_fu_262_adapt_runs_1_we0;
wire   [15:0] grp_compute_adapt_stats_Pipeline_INIT_ADAPT_fu_262_adapt_runs_1_d0;
wire   [4:0] grp_compute_adapt_stats_Pipeline_INIT_ADAPT_fu_262_adapt_runs_address0;
wire    grp_compute_adapt_stats_Pipeline_INIT_ADAPT_fu_262_adapt_runs_ce0;
wire    grp_compute_adapt_stats_Pipeline_INIT_ADAPT_fu_262_adapt_runs_we0;
wire   [15:0] grp_compute_adapt_stats_Pipeline_INIT_ADAPT_fu_262_adapt_runs_d0;
wire    grp_compute_adapt_stats_Pipeline_ADAPT_COLS_fu_274_ap_start;
wire    grp_compute_adapt_stats_Pipeline_ADAPT_COLS_fu_274_ap_done;
wire    grp_compute_adapt_stats_Pipeline_ADAPT_COLS_fu_274_ap_idle;
wire    grp_compute_adapt_stats_Pipeline_ADAPT_COLS_fu_274_ap_ready;
wire   [4:0] grp_compute_adapt_stats_Pipeline_ADAPT_COLS_fu_274_adapt_runs_address0;
wire    grp_compute_adapt_stats_Pipeline_ADAPT_COLS_fu_274_adapt_runs_ce0;
wire    grp_compute_adapt_stats_Pipeline_ADAPT_COLS_fu_274_adapt_runs_we0;
wire   [15:0] grp_compute_adapt_stats_Pipeline_ADAPT_COLS_fu_274_adapt_runs_d0;
wire   [4:0] grp_compute_adapt_stats_Pipeline_ADAPT_COLS_fu_274_adapt_runs_address1;
wire    grp_compute_adapt_stats_Pipeline_ADAPT_COLS_fu_274_adapt_runs_ce1;
wire   [4:0] grp_compute_adapt_stats_Pipeline_ADAPT_COLS_fu_274_adapt_runs_1_address0;
wire    grp_compute_adapt_stats_Pipeline_ADAPT_COLS_fu_274_adapt_runs_1_ce0;
wire    grp_compute_adapt_stats_Pipeline_ADAPT_COLS_fu_274_adapt_runs_1_we0;
wire   [15:0] grp_compute_adapt_stats_Pipeline_ADAPT_COLS_fu_274_adapt_runs_1_d0;
wire   [4:0] grp_compute_adapt_stats_Pipeline_ADAPT_COLS_fu_274_adapt_runs_1_address1;
wire    grp_compute_adapt_stats_Pipeline_ADAPT_COLS_fu_274_adapt_runs_1_ce1;
wire   [4:0] grp_compute_adapt_stats_Pipeline_ADAPT_COLS_fu_274_adapt_runs_2_address0;
wire    grp_compute_adapt_stats_Pipeline_ADAPT_COLS_fu_274_adapt_runs_2_ce0;
wire    grp_compute_adapt_stats_Pipeline_ADAPT_COLS_fu_274_adapt_runs_2_we0;
wire   [15:0] grp_compute_adapt_stats_Pipeline_ADAPT_COLS_fu_274_adapt_runs_2_d0;
wire   [4:0] grp_compute_adapt_stats_Pipeline_ADAPT_COLS_fu_274_adapt_runs_2_address1;
wire    grp_compute_adapt_stats_Pipeline_ADAPT_COLS_fu_274_adapt_runs_2_ce1;
wire   [4:0] grp_compute_adapt_stats_Pipeline_ADAPT_COLS_fu_274_adapt_runs_3_address0;
wire    grp_compute_adapt_stats_Pipeline_ADAPT_COLS_fu_274_adapt_runs_3_ce0;
wire    grp_compute_adapt_stats_Pipeline_ADAPT_COLS_fu_274_adapt_runs_3_we0;
wire   [15:0] grp_compute_adapt_stats_Pipeline_ADAPT_COLS_fu_274_adapt_runs_3_d0;
wire   [4:0] grp_compute_adapt_stats_Pipeline_ADAPT_COLS_fu_274_adapt_runs_3_address1;
wire    grp_compute_adapt_stats_Pipeline_ADAPT_COLS_fu_274_adapt_runs_3_ce1;
wire   [4:0] grp_compute_adapt_stats_Pipeline_ADAPT_COLS_fu_274_cur_address0;
wire    grp_compute_adapt_stats_Pipeline_ADAPT_COLS_fu_274_cur_ce0;
wire    grp_compute_adapt_stats_Pipeline_ADAPT_COLS_fu_274_cur_we0;
wire   [15:0] grp_compute_adapt_stats_Pipeline_ADAPT_COLS_fu_274_cur_d0;
wire   [4:0] grp_compute_adapt_stats_Pipeline_ADAPT_COLS_fu_274_cur_address1;
wire    grp_compute_adapt_stats_Pipeline_ADAPT_COLS_fu_274_cur_ce1;
wire    grp_compute_adapt_stats_Pipeline_ADAPT_COLS_fu_274_cur_we1;
wire   [15:0] grp_compute_adapt_stats_Pipeline_ADAPT_COLS_fu_274_cur_d1;
wire   [4:0] grp_compute_adapt_stats_Pipeline_ADAPT_COLS_fu_274_cur_1_address0;
wire    grp_compute_adapt_stats_Pipeline_ADAPT_COLS_fu_274_cur_1_ce0;
wire    grp_compute_adapt_stats_Pipeline_ADAPT_COLS_fu_274_cur_1_we0;
wire   [15:0] grp_compute_adapt_stats_Pipeline_ADAPT_COLS_fu_274_cur_1_d0;
wire   [4:0] grp_compute_adapt_stats_Pipeline_ADAPT_COLS_fu_274_cur_1_address1;
wire    grp_compute_adapt_stats_Pipeline_ADAPT_COLS_fu_274_cur_1_ce1;
wire    grp_compute_adapt_stats_Pipeline_ADAPT_COLS_fu_274_cur_1_we1;
wire   [15:0] grp_compute_adapt_stats_Pipeline_ADAPT_COLS_fu_274_cur_1_d1;
wire   [4:0] grp_compute_adapt_stats_Pipeline_ADAPT_COLS_fu_274_cur_2_address0;
wire    grp_compute_adapt_stats_Pipeline_ADAPT_COLS_fu_274_cur_2_ce0;
wire    grp_compute_adapt_stats_Pipeline_ADAPT_COLS_fu_274_cur_2_we0;
wire   [15:0] grp_compute_adapt_stats_Pipeline_ADAPT_COLS_fu_274_cur_2_d0;
wire   [4:0] grp_compute_adapt_stats_Pipeline_ADAPT_COLS_fu_274_cur_2_address1;
wire    grp_compute_adapt_stats_Pipeline_ADAPT_COLS_fu_274_cur_2_ce1;
wire    grp_compute_adapt_stats_Pipeline_ADAPT_COLS_fu_274_cur_2_we1;
wire   [15:0] grp_compute_adapt_stats_Pipeline_ADAPT_COLS_fu_274_cur_2_d1;
wire   [4:0] grp_compute_adapt_stats_Pipeline_ADAPT_COLS_fu_274_cur_3_address0;
wire    grp_compute_adapt_stats_Pipeline_ADAPT_COLS_fu_274_cur_3_ce0;
wire    grp_compute_adapt_stats_Pipeline_ADAPT_COLS_fu_274_cur_3_we0;
wire   [15:0] grp_compute_adapt_stats_Pipeline_ADAPT_COLS_fu_274_cur_3_d0;
wire   [4:0] grp_compute_adapt_stats_Pipeline_ADAPT_COLS_fu_274_cur_3_address1;
wire    grp_compute_adapt_stats_Pipeline_ADAPT_COLS_fu_274_cur_3_ce1;
wire    grp_compute_adapt_stats_Pipeline_ADAPT_COLS_fu_274_cur_3_we1;
wire   [15:0] grp_compute_adapt_stats_Pipeline_ADAPT_COLS_fu_274_cur_3_d1;
wire   [12:0] grp_compute_adapt_stats_Pipeline_ADAPT_COLS_fu_274_pix_buf_address0;
wire    grp_compute_adapt_stats_Pipeline_ADAPT_COLS_fu_274_pix_buf_ce0;
wire    grp_topk_sum_hist_fu_291_ap_start;
wire    grp_topk_sum_hist_fu_291_ap_done;
wire    grp_topk_sum_hist_fu_291_ap_idle;
wire    grp_topk_sum_hist_fu_291_ap_ready;
wire   [4:0] grp_topk_sum_hist_fu_291_runs_0_address0;
wire    grp_topk_sum_hist_fu_291_runs_0_ce0;
wire   [4:0] grp_topk_sum_hist_fu_291_runs_1_address0;
wire    grp_topk_sum_hist_fu_291_runs_1_ce0;
wire   [4:0] grp_topk_sum_hist_fu_291_runs_2_address0;
wire    grp_topk_sum_hist_fu_291_runs_2_ce0;
wire   [4:0] grp_topk_sum_hist_fu_291_runs_3_address0;
wire    grp_topk_sum_hist_fu_291_runs_3_ce0;
wire   [31:0] grp_topk_sum_hist_fu_291_ap_return;
reg   [31:0] mean_center_reg_180;
reg   [31:0] ap_phi_mux_agg_result_fixed_max_run_0_phi_fu_195_p4;
reg   [31:0] agg_result_fixed_max_run_0_reg_191;
wire    ap_CS_fsm_state42;
reg    ap_block_state42_on_subcall_done;
reg   [31:0] ap_phi_mux_agg_result_adapt_topk_sum_0_phi_fu_206_p4;
reg   [31:0] agg_result_adapt_topk_sum_0_reg_202;
reg   [0:0] ap_phi_mux_agg_result_valid_0_phi_fu_217_p4;
reg   [0:0] agg_result_valid_0_reg_213;
reg   [5:0] ap_phi_mux_agg_result_adapt_topk_k_0_phi_fu_229_p4;
reg   [5:0] agg_result_adapt_topk_k_0_reg_225;
reg   [7:0] ap_phi_mux_agg_result_t_adapt_0_phi_fu_240_p4;
reg   [7:0] agg_result_t_adapt_0_reg_236;
reg    grp_compute_adapt_stats_Pipeline_FIXED_MAX_LOOP_fu_247_ap_start_reg;
wire    ap_CS_fsm_state2;
reg    grp_compute_adapt_stats_Pipeline_INIT_ADAPT_fu_262_ap_start_reg;
reg    grp_compute_adapt_stats_Pipeline_ADAPT_COLS_fu_274_ap_start_reg;
wire   [0:0] icmp_ln240_fu_487_p2;
wire   [0:0] icmp_ln241_fu_508_p2;
wire    ap_CS_fsm_state41;
reg    grp_topk_sum_hist_fu_291_ap_start_reg;
reg   [6:0] y_fu_146;
wire   [6:0] add_ln240_fu_493_p2;
wire   [0:0] icmp_ln214_fu_325_p2;
wire   [0:0] xor_ln214_fu_319_p2;
wire   [0:0] icmp_ln214_2_fu_337_p2;
wire   [0:0] icmp_ln214_3_fu_343_p2;
wire   [0:0] or_ln214_1_fu_355_p2;
wire   [0:0] icmp_ln214_1_fu_331_p2;
wire   [0:0] or_ln214_2_fu_361_p2;
wire   [0:0] or_ln214_fu_349_p2;
wire   [6:0] count_fu_373_p0;
wire   [7:0] count_fu_373_p1;
wire   [13:0] div_i6_fu_390_p4;
wire   [31:0] zext_ln83_fu_399_p1;
wire   [31:0] grp_fu_408_p0;
wire   [15:0] grp_fu_408_p1;
wire   [31:0] sub_ln225_fu_419_p2;
wire   [23:0] tmp_fu_428_p4;
wire   [0:0] tmp_44_fu_444_p3;
wire   [0:0] xor_ln70_fu_452_p2;
wire   [0:0] icmp_ln71_fu_438_p2;
wire   [0:0] or_ln70_fu_466_p2;
wire   [7:0] select_ln70_fu_458_p3;
wire   [7:0] trunc_ln71_fu_424_p1;
wire   [5:0] trunc_ln240_fu_483_p1;
wire   [7:0] add_ln256_fu_518_p2;
wire   [5:0] k_fu_523_p4;
wire   [0:0] icmp_ln257_fu_533_p2;
wire   [31:0] agg_result_adapt_topk_k_0_cast_fu_552_p1;
wire   [31:0] agg_result_t_adapt_0_cast_fu_548_p1;
reg    grp_fu_408_ap_start;
wire    grp_fu_408_ap_done;
reg   [0:0] ap_return_0_preg;
reg   [31:0] ap_return_1_preg;
reg   [31:0] ap_return_2_preg;
reg   [31:0] ap_return_3_preg;
reg   [31:0] ap_return_4_preg;
reg   [31:0] ap_return_5_preg;
reg   [41:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
reg    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
wire    ap_ST_fsm_state8_blk;
wire    ap_ST_fsm_state9_blk;
wire    ap_ST_fsm_state10_blk;
wire    ap_ST_fsm_state11_blk;
wire    ap_ST_fsm_state12_blk;
wire    ap_ST_fsm_state13_blk;
wire    ap_ST_fsm_state14_blk;
wire    ap_ST_fsm_state15_blk;
wire    ap_ST_fsm_state16_blk;
wire    ap_ST_fsm_state17_blk;
wire    ap_ST_fsm_state18_blk;
wire    ap_ST_fsm_state19_blk;
wire    ap_ST_fsm_state20_blk;
wire    ap_ST_fsm_state21_blk;
wire    ap_ST_fsm_state22_blk;
wire    ap_ST_fsm_state23_blk;
wire    ap_ST_fsm_state24_blk;
wire    ap_ST_fsm_state25_blk;
wire    ap_ST_fsm_state26_blk;
wire    ap_ST_fsm_state27_blk;
wire    ap_ST_fsm_state28_blk;
wire    ap_ST_fsm_state29_blk;
wire    ap_ST_fsm_state30_blk;
wire    ap_ST_fsm_state31_blk;
wire    ap_ST_fsm_state32_blk;
wire    ap_ST_fsm_state33_blk;
wire    ap_ST_fsm_state34_blk;
wire    ap_ST_fsm_state35_blk;
wire    ap_ST_fsm_state36_blk;
wire    ap_ST_fsm_state37_blk;
wire    ap_ST_fsm_state38_blk;
reg    ap_ST_fsm_state39_blk;
wire    ap_ST_fsm_state40_blk;
reg    ap_ST_fsm_state41_blk;
reg    ap_ST_fsm_state42_blk;
wire   [14:0] count_fu_373_p00;
wire   [14:0] count_fu_373_p10;
wire   [31:0] grp_fu_408_p10;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 42'd1;
#0 grp_compute_adapt_stats_Pipeline_FIXED_MAX_LOOP_fu_247_ap_start_reg = 1'b0;
#0 grp_compute_adapt_stats_Pipeline_INIT_ADAPT_fu_262_ap_start_reg = 1'b0;
#0 grp_compute_adapt_stats_Pipeline_ADAPT_COLS_fu_274_ap_start_reg = 1'b0;
#0 grp_topk_sum_hist_fu_291_ap_start_reg = 1'b0;
#0 y_fu_146 = 7'd0;
#0 ap_return_0_preg = 1'd0;
#0 ap_return_1_preg = 32'd0;
#0 ap_return_2_preg = 32'd0;
#0 ap_return_3_preg = 32'd0;
#0 ap_return_4_preg = 32'd0;
#0 ap_return_5_preg = 32'd0;
end

eye_feature_compute_adapt_stats_adapt_runs_RAM_AUTO_1R1W #(
    .DataWidth( 16 ),
    .AddressRange( 32 ),
    .AddressWidth( 5 ))
adapt_runs_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(adapt_runs_address0),
    .ce0(adapt_runs_ce0),
    .we0(adapt_runs_we0),
    .d0(adapt_runs_d0),
    .q0(adapt_runs_q0),
    .address1(grp_compute_adapt_stats_Pipeline_ADAPT_COLS_fu_274_adapt_runs_address1),
    .ce1(adapt_runs_ce1),
    .q1(adapt_runs_q1)
);

eye_feature_compute_adapt_stats_adapt_runs_RAM_AUTO_1R1W #(
    .DataWidth( 16 ),
    .AddressRange( 32 ),
    .AddressWidth( 5 ))
adapt_runs_1_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(adapt_runs_1_address0),
    .ce0(adapt_runs_1_ce0),
    .we0(adapt_runs_1_we0),
    .d0(adapt_runs_1_d0),
    .q0(adapt_runs_1_q0),
    .address1(grp_compute_adapt_stats_Pipeline_ADAPT_COLS_fu_274_adapt_runs_1_address1),
    .ce1(adapt_runs_1_ce1),
    .q1(adapt_runs_1_q1)
);

eye_feature_compute_adapt_stats_adapt_runs_RAM_AUTO_1R1W #(
    .DataWidth( 16 ),
    .AddressRange( 32 ),
    .AddressWidth( 5 ))
adapt_runs_2_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(adapt_runs_2_address0),
    .ce0(adapt_runs_2_ce0),
    .we0(adapt_runs_2_we0),
    .d0(adapt_runs_2_d0),
    .q0(adapt_runs_2_q0),
    .address1(grp_compute_adapt_stats_Pipeline_ADAPT_COLS_fu_274_adapt_runs_2_address1),
    .ce1(adapt_runs_2_ce1),
    .q1(adapt_runs_2_q1)
);

eye_feature_compute_adapt_stats_adapt_runs_RAM_AUTO_1R1W #(
    .DataWidth( 16 ),
    .AddressRange( 32 ),
    .AddressWidth( 5 ))
adapt_runs_3_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(adapt_runs_3_address0),
    .ce0(adapt_runs_3_ce0),
    .we0(adapt_runs_3_we0),
    .d0(adapt_runs_3_d0),
    .q0(adapt_runs_3_q0),
    .address1(grp_compute_adapt_stats_Pipeline_ADAPT_COLS_fu_274_adapt_runs_3_address1),
    .ce1(adapt_runs_3_ce1),
    .q1(adapt_runs_3_q1)
);

eye_feature_compute_adapt_stats_cur_RAM_AUTO_1R1W #(
    .DataWidth( 16 ),
    .AddressRange( 32 ),
    .AddressWidth( 5 ))
cur_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(cur_address0),
    .ce0(cur_ce0),
    .we0(cur_we0),
    .d0(cur_d0),
    .address1(grp_compute_adapt_stats_Pipeline_ADAPT_COLS_fu_274_cur_address1),
    .ce1(cur_ce1),
    .we1(cur_we1),
    .d1(grp_compute_adapt_stats_Pipeline_ADAPT_COLS_fu_274_cur_d1),
    .q1(cur_q1)
);

eye_feature_compute_adapt_stats_cur_RAM_AUTO_1R1W #(
    .DataWidth( 16 ),
    .AddressRange( 32 ),
    .AddressWidth( 5 ))
cur_1_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(cur_1_address0),
    .ce0(cur_1_ce0),
    .we0(cur_1_we0),
    .d0(cur_1_d0),
    .address1(grp_compute_adapt_stats_Pipeline_ADAPT_COLS_fu_274_cur_1_address1),
    .ce1(cur_1_ce1),
    .we1(cur_1_we1),
    .d1(grp_compute_adapt_stats_Pipeline_ADAPT_COLS_fu_274_cur_1_d1),
    .q1(cur_1_q1)
);

eye_feature_compute_adapt_stats_cur_RAM_AUTO_1R1W #(
    .DataWidth( 16 ),
    .AddressRange( 32 ),
    .AddressWidth( 5 ))
cur_2_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(cur_2_address0),
    .ce0(cur_2_ce0),
    .we0(cur_2_we0),
    .d0(cur_2_d0),
    .address1(grp_compute_adapt_stats_Pipeline_ADAPT_COLS_fu_274_cur_2_address1),
    .ce1(cur_2_ce1),
    .we1(cur_2_we1),
    .d1(grp_compute_adapt_stats_Pipeline_ADAPT_COLS_fu_274_cur_2_d1),
    .q1(cur_2_q1)
);

eye_feature_compute_adapt_stats_cur_RAM_AUTO_1R1W #(
    .DataWidth( 16 ),
    .AddressRange( 32 ),
    .AddressWidth( 5 ))
cur_3_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(cur_3_address0),
    .ce0(cur_3_ce0),
    .we0(cur_3_we0),
    .d0(cur_3_d0),
    .address1(grp_compute_adapt_stats_Pipeline_ADAPT_COLS_fu_274_cur_3_address1),
    .ce1(cur_3_ce1),
    .we1(cur_3_we1),
    .d1(grp_compute_adapt_stats_Pipeline_ADAPT_COLS_fu_274_cur_3_d1),
    .q1(cur_3_q1)
);

eye_feature_compute_adapt_stats_Pipeline_FIXED_MAX_LOOP grp_compute_adapt_stats_Pipeline_FIXED_MAX_LOOP_fu_247(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_compute_adapt_stats_Pipeline_FIXED_MAX_LOOP_fu_247_ap_start),
    .ap_done(grp_compute_adapt_stats_Pipeline_FIXED_MAX_LOOP_fu_247_ap_done),
    .ap_idle(grp_compute_adapt_stats_Pipeline_FIXED_MAX_LOOP_fu_247_ap_idle),
    .ap_ready(grp_compute_adapt_stats_Pipeline_FIXED_MAX_LOOP_fu_247_ap_ready),
    .cw(cw),
    .fixed_runs_0_address0(grp_compute_adapt_stats_Pipeline_FIXED_MAX_LOOP_fu_247_fixed_runs_0_address0),
    .fixed_runs_0_ce0(grp_compute_adapt_stats_Pipeline_FIXED_MAX_LOOP_fu_247_fixed_runs_0_ce0),
    .fixed_runs_0_q0(fixed_runs_0_q0),
    .fixed_runs_1_address0(grp_compute_adapt_stats_Pipeline_FIXED_MAX_LOOP_fu_247_fixed_runs_1_address0),
    .fixed_runs_1_ce0(grp_compute_adapt_stats_Pipeline_FIXED_MAX_LOOP_fu_247_fixed_runs_1_ce0),
    .fixed_runs_1_q0(fixed_runs_1_q0),
    .fixed_runs_2_address0(grp_compute_adapt_stats_Pipeline_FIXED_MAX_LOOP_fu_247_fixed_runs_2_address0),
    .fixed_runs_2_ce0(grp_compute_adapt_stats_Pipeline_FIXED_MAX_LOOP_fu_247_fixed_runs_2_ce0),
    .fixed_runs_2_q0(fixed_runs_2_q0),
    .fixed_runs_3_address0(grp_compute_adapt_stats_Pipeline_FIXED_MAX_LOOP_fu_247_fixed_runs_3_address0),
    .fixed_runs_3_ce0(grp_compute_adapt_stats_Pipeline_FIXED_MAX_LOOP_fu_247_fixed_runs_3_ce0),
    .fixed_runs_3_q0(fixed_runs_3_q0),
    .fixed_max_out(grp_compute_adapt_stats_Pipeline_FIXED_MAX_LOOP_fu_247_fixed_max_out),
    .fixed_max_out_ap_vld(grp_compute_adapt_stats_Pipeline_FIXED_MAX_LOOP_fu_247_fixed_max_out_ap_vld)
);

eye_feature_compute_adapt_stats_Pipeline_INIT_ADAPT grp_compute_adapt_stats_Pipeline_INIT_ADAPT_fu_262(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_compute_adapt_stats_Pipeline_INIT_ADAPT_fu_262_ap_start),
    .ap_done(grp_compute_adapt_stats_Pipeline_INIT_ADAPT_fu_262_ap_done),
    .ap_idle(grp_compute_adapt_stats_Pipeline_INIT_ADAPT_fu_262_ap_idle),
    .ap_ready(grp_compute_adapt_stats_Pipeline_INIT_ADAPT_fu_262_ap_ready),
    .cur_3_address0(grp_compute_adapt_stats_Pipeline_INIT_ADAPT_fu_262_cur_3_address0),
    .cur_3_ce0(grp_compute_adapt_stats_Pipeline_INIT_ADAPT_fu_262_cur_3_ce0),
    .cur_3_we0(grp_compute_adapt_stats_Pipeline_INIT_ADAPT_fu_262_cur_3_we0),
    .cur_3_d0(grp_compute_adapt_stats_Pipeline_INIT_ADAPT_fu_262_cur_3_d0),
    .cur_2_address0(grp_compute_adapt_stats_Pipeline_INIT_ADAPT_fu_262_cur_2_address0),
    .cur_2_ce0(grp_compute_adapt_stats_Pipeline_INIT_ADAPT_fu_262_cur_2_ce0),
    .cur_2_we0(grp_compute_adapt_stats_Pipeline_INIT_ADAPT_fu_262_cur_2_we0),
    .cur_2_d0(grp_compute_adapt_stats_Pipeline_INIT_ADAPT_fu_262_cur_2_d0),
    .cur_1_address0(grp_compute_adapt_stats_Pipeline_INIT_ADAPT_fu_262_cur_1_address0),
    .cur_1_ce0(grp_compute_adapt_stats_Pipeline_INIT_ADAPT_fu_262_cur_1_ce0),
    .cur_1_we0(grp_compute_adapt_stats_Pipeline_INIT_ADAPT_fu_262_cur_1_we0),
    .cur_1_d0(grp_compute_adapt_stats_Pipeline_INIT_ADAPT_fu_262_cur_1_d0),
    .cur_address0(grp_compute_adapt_stats_Pipeline_INIT_ADAPT_fu_262_cur_address0),
    .cur_ce0(grp_compute_adapt_stats_Pipeline_INIT_ADAPT_fu_262_cur_ce0),
    .cur_we0(grp_compute_adapt_stats_Pipeline_INIT_ADAPT_fu_262_cur_we0),
    .cur_d0(grp_compute_adapt_stats_Pipeline_INIT_ADAPT_fu_262_cur_d0),
    .adapt_runs_3_address0(grp_compute_adapt_stats_Pipeline_INIT_ADAPT_fu_262_adapt_runs_3_address0),
    .adapt_runs_3_ce0(grp_compute_adapt_stats_Pipeline_INIT_ADAPT_fu_262_adapt_runs_3_ce0),
    .adapt_runs_3_we0(grp_compute_adapt_stats_Pipeline_INIT_ADAPT_fu_262_adapt_runs_3_we0),
    .adapt_runs_3_d0(grp_compute_adapt_stats_Pipeline_INIT_ADAPT_fu_262_adapt_runs_3_d0),
    .adapt_runs_2_address0(grp_compute_adapt_stats_Pipeline_INIT_ADAPT_fu_262_adapt_runs_2_address0),
    .adapt_runs_2_ce0(grp_compute_adapt_stats_Pipeline_INIT_ADAPT_fu_262_adapt_runs_2_ce0),
    .adapt_runs_2_we0(grp_compute_adapt_stats_Pipeline_INIT_ADAPT_fu_262_adapt_runs_2_we0),
    .adapt_runs_2_d0(grp_compute_adapt_stats_Pipeline_INIT_ADAPT_fu_262_adapt_runs_2_d0),
    .adapt_runs_1_address0(grp_compute_adapt_stats_Pipeline_INIT_ADAPT_fu_262_adapt_runs_1_address0),
    .adapt_runs_1_ce0(grp_compute_adapt_stats_Pipeline_INIT_ADAPT_fu_262_adapt_runs_1_ce0),
    .adapt_runs_1_we0(grp_compute_adapt_stats_Pipeline_INIT_ADAPT_fu_262_adapt_runs_1_we0),
    .adapt_runs_1_d0(grp_compute_adapt_stats_Pipeline_INIT_ADAPT_fu_262_adapt_runs_1_d0),
    .adapt_runs_address0(grp_compute_adapt_stats_Pipeline_INIT_ADAPT_fu_262_adapt_runs_address0),
    .adapt_runs_ce0(grp_compute_adapt_stats_Pipeline_INIT_ADAPT_fu_262_adapt_runs_ce0),
    .adapt_runs_we0(grp_compute_adapt_stats_Pipeline_INIT_ADAPT_fu_262_adapt_runs_we0),
    .adapt_runs_d0(grp_compute_adapt_stats_Pipeline_INIT_ADAPT_fu_262_adapt_runs_d0)
);

eye_feature_compute_adapt_stats_Pipeline_ADAPT_COLS grp_compute_adapt_stats_Pipeline_ADAPT_COLS_fu_274(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_compute_adapt_stats_Pipeline_ADAPT_COLS_fu_274_ap_start),
    .ap_done(grp_compute_adapt_stats_Pipeline_ADAPT_COLS_fu_274_ap_done),
    .ap_idle(grp_compute_adapt_stats_Pipeline_ADAPT_COLS_fu_274_ap_idle),
    .ap_ready(grp_compute_adapt_stats_Pipeline_ADAPT_COLS_fu_274_ap_ready),
    .adapt_runs_address0(grp_compute_adapt_stats_Pipeline_ADAPT_COLS_fu_274_adapt_runs_address0),
    .adapt_runs_ce0(grp_compute_adapt_stats_Pipeline_ADAPT_COLS_fu_274_adapt_runs_ce0),
    .adapt_runs_we0(grp_compute_adapt_stats_Pipeline_ADAPT_COLS_fu_274_adapt_runs_we0),
    .adapt_runs_d0(grp_compute_adapt_stats_Pipeline_ADAPT_COLS_fu_274_adapt_runs_d0),
    .adapt_runs_address1(grp_compute_adapt_stats_Pipeline_ADAPT_COLS_fu_274_adapt_runs_address1),
    .adapt_runs_ce1(grp_compute_adapt_stats_Pipeline_ADAPT_COLS_fu_274_adapt_runs_ce1),
    .adapt_runs_q1(adapt_runs_q1),
    .adapt_runs_1_address0(grp_compute_adapt_stats_Pipeline_ADAPT_COLS_fu_274_adapt_runs_1_address0),
    .adapt_runs_1_ce0(grp_compute_adapt_stats_Pipeline_ADAPT_COLS_fu_274_adapt_runs_1_ce0),
    .adapt_runs_1_we0(grp_compute_adapt_stats_Pipeline_ADAPT_COLS_fu_274_adapt_runs_1_we0),
    .adapt_runs_1_d0(grp_compute_adapt_stats_Pipeline_ADAPT_COLS_fu_274_adapt_runs_1_d0),
    .adapt_runs_1_address1(grp_compute_adapt_stats_Pipeline_ADAPT_COLS_fu_274_adapt_runs_1_address1),
    .adapt_runs_1_ce1(grp_compute_adapt_stats_Pipeline_ADAPT_COLS_fu_274_adapt_runs_1_ce1),
    .adapt_runs_1_q1(adapt_runs_1_q1),
    .adapt_runs_2_address0(grp_compute_adapt_stats_Pipeline_ADAPT_COLS_fu_274_adapt_runs_2_address0),
    .adapt_runs_2_ce0(grp_compute_adapt_stats_Pipeline_ADAPT_COLS_fu_274_adapt_runs_2_ce0),
    .adapt_runs_2_we0(grp_compute_adapt_stats_Pipeline_ADAPT_COLS_fu_274_adapt_runs_2_we0),
    .adapt_runs_2_d0(grp_compute_adapt_stats_Pipeline_ADAPT_COLS_fu_274_adapt_runs_2_d0),
    .adapt_runs_2_address1(grp_compute_adapt_stats_Pipeline_ADAPT_COLS_fu_274_adapt_runs_2_address1),
    .adapt_runs_2_ce1(grp_compute_adapt_stats_Pipeline_ADAPT_COLS_fu_274_adapt_runs_2_ce1),
    .adapt_runs_2_q1(adapt_runs_2_q1),
    .adapt_runs_3_address0(grp_compute_adapt_stats_Pipeline_ADAPT_COLS_fu_274_adapt_runs_3_address0),
    .adapt_runs_3_ce0(grp_compute_adapt_stats_Pipeline_ADAPT_COLS_fu_274_adapt_runs_3_ce0),
    .adapt_runs_3_we0(grp_compute_adapt_stats_Pipeline_ADAPT_COLS_fu_274_adapt_runs_3_we0),
    .adapt_runs_3_d0(grp_compute_adapt_stats_Pipeline_ADAPT_COLS_fu_274_adapt_runs_3_d0),
    .adapt_runs_3_address1(grp_compute_adapt_stats_Pipeline_ADAPT_COLS_fu_274_adapt_runs_3_address1),
    .adapt_runs_3_ce1(grp_compute_adapt_stats_Pipeline_ADAPT_COLS_fu_274_adapt_runs_3_ce1),
    .adapt_runs_3_q1(adapt_runs_3_q1),
    .t_adapt(t_adapt_reg_666),
    .cur_address0(grp_compute_adapt_stats_Pipeline_ADAPT_COLS_fu_274_cur_address0),
    .cur_ce0(grp_compute_adapt_stats_Pipeline_ADAPT_COLS_fu_274_cur_ce0),
    .cur_we0(grp_compute_adapt_stats_Pipeline_ADAPT_COLS_fu_274_cur_we0),
    .cur_d0(grp_compute_adapt_stats_Pipeline_ADAPT_COLS_fu_274_cur_d0),
    .cur_address1(grp_compute_adapt_stats_Pipeline_ADAPT_COLS_fu_274_cur_address1),
    .cur_ce1(grp_compute_adapt_stats_Pipeline_ADAPT_COLS_fu_274_cur_ce1),
    .cur_we1(grp_compute_adapt_stats_Pipeline_ADAPT_COLS_fu_274_cur_we1),
    .cur_d1(grp_compute_adapt_stats_Pipeline_ADAPT_COLS_fu_274_cur_d1),
    .cur_q1(cur_q1),
    .cur_1_address0(grp_compute_adapt_stats_Pipeline_ADAPT_COLS_fu_274_cur_1_address0),
    .cur_1_ce0(grp_compute_adapt_stats_Pipeline_ADAPT_COLS_fu_274_cur_1_ce0),
    .cur_1_we0(grp_compute_adapt_stats_Pipeline_ADAPT_COLS_fu_274_cur_1_we0),
    .cur_1_d0(grp_compute_adapt_stats_Pipeline_ADAPT_COLS_fu_274_cur_1_d0),
    .cur_1_address1(grp_compute_adapt_stats_Pipeline_ADAPT_COLS_fu_274_cur_1_address1),
    .cur_1_ce1(grp_compute_adapt_stats_Pipeline_ADAPT_COLS_fu_274_cur_1_ce1),
    .cur_1_we1(grp_compute_adapt_stats_Pipeline_ADAPT_COLS_fu_274_cur_1_we1),
    .cur_1_d1(grp_compute_adapt_stats_Pipeline_ADAPT_COLS_fu_274_cur_1_d1),
    .cur_1_q1(cur_1_q1),
    .cur_2_address0(grp_compute_adapt_stats_Pipeline_ADAPT_COLS_fu_274_cur_2_address0),
    .cur_2_ce0(grp_compute_adapt_stats_Pipeline_ADAPT_COLS_fu_274_cur_2_ce0),
    .cur_2_we0(grp_compute_adapt_stats_Pipeline_ADAPT_COLS_fu_274_cur_2_we0),
    .cur_2_d0(grp_compute_adapt_stats_Pipeline_ADAPT_COLS_fu_274_cur_2_d0),
    .cur_2_address1(grp_compute_adapt_stats_Pipeline_ADAPT_COLS_fu_274_cur_2_address1),
    .cur_2_ce1(grp_compute_adapt_stats_Pipeline_ADAPT_COLS_fu_274_cur_2_ce1),
    .cur_2_we1(grp_compute_adapt_stats_Pipeline_ADAPT_COLS_fu_274_cur_2_we1),
    .cur_2_d1(grp_compute_adapt_stats_Pipeline_ADAPT_COLS_fu_274_cur_2_d1),
    .cur_2_q1(cur_2_q1),
    .cur_3_address0(grp_compute_adapt_stats_Pipeline_ADAPT_COLS_fu_274_cur_3_address0),
    .cur_3_ce0(grp_compute_adapt_stats_Pipeline_ADAPT_COLS_fu_274_cur_3_ce0),
    .cur_3_we0(grp_compute_adapt_stats_Pipeline_ADAPT_COLS_fu_274_cur_3_we0),
    .cur_3_d0(grp_compute_adapt_stats_Pipeline_ADAPT_COLS_fu_274_cur_3_d0),
    .cur_3_address1(grp_compute_adapt_stats_Pipeline_ADAPT_COLS_fu_274_cur_3_address1),
    .cur_3_ce1(grp_compute_adapt_stats_Pipeline_ADAPT_COLS_fu_274_cur_3_ce1),
    .cur_3_we1(grp_compute_adapt_stats_Pipeline_ADAPT_COLS_fu_274_cur_3_we1),
    .cur_3_d1(grp_compute_adapt_stats_Pipeline_ADAPT_COLS_fu_274_cur_3_d1),
    .cur_3_q1(cur_3_q1),
    .zext_ln246(tmp_s_reg_675),
    .pix_buf_address0(grp_compute_adapt_stats_Pipeline_ADAPT_COLS_fu_274_pix_buf_address0),
    .pix_buf_ce0(grp_compute_adapt_stats_Pipeline_ADAPT_COLS_fu_274_pix_buf_ce0),
    .pix_buf_q0(pix_buf_q0),
    .cw(cw)
);

eye_feature_topk_sum_hist grp_topk_sum_hist_fu_291(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_topk_sum_hist_fu_291_ap_start),
    .ap_done(grp_topk_sum_hist_fu_291_ap_done),
    .ap_idle(grp_topk_sum_hist_fu_291_ap_idle),
    .ap_ready(grp_topk_sum_hist_fu_291_ap_ready),
    .runs_0_address0(grp_topk_sum_hist_fu_291_runs_0_address0),
    .runs_0_ce0(grp_topk_sum_hist_fu_291_runs_0_ce0),
    .runs_0_q0(adapt_runs_q0),
    .runs_1_address0(grp_topk_sum_hist_fu_291_runs_1_address0),
    .runs_1_ce0(grp_topk_sum_hist_fu_291_runs_1_ce0),
    .runs_1_q0(adapt_runs_1_q0),
    .runs_2_address0(grp_topk_sum_hist_fu_291_runs_2_address0),
    .runs_2_ce0(grp_topk_sum_hist_fu_291_runs_2_ce0),
    .runs_2_q0(adapt_runs_2_q0),
    .runs_3_address0(grp_topk_sum_hist_fu_291_runs_3_address0),
    .runs_3_ce0(grp_topk_sum_hist_fu_291_runs_3_ce0),
    .runs_3_q0(adapt_runs_3_q0),
    .cw(cw),
    .ch(ch),
    .k(k_1_reg_683),
    .ap_return(grp_topk_sum_hist_fu_291_ap_return)
);

eye_feature_mul_7ns_8ns_15_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 7 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 15 ))
mul_7ns_8ns_15_1_1_U129(
    .din0(count_fu_373_p0),
    .din1(count_fu_373_p1),
    .dout(count_fu_373_p2)
);

eye_feature_sdiv_32ns_16ns_32_36_seq_1 #(
    .ID( 1 ),
    .NUM_STAGE( 36 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 32 ))
sdiv_32ns_16ns_32_36_seq_1_U130(
    .clk(ap_clk),
    .reset(ap_rst),
    .start(grp_fu_408_ap_start),
    .done(grp_fu_408_ap_done),
    .din0(grp_fu_408_p0),
    .din1(grp_fu_408_p1),
    .ce(1'b1),
    .dout(grp_fu_408_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_0_preg <= 1'd0;
    end else begin
        if (((1'b0 == ap_block_state42_on_subcall_done) & (1'b1 == ap_CS_fsm_state42))) begin
            ap_return_0_preg <= ap_phi_mux_agg_result_valid_0_phi_fu_217_p4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
                ap_return_1_preg[0] <= 1'b0;
        ap_return_1_preg[1] <= 1'b0;
        ap_return_1_preg[2] <= 1'b0;
        ap_return_1_preg[3] <= 1'b0;
        ap_return_1_preg[4] <= 1'b0;
        ap_return_1_preg[5] <= 1'b0;
        ap_return_1_preg[6] <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_state42_on_subcall_done) & (1'b1 == ap_CS_fsm_state42))) begin
                        ap_return_1_preg[6 : 0] <= ch_cast10_reg_621[6 : 0];
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_2_preg <= 32'd0;
    end else begin
        if (((1'b0 == ap_block_state42_on_subcall_done) & (1'b1 == ap_CS_fsm_state42))) begin
            ap_return_2_preg <= ap_phi_mux_agg_result_fixed_max_run_0_phi_fu_195_p4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_3_preg <= 32'd0;
    end else begin
        if (((1'b0 == ap_block_state42_on_subcall_done) & (1'b1 == ap_CS_fsm_state42))) begin
            ap_return_3_preg <= ap_phi_mux_agg_result_adapt_topk_sum_0_phi_fu_206_p4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
                ap_return_4_preg[0] <= 1'b0;
        ap_return_4_preg[1] <= 1'b0;
        ap_return_4_preg[2] <= 1'b0;
        ap_return_4_preg[3] <= 1'b0;
        ap_return_4_preg[4] <= 1'b0;
        ap_return_4_preg[5] <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_state42_on_subcall_done) & (1'b1 == ap_CS_fsm_state42))) begin
                        ap_return_4_preg[5 : 0] <= agg_result_adapt_topk_k_0_cast_fu_552_p1[5 : 0];
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
                ap_return_5_preg[0] <= 1'b0;
        ap_return_5_preg[1] <= 1'b0;
        ap_return_5_preg[2] <= 1'b0;
        ap_return_5_preg[3] <= 1'b0;
        ap_return_5_preg[4] <= 1'b0;
        ap_return_5_preg[5] <= 1'b0;
        ap_return_5_preg[6] <= 1'b0;
        ap_return_5_preg[7] <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_state42_on_subcall_done) & (1'b1 == ap_CS_fsm_state42))) begin
                        ap_return_5_preg[7 : 0] <= agg_result_t_adapt_0_cast_fu_548_p1[7 : 0];
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_compute_adapt_stats_Pipeline_ADAPT_COLS_fu_274_ap_start_reg <= 1'b0;
    end else begin
        if (((icmp_ln241_fu_508_p2 == 1'd1) & (icmp_ln240_fu_487_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state40))) begin
            grp_compute_adapt_stats_Pipeline_ADAPT_COLS_fu_274_ap_start_reg <= 1'b1;
        end else if ((grp_compute_adapt_stats_Pipeline_ADAPT_COLS_fu_274_ap_ready == 1'b1)) begin
            grp_compute_adapt_stats_Pipeline_ADAPT_COLS_fu_274_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_compute_adapt_stats_Pipeline_FIXED_MAX_LOOP_fu_247_ap_start_reg <= 1'b0;
    end else begin
        if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (or_ln214_3_fu_367_p2 == 1'd0))) begin
            grp_compute_adapt_stats_Pipeline_FIXED_MAX_LOOP_fu_247_ap_start_reg <= 1'b1;
        end else if ((grp_compute_adapt_stats_Pipeline_FIXED_MAX_LOOP_fu_247_ap_ready == 1'b1)) begin
            grp_compute_adapt_stats_Pipeline_FIXED_MAX_LOOP_fu_247_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_compute_adapt_stats_Pipeline_INIT_ADAPT_fu_262_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state38)) begin
            grp_compute_adapt_stats_Pipeline_INIT_ADAPT_fu_262_ap_start_reg <= 1'b1;
        end else if ((grp_compute_adapt_stats_Pipeline_INIT_ADAPT_fu_262_ap_ready == 1'b1)) begin
            grp_compute_adapt_stats_Pipeline_INIT_ADAPT_fu_262_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_topk_sum_hist_fu_291_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state40) & ((icmp_ln241_fu_508_p2 == 1'd0) | (icmp_ln240_fu_487_p2 == 1'd1)))) begin
            grp_topk_sum_hist_fu_291_ap_start_reg <= 1'b1;
        end else if ((grp_topk_sum_hist_fu_291_ap_ready == 1'b1)) begin
            grp_topk_sum_hist_fu_291_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (or_ln214_3_fu_367_p2 == 1'd1))) begin
        agg_result_adapt_topk_k_0_reg_225 <= 6'd1;
    end else if (((1'b0 == ap_block_state42_on_subcall_done) & (1'b1 == ap_CS_fsm_state42) & (or_ln214_3_reg_626 == 1'd0))) begin
        agg_result_adapt_topk_k_0_reg_225 <= k_1_reg_683;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (or_ln214_3_fu_367_p2 == 1'd1))) begin
        agg_result_adapt_topk_sum_0_reg_202 <= 32'd0;
    end else if (((1'b0 == ap_block_state42_on_subcall_done) & (1'b1 == ap_CS_fsm_state42) & (or_ln214_3_reg_626 == 1'd0))) begin
        agg_result_adapt_topk_sum_0_reg_202 <= grp_topk_sum_hist_fu_291_ap_return;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (or_ln214_3_fu_367_p2 == 1'd1))) begin
        agg_result_fixed_max_run_0_reg_191 <= 32'd0;
    end else if (((1'b0 == ap_block_state42_on_subcall_done) & (1'b1 == ap_CS_fsm_state42) & (or_ln214_3_reg_626 == 1'd0))) begin
        agg_result_fixed_max_run_0_reg_191 <= grp_compute_adapt_stats_Pipeline_FIXED_MAX_LOOP_fu_247_fixed_max_out;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (or_ln214_3_fu_367_p2 == 1'd1))) begin
        agg_result_t_adapt_0_reg_236 <= 8'd0;
    end else if (((1'b0 == ap_block_state42_on_subcall_done) & (1'b1 == ap_CS_fsm_state42) & (or_ln214_3_reg_626 == 1'd0))) begin
        agg_result_t_adapt_0_reg_236 <= t_adapt_reg_666;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (or_ln214_3_fu_367_p2 == 1'd1))) begin
        agg_result_valid_0_reg_213 <= 1'd0;
    end else if (((1'b0 == ap_block_state42_on_subcall_done) & (1'b1 == ap_CS_fsm_state42) & (or_ln214_3_reg_626 == 1'd0))) begin
        agg_result_valid_0_reg_213 <= 1'd1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state3) & (icmp_ln82_fu_385_p2 == 1'd1))) begin
        mean_center_reg_180 <= 32'd0;
    end else if (((1'b1 == ap_CS_fsm_state38) & (icmp_ln82_reg_645 == 1'd0))) begin
        mean_center_reg_180 <= grp_fu_408_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state38)) begin
        y_fu_146 <= 7'd0;
    end else if (((icmp_ln241_fu_508_p2 == 1'd1) & (icmp_ln240_fu_487_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state40))) begin
        y_fu_146 <= add_ln240_fu_493_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        adapt_offset_cast_reg_616[7 : 0] <= adapt_offset_cast_fu_303_p1[7 : 0];
        ch_cast10_reg_621[6 : 0] <= ch_cast10_fu_307_p1[6 : 0];
        count_reg_630 <= count_fu_373_p2;
        or_ln214_3_reg_626 <= or_ln214_3_fu_367_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        icmp_ln82_reg_645 <= icmp_ln82_fu_385_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state40)) begin
        k_1_reg_683 <= k_1_fu_539_p3;
        tmp_s_reg_675[12 : 7] <= tmp_s_fu_499_p3[12 : 7];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state39)) begin
        t_adapt_reg_666 <= t_adapt_fu_472_p3;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state42) & (or_ln214_3_reg_626 == 1'd0))) begin
        adapt_runs_1_address0 = grp_topk_sum_hist_fu_291_runs_1_address0;
    end else if ((1'b1 == ap_CS_fsm_state41)) begin
        adapt_runs_1_address0 = grp_compute_adapt_stats_Pipeline_ADAPT_COLS_fu_274_adapt_runs_1_address0;
    end else if ((1'b1 == ap_CS_fsm_state39)) begin
        adapt_runs_1_address0 = grp_compute_adapt_stats_Pipeline_INIT_ADAPT_fu_262_adapt_runs_1_address0;
    end else begin
        adapt_runs_1_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state42) & (or_ln214_3_reg_626 == 1'd0))) begin
        adapt_runs_1_ce0 = grp_topk_sum_hist_fu_291_runs_1_ce0;
    end else if ((1'b1 == ap_CS_fsm_state41)) begin
        adapt_runs_1_ce0 = grp_compute_adapt_stats_Pipeline_ADAPT_COLS_fu_274_adapt_runs_1_ce0;
    end else if ((1'b1 == ap_CS_fsm_state39)) begin
        adapt_runs_1_ce0 = grp_compute_adapt_stats_Pipeline_INIT_ADAPT_fu_262_adapt_runs_1_ce0;
    end else begin
        adapt_runs_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state41)) begin
        adapt_runs_1_ce1 = grp_compute_adapt_stats_Pipeline_ADAPT_COLS_fu_274_adapt_runs_1_ce1;
    end else begin
        adapt_runs_1_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state41)) begin
        adapt_runs_1_d0 = grp_compute_adapt_stats_Pipeline_ADAPT_COLS_fu_274_adapt_runs_1_d0;
    end else if ((1'b1 == ap_CS_fsm_state39)) begin
        adapt_runs_1_d0 = grp_compute_adapt_stats_Pipeline_INIT_ADAPT_fu_262_adapt_runs_1_d0;
    end else begin
        adapt_runs_1_d0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state41)) begin
        adapt_runs_1_we0 = grp_compute_adapt_stats_Pipeline_ADAPT_COLS_fu_274_adapt_runs_1_we0;
    end else if ((1'b1 == ap_CS_fsm_state39)) begin
        adapt_runs_1_we0 = grp_compute_adapt_stats_Pipeline_INIT_ADAPT_fu_262_adapt_runs_1_we0;
    end else begin
        adapt_runs_1_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state42) & (or_ln214_3_reg_626 == 1'd0))) begin
        adapt_runs_2_address0 = grp_topk_sum_hist_fu_291_runs_2_address0;
    end else if ((1'b1 == ap_CS_fsm_state41)) begin
        adapt_runs_2_address0 = grp_compute_adapt_stats_Pipeline_ADAPT_COLS_fu_274_adapt_runs_2_address0;
    end else if ((1'b1 == ap_CS_fsm_state39)) begin
        adapt_runs_2_address0 = grp_compute_adapt_stats_Pipeline_INIT_ADAPT_fu_262_adapt_runs_2_address0;
    end else begin
        adapt_runs_2_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state42) & (or_ln214_3_reg_626 == 1'd0))) begin
        adapt_runs_2_ce0 = grp_topk_sum_hist_fu_291_runs_2_ce0;
    end else if ((1'b1 == ap_CS_fsm_state41)) begin
        adapt_runs_2_ce0 = grp_compute_adapt_stats_Pipeline_ADAPT_COLS_fu_274_adapt_runs_2_ce0;
    end else if ((1'b1 == ap_CS_fsm_state39)) begin
        adapt_runs_2_ce0 = grp_compute_adapt_stats_Pipeline_INIT_ADAPT_fu_262_adapt_runs_2_ce0;
    end else begin
        adapt_runs_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state41)) begin
        adapt_runs_2_ce1 = grp_compute_adapt_stats_Pipeline_ADAPT_COLS_fu_274_adapt_runs_2_ce1;
    end else begin
        adapt_runs_2_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state41)) begin
        adapt_runs_2_d0 = grp_compute_adapt_stats_Pipeline_ADAPT_COLS_fu_274_adapt_runs_2_d0;
    end else if ((1'b1 == ap_CS_fsm_state39)) begin
        adapt_runs_2_d0 = grp_compute_adapt_stats_Pipeline_INIT_ADAPT_fu_262_adapt_runs_2_d0;
    end else begin
        adapt_runs_2_d0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state41)) begin
        adapt_runs_2_we0 = grp_compute_adapt_stats_Pipeline_ADAPT_COLS_fu_274_adapt_runs_2_we0;
    end else if ((1'b1 == ap_CS_fsm_state39)) begin
        adapt_runs_2_we0 = grp_compute_adapt_stats_Pipeline_INIT_ADAPT_fu_262_adapt_runs_2_we0;
    end else begin
        adapt_runs_2_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state42) & (or_ln214_3_reg_626 == 1'd0))) begin
        adapt_runs_3_address0 = grp_topk_sum_hist_fu_291_runs_3_address0;
    end else if ((1'b1 == ap_CS_fsm_state41)) begin
        adapt_runs_3_address0 = grp_compute_adapt_stats_Pipeline_ADAPT_COLS_fu_274_adapt_runs_3_address0;
    end else if ((1'b1 == ap_CS_fsm_state39)) begin
        adapt_runs_3_address0 = grp_compute_adapt_stats_Pipeline_INIT_ADAPT_fu_262_adapt_runs_3_address0;
    end else begin
        adapt_runs_3_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state42) & (or_ln214_3_reg_626 == 1'd0))) begin
        adapt_runs_3_ce0 = grp_topk_sum_hist_fu_291_runs_3_ce0;
    end else if ((1'b1 == ap_CS_fsm_state41)) begin
        adapt_runs_3_ce0 = grp_compute_adapt_stats_Pipeline_ADAPT_COLS_fu_274_adapt_runs_3_ce0;
    end else if ((1'b1 == ap_CS_fsm_state39)) begin
        adapt_runs_3_ce0 = grp_compute_adapt_stats_Pipeline_INIT_ADAPT_fu_262_adapt_runs_3_ce0;
    end else begin
        adapt_runs_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state41)) begin
        adapt_runs_3_ce1 = grp_compute_adapt_stats_Pipeline_ADAPT_COLS_fu_274_adapt_runs_3_ce1;
    end else begin
        adapt_runs_3_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state41)) begin
        adapt_runs_3_d0 = grp_compute_adapt_stats_Pipeline_ADAPT_COLS_fu_274_adapt_runs_3_d0;
    end else if ((1'b1 == ap_CS_fsm_state39)) begin
        adapt_runs_3_d0 = grp_compute_adapt_stats_Pipeline_INIT_ADAPT_fu_262_adapt_runs_3_d0;
    end else begin
        adapt_runs_3_d0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state41)) begin
        adapt_runs_3_we0 = grp_compute_adapt_stats_Pipeline_ADAPT_COLS_fu_274_adapt_runs_3_we0;
    end else if ((1'b1 == ap_CS_fsm_state39)) begin
        adapt_runs_3_we0 = grp_compute_adapt_stats_Pipeline_INIT_ADAPT_fu_262_adapt_runs_3_we0;
    end else begin
        adapt_runs_3_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state42) & (or_ln214_3_reg_626 == 1'd0))) begin
        adapt_runs_address0 = grp_topk_sum_hist_fu_291_runs_0_address0;
    end else if ((1'b1 == ap_CS_fsm_state41)) begin
        adapt_runs_address0 = grp_compute_adapt_stats_Pipeline_ADAPT_COLS_fu_274_adapt_runs_address0;
    end else if ((1'b1 == ap_CS_fsm_state39)) begin
        adapt_runs_address0 = grp_compute_adapt_stats_Pipeline_INIT_ADAPT_fu_262_adapt_runs_address0;
    end else begin
        adapt_runs_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state42) & (or_ln214_3_reg_626 == 1'd0))) begin
        adapt_runs_ce0 = grp_topk_sum_hist_fu_291_runs_0_ce0;
    end else if ((1'b1 == ap_CS_fsm_state41)) begin
        adapt_runs_ce0 = grp_compute_adapt_stats_Pipeline_ADAPT_COLS_fu_274_adapt_runs_ce0;
    end else if ((1'b1 == ap_CS_fsm_state39)) begin
        adapt_runs_ce0 = grp_compute_adapt_stats_Pipeline_INIT_ADAPT_fu_262_adapt_runs_ce0;
    end else begin
        adapt_runs_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state41)) begin
        adapt_runs_ce1 = grp_compute_adapt_stats_Pipeline_ADAPT_COLS_fu_274_adapt_runs_ce1;
    end else begin
        adapt_runs_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state41)) begin
        adapt_runs_d0 = grp_compute_adapt_stats_Pipeline_ADAPT_COLS_fu_274_adapt_runs_d0;
    end else if ((1'b1 == ap_CS_fsm_state39)) begin
        adapt_runs_d0 = grp_compute_adapt_stats_Pipeline_INIT_ADAPT_fu_262_adapt_runs_d0;
    end else begin
        adapt_runs_d0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state41)) begin
        adapt_runs_we0 = grp_compute_adapt_stats_Pipeline_ADAPT_COLS_fu_274_adapt_runs_we0;
    end else if ((1'b1 == ap_CS_fsm_state39)) begin
        adapt_runs_we0 = grp_compute_adapt_stats_Pipeline_INIT_ADAPT_fu_262_adapt_runs_we0;
    end else begin
        adapt_runs_we0 = 1'b0;
    end
end

assign ap_ST_fsm_state10_blk = 1'b0;

assign ap_ST_fsm_state11_blk = 1'b0;

assign ap_ST_fsm_state12_blk = 1'b0;

assign ap_ST_fsm_state13_blk = 1'b0;

assign ap_ST_fsm_state14_blk = 1'b0;

assign ap_ST_fsm_state15_blk = 1'b0;

assign ap_ST_fsm_state16_blk = 1'b0;

assign ap_ST_fsm_state17_blk = 1'b0;

assign ap_ST_fsm_state18_blk = 1'b0;

assign ap_ST_fsm_state19_blk = 1'b0;

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state20_blk = 1'b0;

assign ap_ST_fsm_state21_blk = 1'b0;

assign ap_ST_fsm_state22_blk = 1'b0;

assign ap_ST_fsm_state23_blk = 1'b0;

assign ap_ST_fsm_state24_blk = 1'b0;

assign ap_ST_fsm_state25_blk = 1'b0;

assign ap_ST_fsm_state26_blk = 1'b0;

assign ap_ST_fsm_state27_blk = 1'b0;

assign ap_ST_fsm_state28_blk = 1'b0;

assign ap_ST_fsm_state29_blk = 1'b0;

always @ (*) begin
    if ((grp_compute_adapt_stats_Pipeline_FIXED_MAX_LOOP_fu_247_ap_done == 1'b0)) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

assign ap_ST_fsm_state30_blk = 1'b0;

assign ap_ST_fsm_state31_blk = 1'b0;

assign ap_ST_fsm_state32_blk = 1'b0;

assign ap_ST_fsm_state33_blk = 1'b0;

assign ap_ST_fsm_state34_blk = 1'b0;

assign ap_ST_fsm_state35_blk = 1'b0;

assign ap_ST_fsm_state36_blk = 1'b0;

assign ap_ST_fsm_state37_blk = 1'b0;

assign ap_ST_fsm_state38_blk = 1'b0;

always @ (*) begin
    if ((grp_compute_adapt_stats_Pipeline_INIT_ADAPT_fu_262_ap_done == 1'b0)) begin
        ap_ST_fsm_state39_blk = 1'b1;
    end else begin
        ap_ST_fsm_state39_blk = 1'b0;
    end
end

assign ap_ST_fsm_state3_blk = 1'b0;

assign ap_ST_fsm_state40_blk = 1'b0;

always @ (*) begin
    if ((grp_compute_adapt_stats_Pipeline_ADAPT_COLS_fu_274_ap_done == 1'b0)) begin
        ap_ST_fsm_state41_blk = 1'b1;
    end else begin
        ap_ST_fsm_state41_blk = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state42_on_subcall_done)) begin
        ap_ST_fsm_state42_blk = 1'b1;
    end else begin
        ap_ST_fsm_state42_blk = 1'b0;
    end
end

assign ap_ST_fsm_state4_blk = 1'b0;

assign ap_ST_fsm_state5_blk = 1'b0;

assign ap_ST_fsm_state6_blk = 1'b0;

assign ap_ST_fsm_state7_blk = 1'b0;

assign ap_ST_fsm_state8_blk = 1'b0;

assign ap_ST_fsm_state9_blk = 1'b0;

always @ (*) begin
    if ((((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)) | ((1'b0 == ap_block_state42_on_subcall_done) & (1'b1 == ap_CS_fsm_state42)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state42) & (or_ln214_3_reg_626 == 1'd0))) begin
        ap_phi_mux_agg_result_adapt_topk_k_0_phi_fu_229_p4 = k_1_reg_683;
    end else begin
        ap_phi_mux_agg_result_adapt_topk_k_0_phi_fu_229_p4 = agg_result_adapt_topk_k_0_reg_225;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state42) & (or_ln214_3_reg_626 == 1'd0))) begin
        ap_phi_mux_agg_result_adapt_topk_sum_0_phi_fu_206_p4 = grp_topk_sum_hist_fu_291_ap_return;
    end else begin
        ap_phi_mux_agg_result_adapt_topk_sum_0_phi_fu_206_p4 = agg_result_adapt_topk_sum_0_reg_202;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state42) & (or_ln214_3_reg_626 == 1'd0))) begin
        ap_phi_mux_agg_result_fixed_max_run_0_phi_fu_195_p4 = grp_compute_adapt_stats_Pipeline_FIXED_MAX_LOOP_fu_247_fixed_max_out;
    end else begin
        ap_phi_mux_agg_result_fixed_max_run_0_phi_fu_195_p4 = agg_result_fixed_max_run_0_reg_191;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state42) & (or_ln214_3_reg_626 == 1'd0))) begin
        ap_phi_mux_agg_result_t_adapt_0_phi_fu_240_p4 = t_adapt_reg_666;
    end else begin
        ap_phi_mux_agg_result_t_adapt_0_phi_fu_240_p4 = agg_result_t_adapt_0_reg_236;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state42) & (or_ln214_3_reg_626 == 1'd0))) begin
        ap_phi_mux_agg_result_valid_0_phi_fu_217_p4 = 1'd1;
    end else begin
        ap_phi_mux_agg_result_valid_0_phi_fu_217_p4 = agg_result_valid_0_reg_213;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state42_on_subcall_done) & (1'b1 == ap_CS_fsm_state42))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state42_on_subcall_done) & (1'b1 == ap_CS_fsm_state42))) begin
        ap_return_0 = ap_phi_mux_agg_result_valid_0_phi_fu_217_p4;
    end else begin
        ap_return_0 = ap_return_0_preg;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state42_on_subcall_done) & (1'b1 == ap_CS_fsm_state42))) begin
        ap_return_1 = ch_cast10_reg_621;
    end else begin
        ap_return_1 = ap_return_1_preg;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state42_on_subcall_done) & (1'b1 == ap_CS_fsm_state42))) begin
        ap_return_2 = ap_phi_mux_agg_result_fixed_max_run_0_phi_fu_195_p4;
    end else begin
        ap_return_2 = ap_return_2_preg;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state42_on_subcall_done) & (1'b1 == ap_CS_fsm_state42))) begin
        ap_return_3 = ap_phi_mux_agg_result_adapt_topk_sum_0_phi_fu_206_p4;
    end else begin
        ap_return_3 = ap_return_3_preg;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state42_on_subcall_done) & (1'b1 == ap_CS_fsm_state42))) begin
        ap_return_4 = agg_result_adapt_topk_k_0_cast_fu_552_p1;
    end else begin
        ap_return_4 = ap_return_4_preg;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state42_on_subcall_done) & (1'b1 == ap_CS_fsm_state42))) begin
        ap_return_5 = agg_result_t_adapt_0_cast_fu_548_p1;
    end else begin
        ap_return_5 = ap_return_5_preg;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state41)) begin
        cur_1_address0 = grp_compute_adapt_stats_Pipeline_ADAPT_COLS_fu_274_cur_1_address0;
    end else if ((1'b1 == ap_CS_fsm_state39)) begin
        cur_1_address0 = grp_compute_adapt_stats_Pipeline_INIT_ADAPT_fu_262_cur_1_address0;
    end else begin
        cur_1_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state41)) begin
        cur_1_ce0 = grp_compute_adapt_stats_Pipeline_ADAPT_COLS_fu_274_cur_1_ce0;
    end else if ((1'b1 == ap_CS_fsm_state39)) begin
        cur_1_ce0 = grp_compute_adapt_stats_Pipeline_INIT_ADAPT_fu_262_cur_1_ce0;
    end else begin
        cur_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state41)) begin
        cur_1_ce1 = grp_compute_adapt_stats_Pipeline_ADAPT_COLS_fu_274_cur_1_ce1;
    end else begin
        cur_1_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state41)) begin
        cur_1_d0 = grp_compute_adapt_stats_Pipeline_ADAPT_COLS_fu_274_cur_1_d0;
    end else if ((1'b1 == ap_CS_fsm_state39)) begin
        cur_1_d0 = grp_compute_adapt_stats_Pipeline_INIT_ADAPT_fu_262_cur_1_d0;
    end else begin
        cur_1_d0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state41)) begin
        cur_1_we0 = grp_compute_adapt_stats_Pipeline_ADAPT_COLS_fu_274_cur_1_we0;
    end else if ((1'b1 == ap_CS_fsm_state39)) begin
        cur_1_we0 = grp_compute_adapt_stats_Pipeline_INIT_ADAPT_fu_262_cur_1_we0;
    end else begin
        cur_1_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state41)) begin
        cur_1_we1 = grp_compute_adapt_stats_Pipeline_ADAPT_COLS_fu_274_cur_1_we1;
    end else begin
        cur_1_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state41)) begin
        cur_2_address0 = grp_compute_adapt_stats_Pipeline_ADAPT_COLS_fu_274_cur_2_address0;
    end else if ((1'b1 == ap_CS_fsm_state39)) begin
        cur_2_address0 = grp_compute_adapt_stats_Pipeline_INIT_ADAPT_fu_262_cur_2_address0;
    end else begin
        cur_2_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state41)) begin
        cur_2_ce0 = grp_compute_adapt_stats_Pipeline_ADAPT_COLS_fu_274_cur_2_ce0;
    end else if ((1'b1 == ap_CS_fsm_state39)) begin
        cur_2_ce0 = grp_compute_adapt_stats_Pipeline_INIT_ADAPT_fu_262_cur_2_ce0;
    end else begin
        cur_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state41)) begin
        cur_2_ce1 = grp_compute_adapt_stats_Pipeline_ADAPT_COLS_fu_274_cur_2_ce1;
    end else begin
        cur_2_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state41)) begin
        cur_2_d0 = grp_compute_adapt_stats_Pipeline_ADAPT_COLS_fu_274_cur_2_d0;
    end else if ((1'b1 == ap_CS_fsm_state39)) begin
        cur_2_d0 = grp_compute_adapt_stats_Pipeline_INIT_ADAPT_fu_262_cur_2_d0;
    end else begin
        cur_2_d0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state41)) begin
        cur_2_we0 = grp_compute_adapt_stats_Pipeline_ADAPT_COLS_fu_274_cur_2_we0;
    end else if ((1'b1 == ap_CS_fsm_state39)) begin
        cur_2_we0 = grp_compute_adapt_stats_Pipeline_INIT_ADAPT_fu_262_cur_2_we0;
    end else begin
        cur_2_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state41)) begin
        cur_2_we1 = grp_compute_adapt_stats_Pipeline_ADAPT_COLS_fu_274_cur_2_we1;
    end else begin
        cur_2_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state41)) begin
        cur_3_address0 = grp_compute_adapt_stats_Pipeline_ADAPT_COLS_fu_274_cur_3_address0;
    end else if ((1'b1 == ap_CS_fsm_state39)) begin
        cur_3_address0 = grp_compute_adapt_stats_Pipeline_INIT_ADAPT_fu_262_cur_3_address0;
    end else begin
        cur_3_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state41)) begin
        cur_3_ce0 = grp_compute_adapt_stats_Pipeline_ADAPT_COLS_fu_274_cur_3_ce0;
    end else if ((1'b1 == ap_CS_fsm_state39)) begin
        cur_3_ce0 = grp_compute_adapt_stats_Pipeline_INIT_ADAPT_fu_262_cur_3_ce0;
    end else begin
        cur_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state41)) begin
        cur_3_ce1 = grp_compute_adapt_stats_Pipeline_ADAPT_COLS_fu_274_cur_3_ce1;
    end else begin
        cur_3_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state41)) begin
        cur_3_d0 = grp_compute_adapt_stats_Pipeline_ADAPT_COLS_fu_274_cur_3_d0;
    end else if ((1'b1 == ap_CS_fsm_state39)) begin
        cur_3_d0 = grp_compute_adapt_stats_Pipeline_INIT_ADAPT_fu_262_cur_3_d0;
    end else begin
        cur_3_d0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state41)) begin
        cur_3_we0 = grp_compute_adapt_stats_Pipeline_ADAPT_COLS_fu_274_cur_3_we0;
    end else if ((1'b1 == ap_CS_fsm_state39)) begin
        cur_3_we0 = grp_compute_adapt_stats_Pipeline_INIT_ADAPT_fu_262_cur_3_we0;
    end else begin
        cur_3_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state41)) begin
        cur_3_we1 = grp_compute_adapt_stats_Pipeline_ADAPT_COLS_fu_274_cur_3_we1;
    end else begin
        cur_3_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state41)) begin
        cur_address0 = grp_compute_adapt_stats_Pipeline_ADAPT_COLS_fu_274_cur_address0;
    end else if ((1'b1 == ap_CS_fsm_state39)) begin
        cur_address0 = grp_compute_adapt_stats_Pipeline_INIT_ADAPT_fu_262_cur_address0;
    end else begin
        cur_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state41)) begin
        cur_ce0 = grp_compute_adapt_stats_Pipeline_ADAPT_COLS_fu_274_cur_ce0;
    end else if ((1'b1 == ap_CS_fsm_state39)) begin
        cur_ce0 = grp_compute_adapt_stats_Pipeline_INIT_ADAPT_fu_262_cur_ce0;
    end else begin
        cur_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state41)) begin
        cur_ce1 = grp_compute_adapt_stats_Pipeline_ADAPT_COLS_fu_274_cur_ce1;
    end else begin
        cur_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state41)) begin
        cur_d0 = grp_compute_adapt_stats_Pipeline_ADAPT_COLS_fu_274_cur_d0;
    end else if ((1'b1 == ap_CS_fsm_state39)) begin
        cur_d0 = grp_compute_adapt_stats_Pipeline_INIT_ADAPT_fu_262_cur_d0;
    end else begin
        cur_d0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state41)) begin
        cur_we0 = grp_compute_adapt_stats_Pipeline_ADAPT_COLS_fu_274_cur_we0;
    end else if ((1'b1 == ap_CS_fsm_state39)) begin
        cur_we0 = grp_compute_adapt_stats_Pipeline_INIT_ADAPT_fu_262_cur_we0;
    end else begin
        cur_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state41)) begin
        cur_we1 = grp_compute_adapt_stats_Pipeline_ADAPT_COLS_fu_274_cur_we1;
    end else begin
        cur_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state3) & (icmp_ln82_fu_385_p2 == 1'd0))) begin
        grp_fu_408_ap_start = 1'b1;
    end else begin
        grp_fu_408_ap_start = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (or_ln214_3_fu_367_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state42;
            end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (or_ln214_3_fu_367_p2 == 1'd0))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((grp_compute_adapt_stats_Pipeline_FIXED_MAX_LOOP_fu_247_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            if (((1'b1 == ap_CS_fsm_state3) & (icmp_ln82_fu_385_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state38;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state11;
        end
        ap_ST_fsm_state11 : begin
            ap_NS_fsm = ap_ST_fsm_state12;
        end
        ap_ST_fsm_state12 : begin
            ap_NS_fsm = ap_ST_fsm_state13;
        end
        ap_ST_fsm_state13 : begin
            ap_NS_fsm = ap_ST_fsm_state14;
        end
        ap_ST_fsm_state14 : begin
            ap_NS_fsm = ap_ST_fsm_state15;
        end
        ap_ST_fsm_state15 : begin
            ap_NS_fsm = ap_ST_fsm_state16;
        end
        ap_ST_fsm_state16 : begin
            ap_NS_fsm = ap_ST_fsm_state17;
        end
        ap_ST_fsm_state17 : begin
            ap_NS_fsm = ap_ST_fsm_state18;
        end
        ap_ST_fsm_state18 : begin
            ap_NS_fsm = ap_ST_fsm_state19;
        end
        ap_ST_fsm_state19 : begin
            ap_NS_fsm = ap_ST_fsm_state20;
        end
        ap_ST_fsm_state20 : begin
            ap_NS_fsm = ap_ST_fsm_state21;
        end
        ap_ST_fsm_state21 : begin
            ap_NS_fsm = ap_ST_fsm_state22;
        end
        ap_ST_fsm_state22 : begin
            ap_NS_fsm = ap_ST_fsm_state23;
        end
        ap_ST_fsm_state23 : begin
            ap_NS_fsm = ap_ST_fsm_state24;
        end
        ap_ST_fsm_state24 : begin
            ap_NS_fsm = ap_ST_fsm_state25;
        end
        ap_ST_fsm_state25 : begin
            ap_NS_fsm = ap_ST_fsm_state26;
        end
        ap_ST_fsm_state26 : begin
            ap_NS_fsm = ap_ST_fsm_state27;
        end
        ap_ST_fsm_state27 : begin
            ap_NS_fsm = ap_ST_fsm_state28;
        end
        ap_ST_fsm_state28 : begin
            ap_NS_fsm = ap_ST_fsm_state29;
        end
        ap_ST_fsm_state29 : begin
            ap_NS_fsm = ap_ST_fsm_state30;
        end
        ap_ST_fsm_state30 : begin
            ap_NS_fsm = ap_ST_fsm_state31;
        end
        ap_ST_fsm_state31 : begin
            ap_NS_fsm = ap_ST_fsm_state32;
        end
        ap_ST_fsm_state32 : begin
            ap_NS_fsm = ap_ST_fsm_state33;
        end
        ap_ST_fsm_state33 : begin
            ap_NS_fsm = ap_ST_fsm_state34;
        end
        ap_ST_fsm_state34 : begin
            ap_NS_fsm = ap_ST_fsm_state35;
        end
        ap_ST_fsm_state35 : begin
            ap_NS_fsm = ap_ST_fsm_state36;
        end
        ap_ST_fsm_state36 : begin
            ap_NS_fsm = ap_ST_fsm_state37;
        end
        ap_ST_fsm_state37 : begin
            ap_NS_fsm = ap_ST_fsm_state38;
        end
        ap_ST_fsm_state38 : begin
            ap_NS_fsm = ap_ST_fsm_state39;
        end
        ap_ST_fsm_state39 : begin
            if (((grp_compute_adapt_stats_Pipeline_INIT_ADAPT_fu_262_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state39))) begin
                ap_NS_fsm = ap_ST_fsm_state40;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state39;
            end
        end
        ap_ST_fsm_state40 : begin
            if (((icmp_ln241_fu_508_p2 == 1'd1) & (icmp_ln240_fu_487_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state40))) begin
                ap_NS_fsm = ap_ST_fsm_state41;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state42;
            end
        end
        ap_ST_fsm_state41 : begin
            if (((grp_compute_adapt_stats_Pipeline_ADAPT_COLS_fu_274_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state41))) begin
                ap_NS_fsm = ap_ST_fsm_state40;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state41;
            end
        end
        ap_ST_fsm_state42 : begin
            if (((1'b0 == ap_block_state42_on_subcall_done) & (1'b1 == ap_CS_fsm_state42))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state42;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign adapt_offset_cast_fu_303_p1 = adapt_offset;

assign add_ln240_fu_493_p2 = (y_fu_146 + 7'd1);

assign add_ln256_fu_518_p2 = (cw + 8'd3);

assign agg_result_adapt_topk_k_0_cast_fu_552_p1 = ap_phi_mux_agg_result_adapt_topk_k_0_phi_fu_229_p4;

assign agg_result_t_adapt_0_cast_fu_548_p1 = ap_phi_mux_agg_result_t_adapt_0_phi_fu_240_p4;

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state38 = ap_CS_fsm[32'd37];

assign ap_CS_fsm_state39 = ap_CS_fsm[32'd38];

assign ap_CS_fsm_state40 = ap_CS_fsm[32'd39];

assign ap_CS_fsm_state41 = ap_CS_fsm[32'd40];

assign ap_CS_fsm_state42 = ap_CS_fsm[32'd41];

always @ (*) begin
    ap_block_state42_on_subcall_done = ((grp_topk_sum_hist_fu_291_ap_done == 1'b0) & (or_ln214_3_reg_626 == 1'd0));
end

assign ch_cast10_fu_307_p1 = ch;

assign count_fu_373_p0 = count_fu_373_p00;

assign count_fu_373_p00 = ch;

assign count_fu_373_p1 = count_fu_373_p10;

assign count_fu_373_p10 = cw;

assign div_i6_fu_390_p4 = {{count_reg_630[14:1]}};

assign fixed_runs_0_address0 = grp_compute_adapt_stats_Pipeline_FIXED_MAX_LOOP_fu_247_fixed_runs_0_address0;

assign fixed_runs_0_ce0 = grp_compute_adapt_stats_Pipeline_FIXED_MAX_LOOP_fu_247_fixed_runs_0_ce0;

assign fixed_runs_1_address0 = grp_compute_adapt_stats_Pipeline_FIXED_MAX_LOOP_fu_247_fixed_runs_1_address0;

assign fixed_runs_1_ce0 = grp_compute_adapt_stats_Pipeline_FIXED_MAX_LOOP_fu_247_fixed_runs_1_ce0;

assign fixed_runs_2_address0 = grp_compute_adapt_stats_Pipeline_FIXED_MAX_LOOP_fu_247_fixed_runs_2_address0;

assign fixed_runs_2_ce0 = grp_compute_adapt_stats_Pipeline_FIXED_MAX_LOOP_fu_247_fixed_runs_2_ce0;

assign fixed_runs_3_address0 = grp_compute_adapt_stats_Pipeline_FIXED_MAX_LOOP_fu_247_fixed_runs_3_address0;

assign fixed_runs_3_ce0 = grp_compute_adapt_stats_Pipeline_FIXED_MAX_LOOP_fu_247_fixed_runs_3_ce0;

assign grp_compute_adapt_stats_Pipeline_ADAPT_COLS_fu_274_ap_start = grp_compute_adapt_stats_Pipeline_ADAPT_COLS_fu_274_ap_start_reg;

assign grp_compute_adapt_stats_Pipeline_FIXED_MAX_LOOP_fu_247_ap_start = grp_compute_adapt_stats_Pipeline_FIXED_MAX_LOOP_fu_247_ap_start_reg;

assign grp_compute_adapt_stats_Pipeline_INIT_ADAPT_fu_262_ap_start = grp_compute_adapt_stats_Pipeline_INIT_ADAPT_fu_262_ap_start_reg;

assign grp_fu_408_p0 = (zext_ln83_fu_399_p1 + sum_center_val);

assign grp_fu_408_p1 = grp_fu_408_p10;

assign grp_fu_408_p10 = count_reg_630;

assign grp_topk_sum_hist_fu_291_ap_start = grp_topk_sum_hist_fu_291_ap_start_reg;

assign icmp_ln214_1_fu_331_p2 = ((ch == 7'd0) ? 1'b1 : 1'b0);

assign icmp_ln214_2_fu_337_p2 = ((cw > 8'd128) ? 1'b1 : 1'b0);

assign icmp_ln214_3_fu_343_p2 = ((ch > 7'd64) ? 1'b1 : 1'b0);

assign icmp_ln214_fu_325_p2 = ((cw == 8'd0) ? 1'b1 : 1'b0);

assign icmp_ln240_fu_487_p2 = ((y_fu_146 == 7'd64) ? 1'b1 : 1'b0);

assign icmp_ln241_fu_508_p2 = ((y_fu_146 < ch) ? 1'b1 : 1'b0);

assign icmp_ln257_fu_533_p2 = ((k_fu_523_p4 == 6'd0) ? 1'b1 : 1'b0);

assign icmp_ln71_fu_438_p2 = (($signed(tmp_fu_428_p4) > $signed(24'd0)) ? 1'b1 : 1'b0);

assign icmp_ln82_fu_385_p2 = ((count_reg_630 == 15'd0) ? 1'b1 : 1'b0);

assign k_1_fu_539_p3 = ((icmp_ln257_fu_533_p2[0:0] == 1'b1) ? 6'd1 : k_fu_523_p4);

assign k_fu_523_p4 = {{add_ln256_fu_518_p2[7:2]}};

assign or_ln214_1_fu_355_p2 = (icmp_ln214_3_fu_343_p2 | icmp_ln214_2_fu_337_p2);

assign or_ln214_2_fu_361_p2 = (or_ln214_1_fu_355_p2 | icmp_ln214_1_fu_331_p2);

assign or_ln214_3_fu_367_p2 = (or_ln214_fu_349_p2 | or_ln214_2_fu_361_p2);

assign or_ln214_fu_349_p2 = (xor_ln214_fu_319_p2 | icmp_ln214_fu_325_p2);

assign or_ln70_fu_466_p2 = (tmp_44_fu_444_p3 | icmp_ln71_fu_438_p2);

assign pix_buf_address0 = grp_compute_adapt_stats_Pipeline_ADAPT_COLS_fu_274_pix_buf_address0;

assign pix_buf_ce0 = grp_compute_adapt_stats_Pipeline_ADAPT_COLS_fu_274_pix_buf_ce0;

assign select_ln70_fu_458_p3 = ((xor_ln70_fu_452_p2[0:0] == 1'b1) ? 8'd255 : 8'd0);

assign sub_ln225_fu_419_p2 = (mean_center_reg_180 - adapt_offset_cast_reg_616);

assign t_adapt_fu_472_p3 = ((or_ln70_fu_466_p2[0:0] == 1'b1) ? select_ln70_fu_458_p3 : trunc_ln71_fu_424_p1);

assign tmp_44_fu_444_p3 = sub_ln225_fu_419_p2[32'd31];

assign tmp_fu_428_p4 = {{sub_ln225_fu_419_p2[31:8]}};

assign tmp_s_fu_499_p3 = {{trunc_ln240_fu_483_p1}, {7'd0}};

assign trunc_ln240_fu_483_p1 = y_fu_146[5:0];

assign trunc_ln71_fu_424_p1 = sub_ln225_fu_419_p2[7:0];

assign xor_ln214_fu_319_p2 = (valid ^ 1'd1);

assign xor_ln70_fu_452_p2 = (tmp_44_fu_444_p3 ^ 1'd1);

assign zext_ln83_fu_399_p1 = div_i6_fu_390_p4;

always @ (posedge ap_clk) begin
    adapt_offset_cast_reg_616[31:8] <= 24'b000000000000000000000000;
    ch_cast10_reg_621[31:7] <= 25'b0000000000000000000000000;
    tmp_s_reg_675[6:0] <= 7'b0000000;
    ap_return_1_preg[31:7] <= 25'b0000000000000000000000000;
    ap_return_4_preg[31:6] <= 26'b00000000000000000000000000;
    ap_return_5_preg[31:8] <= 24'b000000000000000000000000;
end

endmodule //eye_feature_compute_adapt_stats
