// ==============================================================
// Generated by Vitis HLS v2023.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module eye_feature_eye_feature_Pipeline_FRAME_X (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        in_stream_TVALID,
        c_cx0,
        ex1_1,
        c_valid_2,
        rev84,
        icmp_ln523_1,
        in_stream_TDATA,
        in_stream_TREADY,
        in_stream_TKEEP,
        in_stream_TSTRB,
        in_stream_TLAST,
        pixel_format,
        cmp6_i,
        c_cx0_3,
        ex0_1,
        c_valid_3,
        rev,
        icmp_ln522_1,
        frame_width,
        empty_55,
        zext_ln540_1,
        hist0_address0,
        hist0_ce0,
        hist0_we0,
        hist0_d0,
        hist0_q0,
        hist0_1_address0,
        hist0_1_ce0,
        hist0_1_we0,
        hist0_1_d0,
        hist0_1_q0,
        hist0_2_address0,
        hist0_2_ce0,
        hist0_2_we0,
        hist0_2_d0,
        hist0_2_q0,
        hist0_3_address0,
        hist0_3_ce0,
        hist0_3_we0,
        hist0_3_d0,
        hist0_3_q0,
        empty,
        zext_ln546_1,
        hist1_address0,
        hist1_ce0,
        hist1_we0,
        hist1_d0,
        hist1_q0,
        hist1_1_address0,
        hist1_1_ce0,
        hist1_1_we0,
        hist1_1_d0,
        hist1_1_q0,
        hist1_2_address0,
        hist1_2_ce0,
        hist1_2_we0,
        hist1_2_d0,
        hist1_2_q0,
        hist1_3_address0,
        hist1_3_ce0,
        hist1_3_we0,
        hist1_3_d0,
        hist1_3_q0,
        pix0_address1,
        pix0_ce1,
        pix0_we1,
        pix0_d1,
        pix1_address1,
        pix1_ce1,
        pix1_we1,
        pix1_d1
);

parameter    ap_ST_fsm_pp0_stage0 = 2'd1;
parameter    ap_ST_fsm_pp0_stage1 = 2'd2;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input   in_stream_TVALID;
input  [31:0] c_cx0;
input  [31:0] ex1_1;
input  [0:0] c_valid_2;
input  [0:0] rev84;
input  [0:0] icmp_ln523_1;
input  [31:0] in_stream_TDATA;
output   in_stream_TREADY;
input  [3:0] in_stream_TKEEP;
input  [3:0] in_stream_TSTRB;
input  [0:0] in_stream_TLAST;
input  [31:0] pixel_format;
input  [0:0] cmp6_i;
input  [31:0] c_cx0_3;
input  [31:0] ex0_1;
input  [0:0] c_valid_3;
input  [0:0] rev;
input  [0:0] icmp_ln522_1;
input  [31:0] frame_width;
input  [12:0] empty_55;
input  [12:0] zext_ln540_1;
output  [3:0] hist0_address0;
output   hist0_ce0;
output   hist0_we0;
output  [15:0] hist0_d0;
input  [15:0] hist0_q0;
output  [3:0] hist0_1_address0;
output   hist0_1_ce0;
output   hist0_1_we0;
output  [15:0] hist0_1_d0;
input  [15:0] hist0_1_q0;
output  [3:0] hist0_2_address0;
output   hist0_2_ce0;
output   hist0_2_we0;
output  [15:0] hist0_2_d0;
input  [15:0] hist0_2_q0;
output  [3:0] hist0_3_address0;
output   hist0_3_ce0;
output   hist0_3_we0;
output  [15:0] hist0_3_d0;
input  [15:0] hist0_3_q0;
input  [12:0] empty;
input  [12:0] zext_ln546_1;
output  [3:0] hist1_address0;
output   hist1_ce0;
output   hist1_we0;
output  [15:0] hist1_d0;
input  [15:0] hist1_q0;
output  [3:0] hist1_1_address0;
output   hist1_1_ce0;
output   hist1_1_we0;
output  [15:0] hist1_1_d0;
input  [15:0] hist1_1_q0;
output  [3:0] hist1_2_address0;
output   hist1_2_ce0;
output   hist1_2_we0;
output  [15:0] hist1_2_d0;
input  [15:0] hist1_2_q0;
output  [3:0] hist1_3_address0;
output   hist1_3_ce0;
output   hist1_3_we0;
output  [15:0] hist1_3_d0;
input  [15:0] hist1_3_q0;
output  [12:0] pix0_address1;
output   pix0_ce1;
output   pix0_we1;
output  [7:0] pix0_d1;
output  [12:0] pix1_address1;
output   pix1_ce1;
output   pix1_we1;
output  [7:0] pix1_d1;

reg ap_idle;
reg in_stream_TREADY;
reg[3:0] hist0_address0;
reg hist0_ce0;
reg hist0_we0;
reg[3:0] hist0_1_address0;
reg hist0_1_ce0;
reg hist0_1_we0;
reg[3:0] hist0_2_address0;
reg hist0_2_ce0;
reg hist0_2_we0;
reg[3:0] hist0_3_address0;
reg hist0_3_ce0;
reg hist0_3_we0;
reg[3:0] hist1_address0;
reg hist1_ce0;
reg hist1_we0;
reg[3:0] hist1_1_address0;
reg hist1_1_ce0;
reg hist1_1_we0;
reg[3:0] hist1_2_address0;
reg hist1_2_ce0;
reg hist1_2_we0;
reg[3:0] hist1_3_address0;
reg hist1_3_ce0;
reg hist1_3_we0;
reg pix0_ce1;
reg pix0_we1;
reg pix1_ce1;
reg pix1_we1;

(* fsm_encoding = "none" *) reg   [1:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_idle_pp0;
wire    ap_CS_fsm_pp0_stage1;
reg   [0:0] icmp_ln532_reg_1037;
reg   [0:0] icmp_ln534_reg_1047;
reg    ap_predicate_op67_read_state2;
reg    ap_block_state2_pp0_stage1_iter0;
reg    ap_block_pp0_stage1_subdone;
reg    ap_condition_exit_pp0_iter0_stage1;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    in_stream_TDATA_blk_n;
wire    ap_block_pp0_stage1;
wire    ap_block_pp0_stage0_11001;
wire   [0:0] cmp6_i_read_read_fu_252_p2;
wire   [0:0] icmp_ln532_fu_452_p2;
reg   [0:0] icmp_ln532_reg_1037_pp0_iter1_reg;
wire   [12:0] trunc_ln532_fu_464_p1;
reg   [12:0] trunc_ln532_reg_1041;
reg   [12:0] trunc_ln532_reg_1041_pp0_iter1_reg;
reg   [12:0] trunc_ln532_reg_1041_pp0_iter2_reg;
wire   [0:0] icmp_ln534_fu_472_p2;
reg   [0:0] icmp_ln534_reg_1047_pp0_iter1_reg;
wire   [0:0] icmp_ln124_fu_478_p2;
reg   [0:0] icmp_ln124_reg_1051;
reg   [0:0] icmp_ln124_reg_1051_pp0_iter1_reg;
reg   [0:0] icmp_ln124_reg_1051_pp0_iter2_reg;
wire   [0:0] icmp_ln124_1_fu_484_p2;
reg   [0:0] icmp_ln124_1_reg_1056;
reg   [0:0] icmp_ln124_1_reg_1056_pp0_iter1_reg;
reg   [0:0] icmp_ln124_1_reg_1056_pp0_iter2_reg;
wire   [0:0] and_ln538_1_fu_526_p2;
reg   [0:0] and_ln538_1_reg_1061;
reg   [0:0] and_ln538_1_reg_1061_pp0_iter1_reg;
reg   [0:0] and_ln538_1_reg_1061_pp0_iter2_reg;
wire   [0:0] and_ln544_1_fu_568_p2;
reg   [0:0] and_ln544_1_reg_1065;
reg   [0:0] and_ln544_1_reg_1065_pp0_iter1_reg;
reg   [0:0] and_ln544_1_reg_1065_pp0_iter2_reg;
wire   [7:0] gray_7_fu_583_p1;
reg   [7:0] gray_7_reg_1069;
reg    ap_block_pp0_stage1_11001;
reg   [7:0] gray_7_reg_1069_pp0_iter1_reg;
reg   [2:0] lshr_ln4_reg_1074;
reg   [4:0] tmp_s_reg_1079;
wire   [7:0] g_field_fu_627_p3;
reg   [7:0] g_field_reg_1084;
reg   [7:0] g_field_reg_1084_pp0_iter1_reg;
reg   [2:0] lshr_ln107_1_reg_1089;
wire   [4:0] trunc_ln107_fu_645_p1;
reg   [4:0] trunc_ln107_reg_1094;
reg   [7:0] g_reg_1104;
wire   [7:0] r_field_fu_681_p3;
reg   [7:0] r_field_reg_1119;
wire   [15:0] mul_ln118_2_fu_707_p2;
wire   [15:0] mul_ln118_5_fu_713_p2;
wire   [15:0] grp_fu_962_p3;
reg   [15:0] add_ln118_reg_1144;
wire   [12:0] grp_fu_970_p3;
reg   [12:0] add_ln118_1_reg_1149;
wire   [15:0] grp_fu_978_p3;
reg   [15:0] add_ln118_3_reg_1154;
wire   [15:0] mul_ln118_7_fu_722_p2;
reg   [1:0] trunc_ln_reg_1164;
reg   [3:0] hist0_addr_reg_1169;
reg   [3:0] hist0_1_addr_reg_1174;
reg   [3:0] hist0_2_addr_reg_1179;
reg   [3:0] hist0_3_addr_reg_1184;
reg   [1:0] trunc_ln1_reg_1189;
reg   [3:0] hist1_addr_reg_1194;
reg   [3:0] hist1_1_addr_reg_1199;
reg   [3:0] hist1_2_addr_reg_1204;
reg   [3:0] hist1_3_addr_reg_1209;
reg    ap_enable_reg_pp0_iter0_reg;
wire    ap_block_pp0_stage0_subdone;
wire   [63:0] zext_ln540_fu_821_p1;
wire   [63:0] zext_ln541_fu_846_p1;
wire   [63:0] zext_ln546_fu_863_p1;
wire   [63:0] zext_ln547_fu_888_p1;
reg   [30:0] x_fu_188;
wire   [30:0] add_ln532_fu_458_p2;
wire    ap_loop_init;
reg   [30:0] ap_sig_allocacmp_x_2;
wire    ap_block_pp0_stage0;
wire   [7:0] gray_6_fu_802_p3;
wire   [15:0] add_ln542_fu_919_p2;
wire   [15:0] add_ln548_fu_952_p2;
wire   [31:0] zext_ln532_fu_468_p1;
wire   [0:0] icmp_ln538_fu_490_p2;
wire   [0:0] and_ln538_fu_508_p2;
wire   [0:0] icmp_ln538_1_fu_502_p2;
wire   [0:0] and_ln538_2_fu_514_p2;
wire   [0:0] and_ln538_3_fu_520_p2;
wire   [0:0] xor_ln538_fu_496_p2;
wire   [0:0] icmp_ln544_fu_532_p2;
wire   [0:0] and_ln544_fu_550_p2;
wire   [0:0] icmp_ln544_1_fu_544_p2;
wire   [0:0] and_ln544_2_fu_556_p2;
wire   [0:0] and_ln544_3_fu_562_p2;
wire   [0:0] xor_ln544_fu_538_p2;
wire   [5:0] tmp_1_fu_617_p4;
wire   [1:0] lshr_ln5_fu_607_p4;
wire   [7:0] r_fu_653_p4;
wire   [7:0] b_field_fu_687_p3;
wire   [7:0] mul_ln118_2_fu_707_p0;
wire   [8:0] mul_ln118_2_fu_707_p1;
wire   [7:0] mul_ln118_5_fu_713_p0;
wire   [8:0] mul_ln118_5_fu_713_p1;
wire   [7:0] mul_ln118_7_fu_722_p0;
wire   [8:0] mul_ln118_7_fu_722_p1;
wire   [15:0] zext_ln118_9_fu_728_p1;
(* use_dsp48 = "no" *) wire   [15:0] y_fu_731_p2;
wire   [12:0] grp_fu_986_p3;
wire   [15:0] zext_ln118_11_fu_746_p1;
(* use_dsp48 = "no" *) wire   [15:0] y_1_fu_749_p2;
wire   [15:0] grp_fu_995_p3;
(* use_dsp48 = "no" *) wire   [15:0] y_2_fu_764_p2;
wire   [7:0] gray_fu_736_p4;
wire   [7:0] gray_2_fu_754_p4;
wire   [7:0] gray_4_fu_779_p3;
wire   [0:0] xor_ln124_fu_792_p2;
wire   [0:0] and_ln124_fu_797_p2;
wire   [7:0] gray_3_fu_769_p4;
wire   [7:0] gray_5_fu_785_p3;
wire   [12:0] sub_ln539_fu_812_p2;
wire   [12:0] add_ln540_fu_816_p2;
wire   [3:0] trunc_ln541_1_fu_836_p4;
wire   [12:0] sub_ln545_fu_854_p2;
wire   [12:0] add_ln546_fu_858_p2;
wire   [3:0] trunc_ln547_1_fu_878_p4;
wire   [15:0] tmp_fu_896_p9;
wire   [15:0] tmp_fu_896_p11;
wire   [15:0] tmp_3_fu_929_p9;
wire   [15:0] tmp_3_fu_929_p11;
wire   [7:0] grp_fu_962_p0;
wire   [6:0] grp_fu_962_p1;
wire   [7:0] grp_fu_970_p0;
wire   [4:0] grp_fu_970_p1;
wire   [7:0] grp_fu_970_p2;
wire   [7:0] grp_fu_978_p0;
wire   [6:0] grp_fu_978_p1;
wire   [7:0] grp_fu_986_p0;
wire   [4:0] grp_fu_986_p1;
wire   [7:0] grp_fu_986_p2;
wire   [7:0] grp_fu_995_p0;
wire   [6:0] grp_fu_995_p1;
reg    grp_fu_962_ce;
reg    grp_fu_970_ce;
reg    grp_fu_978_ce;
reg    grp_fu_986_ce;
reg    grp_fu_995_ce;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_condition_exit_pp0_iter2_stage0;
reg    ap_idle_pp0_0to1;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg   [1:0] ap_NS_fsm;
reg    ap_idle_pp0_1to3;
reg    ap_done_pending_pp0;
wire    ap_enable_pp0;
wire    ap_start_int;
wire   [14:0] grp_fu_962_p00;
wire   [12:0] grp_fu_970_p00;
wire   [14:0] grp_fu_978_p00;
wire   [12:0] grp_fu_986_p00;
wire   [14:0] grp_fu_995_p00;
wire   [15:0] mul_ln118_2_fu_707_p00;
wire   [15:0] mul_ln118_5_fu_713_p00;
wire   [15:0] mul_ln118_7_fu_722_p00;
reg    ap_condition_865;
wire   [1:0] tmp_fu_896_p1;
wire   [1:0] tmp_fu_896_p3;
wire  signed [1:0] tmp_fu_896_p5;
wire  signed [1:0] tmp_fu_896_p7;
wire   [1:0] tmp_3_fu_929_p1;
wire   [1:0] tmp_3_fu_929_p3;
wire  signed [1:0] tmp_3_fu_929_p5;
wire  signed [1:0] tmp_3_fu_929_p7;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 2'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter0_reg = 1'b0;
#0 x_fu_188 = 31'd0;
#0 ap_done_reg = 1'b0;
end

eye_feature_mul_8ns_9ns_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 9 ),
    .dout_WIDTH( 16 ))
mul_8ns_9ns_16_1_1_U9(
    .din0(mul_ln118_2_fu_707_p0),
    .din1(mul_ln118_2_fu_707_p1),
    .dout(mul_ln118_2_fu_707_p2)
);

eye_feature_mul_8ns_9ns_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 9 ),
    .dout_WIDTH( 16 ))
mul_8ns_9ns_16_1_1_U10(
    .din0(mul_ln118_5_fu_713_p0),
    .din1(mul_ln118_5_fu_713_p1),
    .dout(mul_ln118_5_fu_713_p2)
);

eye_feature_mul_8ns_9ns_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 9 ),
    .dout_WIDTH( 16 ))
mul_8ns_9ns_16_1_1_U11(
    .din0(mul_ln118_7_fu_722_p0),
    .din1(mul_ln118_7_fu_722_p1),
    .dout(mul_ln118_7_fu_722_p2)
);

eye_feature_sparsemux_9_2_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 2'h0 ),
    .din0_WIDTH( 16 ),
    .CASE1( 2'h1 ),
    .din1_WIDTH( 16 ),
    .CASE2( 2'h2 ),
    .din2_WIDTH( 16 ),
    .CASE3( 2'h3 ),
    .din3_WIDTH( 16 ),
    .def_WIDTH( 16 ),
    .sel_WIDTH( 2 ),
    .dout_WIDTH( 16 ))
sparsemux_9_2_16_1_1_U12(
    .din0(hist0_q0),
    .din1(hist0_1_q0),
    .din2(hist0_2_q0),
    .din3(hist0_3_q0),
    .def(tmp_fu_896_p9),
    .sel(trunc_ln_reg_1164),
    .dout(tmp_fu_896_p11)
);

eye_feature_sparsemux_9_2_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 2'h0 ),
    .din0_WIDTH( 16 ),
    .CASE1( 2'h1 ),
    .din1_WIDTH( 16 ),
    .CASE2( 2'h2 ),
    .din2_WIDTH( 16 ),
    .CASE3( 2'h3 ),
    .din3_WIDTH( 16 ),
    .def_WIDTH( 16 ),
    .sel_WIDTH( 2 ),
    .dout_WIDTH( 16 ))
sparsemux_9_2_16_1_1_U13(
    .din0(hist1_q0),
    .din1(hist1_1_q0),
    .din2(hist1_2_q0),
    .din3(hist1_3_q0),
    .def(tmp_3_fu_929_p9),
    .sel(trunc_ln1_reg_1189),
    .dout(tmp_3_fu_929_p11)
);

eye_feature_mac_muladd_8ns_7ns_16ns_16_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 7 ),
    .din2_WIDTH( 16 ),
    .dout_WIDTH( 16 ))
mac_muladd_8ns_7ns_16ns_16_4_1_U14(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_962_p0),
    .din1(grp_fu_962_p1),
    .din2(mul_ln118_2_fu_707_p2),
    .ce(grp_fu_962_ce),
    .dout(grp_fu_962_p3)
);

eye_feature_mac_muladd_8ns_5ns_8ns_13_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 5 ),
    .din2_WIDTH( 8 ),
    .dout_WIDTH( 13 ))
mac_muladd_8ns_5ns_8ns_13_4_1_U15(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_970_p0),
    .din1(grp_fu_970_p1),
    .din2(grp_fu_970_p2),
    .ce(grp_fu_970_ce),
    .dout(grp_fu_970_p3)
);

eye_feature_mac_muladd_8ns_7ns_16ns_16_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 7 ),
    .din2_WIDTH( 16 ),
    .dout_WIDTH( 16 ))
mac_muladd_8ns_7ns_16ns_16_4_1_U16(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_978_p0),
    .din1(grp_fu_978_p1),
    .din2(mul_ln118_5_fu_713_p2),
    .ce(grp_fu_978_ce),
    .dout(grp_fu_978_p3)
);

eye_feature_mac_muladd_8ns_5ns_8ns_13_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 5 ),
    .din2_WIDTH( 8 ),
    .dout_WIDTH( 13 ))
mac_muladd_8ns_5ns_8ns_13_4_1_U17(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_986_p0),
    .din1(grp_fu_986_p1),
    .din2(grp_fu_986_p2),
    .ce(grp_fu_986_ce),
    .dout(grp_fu_986_p3)
);

eye_feature_mac_muladd_8ns_7ns_16ns_16_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 7 ),
    .din2_WIDTH( 16 ),
    .dout_WIDTH( 16 ))
mac_muladd_8ns_7ns_16ns_16_4_1_U18(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_995_p0),
    .din1(grp_fu_995_p1),
    .din2(mul_ln118_7_fu_722_p2),
    .ce(grp_fu_995_ce),
    .dout(grp_fu_995_p3)
);

eye_feature_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage1),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready_pp0_iter2_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
            ap_enable_reg_pp0_iter0_reg <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage1)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter3 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_idle_pp0_0to1 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter2_stage0))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= 1'b0;
    end else if (((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_idle_pp0_0to1 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter2_stage0))) begin
        ap_loop_exit_ready_pp0_iter2_reg <= 1'b0;
    end else if (((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((1'b1 == ap_condition_865)) begin
            x_fu_188 <= add_ln532_fu_458_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            x_fu_188 <= 31'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        add_ln118_1_reg_1149 <= grp_fu_970_p3;
        add_ln118_3_reg_1154 <= grp_fu_978_p3;
        add_ln118_reg_1144 <= grp_fu_962_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        and_ln538_1_reg_1061 <= and_ln538_1_fu_526_p2;
        and_ln538_1_reg_1061_pp0_iter1_reg <= and_ln538_1_reg_1061;
        and_ln538_1_reg_1061_pp0_iter2_reg <= and_ln538_1_reg_1061_pp0_iter1_reg;
        and_ln544_1_reg_1065 <= and_ln544_1_fu_568_p2;
        and_ln544_1_reg_1065_pp0_iter1_reg <= and_ln544_1_reg_1065;
        and_ln544_1_reg_1065_pp0_iter2_reg <= and_ln544_1_reg_1065_pp0_iter1_reg;
        icmp_ln124_1_reg_1056 <= icmp_ln124_1_fu_484_p2;
        icmp_ln124_1_reg_1056_pp0_iter1_reg <= icmp_ln124_1_reg_1056;
        icmp_ln124_1_reg_1056_pp0_iter2_reg <= icmp_ln124_1_reg_1056_pp0_iter1_reg;
        icmp_ln124_reg_1051 <= icmp_ln124_fu_478_p2;
        icmp_ln124_reg_1051_pp0_iter1_reg <= icmp_ln124_reg_1051;
        icmp_ln124_reg_1051_pp0_iter2_reg <= icmp_ln124_reg_1051_pp0_iter1_reg;
        icmp_ln532_reg_1037 <= icmp_ln532_fu_452_p2;
        icmp_ln532_reg_1037_pp0_iter1_reg <= icmp_ln532_reg_1037;
        icmp_ln534_reg_1047 <= icmp_ln534_fu_472_p2;
        icmp_ln534_reg_1047_pp0_iter1_reg <= icmp_ln534_reg_1047;
        r_field_reg_1119 <= r_field_fu_681_p3;
        trunc_ln532_reg_1041 <= trunc_ln532_fu_464_p1;
        trunc_ln532_reg_1041_pp0_iter1_reg <= trunc_ln532_reg_1041;
        trunc_ln532_reg_1041_pp0_iter2_reg <= trunc_ln532_reg_1041_pp0_iter1_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        g_field_reg_1084 <= g_field_fu_627_p3;
        g_field_reg_1084_pp0_iter1_reg <= g_field_reg_1084;
        g_reg_1104 <= {{in_stream_TDATA[15:8]}};
        gray_7_reg_1069 <= gray_7_fu_583_p1;
        gray_7_reg_1069_pp0_iter1_reg <= gray_7_reg_1069;
        hist0_1_addr_reg_1174 <= zext_ln541_fu_846_p1;
        hist0_2_addr_reg_1179 <= zext_ln541_fu_846_p1;
        hist0_3_addr_reg_1184 <= zext_ln541_fu_846_p1;
        hist0_addr_reg_1169 <= zext_ln541_fu_846_p1;
        hist1_1_addr_reg_1199 <= zext_ln547_fu_888_p1;
        hist1_2_addr_reg_1204 <= zext_ln547_fu_888_p1;
        hist1_3_addr_reg_1209 <= zext_ln547_fu_888_p1;
        hist1_addr_reg_1194 <= zext_ln547_fu_888_p1;
        lshr_ln107_1_reg_1089 <= {{in_stream_TDATA[4:2]}};
        lshr_ln4_reg_1074 <= {{in_stream_TDATA[15:13]}};
        tmp_s_reg_1079 <= {{in_stream_TDATA[15:11]}};
        trunc_ln107_reg_1094 <= trunc_ln107_fu_645_p1;
        trunc_ln1_reg_1189 <= {{gray_6_fu_802_p3[3:2]}};
        trunc_ln_reg_1164 <= {{gray_6_fu_802_p3[3:2]}};
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & ((icmp_ln534_reg_1047 == 1'd0) | (icmp_ln532_reg_1037 == 1'd1)))) begin
        ap_condition_exit_pp0_iter0_stage1 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & ((icmp_ln534_reg_1047_pp0_iter1_reg == 1'd0) | (icmp_ln532_reg_1037_pp0_iter1_reg == 1'd1)))) begin
        ap_condition_exit_pp0_iter2_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter2_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter2_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (~((ap_loop_exit_ready_pp0_iter2_reg == 1'b0) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b0) & (ap_loop_exit_ready == 1'b0))) begin
        ap_done_pending_pp0 = 1'b1;
    end else begin
        ap_done_pending_pp0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
        ap_enable_reg_pp0_iter0 = ap_start_int;
    end else begin
        ap_enable_reg_pp0_iter0 = ap_enable_reg_pp0_iter0_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0_0to1 = 1'b1;
    end else begin
        ap_idle_pp0_0to1 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0))) begin
        ap_idle_pp0_1to3 = 1'b1;
    end else begin
        ap_idle_pp0_1to3 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_x_2 = 31'd0;
    end else begin
        ap_sig_allocacmp_x_2 = x_fu_188;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        grp_fu_962_ce = 1'b1;
    end else begin
        grp_fu_962_ce = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        grp_fu_970_ce = 1'b1;
    end else begin
        grp_fu_970_ce = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        grp_fu_978_ce = 1'b1;
    end else begin
        grp_fu_978_ce = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        grp_fu_986_ce = 1'b1;
    end else begin
        grp_fu_986_ce = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        grp_fu_995_ce = 1'b1;
    end else begin
        grp_fu_995_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        hist0_1_address0 = hist0_1_addr_reg_1174;
    end else if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        hist0_1_address0 = zext_ln541_fu_846_p1;
    end else begin
        hist0_1_address0 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        hist0_1_ce0 = 1'b1;
    end else begin
        hist0_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'd1 == and_ln538_1_reg_1061_pp0_iter2_reg) & (ap_enable_reg_pp0_iter3 == 1'b1) & (trunc_ln_reg_1164 == 2'd1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        hist0_1_we0 = 1'b1;
    end else begin
        hist0_1_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        hist0_2_address0 = hist0_2_addr_reg_1179;
    end else if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        hist0_2_address0 = zext_ln541_fu_846_p1;
    end else begin
        hist0_2_address0 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        hist0_2_ce0 = 1'b1;
    end else begin
        hist0_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'd1 == and_ln538_1_reg_1061_pp0_iter2_reg) & (ap_enable_reg_pp0_iter3 == 1'b1) & (trunc_ln_reg_1164 == 2'd2) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        hist0_2_we0 = 1'b1;
    end else begin
        hist0_2_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        hist0_3_address0 = hist0_3_addr_reg_1184;
    end else if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        hist0_3_address0 = zext_ln541_fu_846_p1;
    end else begin
        hist0_3_address0 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        hist0_3_ce0 = 1'b1;
    end else begin
        hist0_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'd1 == and_ln538_1_reg_1061_pp0_iter2_reg) & (ap_enable_reg_pp0_iter3 == 1'b1) & (trunc_ln_reg_1164 == 2'd3) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        hist0_3_we0 = 1'b1;
    end else begin
        hist0_3_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        hist0_address0 = hist0_addr_reg_1169;
    end else if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        hist0_address0 = zext_ln541_fu_846_p1;
    end else begin
        hist0_address0 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        hist0_ce0 = 1'b1;
    end else begin
        hist0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'd1 == and_ln538_1_reg_1061_pp0_iter2_reg) & (ap_enable_reg_pp0_iter3 == 1'b1) & (trunc_ln_reg_1164 == 2'd0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        hist0_we0 = 1'b1;
    end else begin
        hist0_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        hist1_1_address0 = hist1_1_addr_reg_1199;
    end else if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        hist1_1_address0 = zext_ln547_fu_888_p1;
    end else begin
        hist1_1_address0 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        hist1_1_ce0 = 1'b1;
    end else begin
        hist1_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'd1 == and_ln544_1_reg_1065_pp0_iter2_reg) & (ap_enable_reg_pp0_iter3 == 1'b1) & (trunc_ln1_reg_1189 == 2'd1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        hist1_1_we0 = 1'b1;
    end else begin
        hist1_1_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        hist1_2_address0 = hist1_2_addr_reg_1204;
    end else if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        hist1_2_address0 = zext_ln547_fu_888_p1;
    end else begin
        hist1_2_address0 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        hist1_2_ce0 = 1'b1;
    end else begin
        hist1_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'd1 == and_ln544_1_reg_1065_pp0_iter2_reg) & (ap_enable_reg_pp0_iter3 == 1'b1) & (trunc_ln1_reg_1189 == 2'd2) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        hist1_2_we0 = 1'b1;
    end else begin
        hist1_2_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        hist1_3_address0 = hist1_3_addr_reg_1209;
    end else if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        hist1_3_address0 = zext_ln547_fu_888_p1;
    end else begin
        hist1_3_address0 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        hist1_3_ce0 = 1'b1;
    end else begin
        hist1_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'd1 == and_ln544_1_reg_1065_pp0_iter2_reg) & (ap_enable_reg_pp0_iter3 == 1'b1) & (trunc_ln1_reg_1189 == 2'd3) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        hist1_3_we0 = 1'b1;
    end else begin
        hist1_3_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        hist1_address0 = hist1_addr_reg_1194;
    end else if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        hist1_address0 = zext_ln547_fu_888_p1;
    end else begin
        hist1_address0 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        hist1_ce0 = 1'b1;
    end else begin
        hist1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'd1 == and_ln544_1_reg_1065_pp0_iter2_reg) & (ap_enable_reg_pp0_iter3 == 1'b1) & (trunc_ln1_reg_1189 == 2'd0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        hist1_we0 = 1'b1;
    end else begin
        hist1_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1) & (ap_predicate_op67_read_state2 == 1'b1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        in_stream_TDATA_blk_n = in_stream_TVALID;
    end else begin
        in_stream_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_predicate_op67_read_state2 == 1'b1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        in_stream_TREADY = 1'b1;
    end else begin
        in_stream_TREADY = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        pix0_ce1 = 1'b1;
    end else begin
        pix0_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (1'd1 == and_ln538_1_reg_1061_pp0_iter2_reg) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        pix0_we1 = 1'b1;
    end else begin
        pix0_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        pix1_ce1 = 1'b1;
    end else begin
        pix1_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (1'd1 == and_ln544_1_reg_1065_pp0_iter2_reg) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        pix1_we1 = 1'b1;
    end else begin
        pix1_we1 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            if (((ap_idle_pp0_0to1 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter2_stage0))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if ((~((ap_start_int == 1'b0) & (ap_done_pending_pp0 == 1'b0) & (ap_idle_pp0_1to3 == 1'b1)) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_pp0_stage1 : begin
            if ((1'b0 == ap_block_pp0_stage1_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln532_fu_458_p2 = (ap_sig_allocacmp_x_2 + 31'd1);

assign add_ln540_fu_816_p2 = (zext_ln540_1 + sub_ln539_fu_812_p2);

assign add_ln542_fu_919_p2 = (tmp_fu_896_p11 + 16'd1);

assign add_ln546_fu_858_p2 = (zext_ln546_1 + sub_ln545_fu_854_p2);

assign add_ln548_fu_952_p2 = (tmp_3_fu_929_p11 + 16'd1);

assign and_ln124_fu_797_p2 = (xor_ln124_fu_792_p2 & icmp_ln124_1_reg_1056_pp0_iter2_reg);

assign and_ln538_1_fu_526_p2 = (xor_ln538_fu_496_p2 & and_ln538_3_fu_520_p2);

assign and_ln538_2_fu_514_p2 = (icmp_ln522_1 & and_ln538_fu_508_p2);

assign and_ln538_3_fu_520_p2 = (icmp_ln538_1_fu_502_p2 & and_ln538_2_fu_514_p2);

assign and_ln538_fu_508_p2 = (rev & c_valid_3);

assign and_ln544_1_fu_568_p2 = (xor_ln544_fu_538_p2 & and_ln544_3_fu_562_p2);

assign and_ln544_2_fu_556_p2 = (icmp_ln523_1 & and_ln544_fu_550_p2);

assign and_ln544_3_fu_562_p2 = (icmp_ln544_1_fu_544_p2 & and_ln544_2_fu_556_p2);

assign and_ln544_fu_550_p2 = (rev84 & c_valid_2);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_pp0_stage1 = ap_CS_fsm[32'd1];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage1_11001 = ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_block_state2_pp0_stage1_iter0));
end

always @ (*) begin
    ap_block_pp0_stage1_subdone = ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_block_state2_pp0_stage1_iter0));
end

always @ (*) begin
    ap_block_state2_pp0_stage1_iter0 = ((ap_predicate_op67_read_state2 == 1'b1) & (in_stream_TVALID == 1'b0));
end

always @ (*) begin
    ap_condition_865 = ((ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln534_fu_472_p2 == 1'd1) & (icmp_ln532_fu_452_p2 == 1'd0));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage1;

always @ (*) begin
    ap_predicate_op67_read_state2 = ((icmp_ln534_reg_1047 == 1'd1) & (icmp_ln532_reg_1037 == 1'd0));
end

assign b_field_fu_687_p3 = {{trunc_ln107_reg_1094}, {lshr_ln107_1_reg_1089}};

assign cmp6_i_read_read_fu_252_p2 = cmp6_i;

assign g_field_fu_627_p3 = {{tmp_1_fu_617_p4}, {lshr_ln5_fu_607_p4}};

assign gray_2_fu_754_p4 = {{y_1_fu_749_p2[15:8]}};

assign gray_3_fu_769_p4 = {{y_2_fu_764_p2[15:8]}};

assign gray_4_fu_779_p3 = ((icmp_ln124_reg_1051_pp0_iter2_reg[0:0] == 1'b1) ? gray_fu_736_p4 : gray_7_reg_1069_pp0_iter1_reg);

assign gray_5_fu_785_p3 = ((cmp6_i[0:0] == 1'b1) ? gray_2_fu_754_p4 : gray_4_fu_779_p3);

assign gray_6_fu_802_p3 = ((and_ln124_fu_797_p2[0:0] == 1'b1) ? gray_3_fu_769_p4 : gray_5_fu_785_p3);

assign gray_7_fu_583_p1 = in_stream_TDATA[7:0];

assign gray_fu_736_p4 = {{y_fu_731_p2[15:8]}};

assign grp_fu_962_p0 = grp_fu_962_p00;

assign grp_fu_962_p00 = r_fu_653_p4;

assign grp_fu_962_p1 = 15'd77;

assign grp_fu_970_p0 = grp_fu_970_p00;

assign grp_fu_970_p00 = gray_7_fu_583_p1;

assign grp_fu_970_p1 = 13'd29;

assign grp_fu_970_p2 = 13'd128;

assign grp_fu_978_p0 = grp_fu_978_p00;

assign grp_fu_978_p00 = g_field_fu_627_p3;

assign grp_fu_978_p1 = 15'd77;

assign grp_fu_986_p0 = grp_fu_986_p00;

assign grp_fu_986_p00 = b_field_fu_687_p3;

assign grp_fu_986_p1 = 13'd29;

assign grp_fu_986_p2 = 13'd128;

assign grp_fu_995_p0 = grp_fu_995_p00;

assign grp_fu_995_p00 = r_field_fu_681_p3;

assign grp_fu_995_p1 = 15'd77;

assign hist0_1_d0 = add_ln542_fu_919_p2;

assign hist0_2_d0 = add_ln542_fu_919_p2;

assign hist0_3_d0 = add_ln542_fu_919_p2;

assign hist0_d0 = add_ln542_fu_919_p2;

assign hist1_1_d0 = add_ln548_fu_952_p2;

assign hist1_2_d0 = add_ln548_fu_952_p2;

assign hist1_3_d0 = add_ln548_fu_952_p2;

assign hist1_d0 = add_ln548_fu_952_p2;

assign icmp_ln124_1_fu_484_p2 = ((pixel_format == 32'd1) ? 1'b1 : 1'b0);

assign icmp_ln124_fu_478_p2 = ((pixel_format == 32'd2) ? 1'b1 : 1'b0);

assign icmp_ln532_fu_452_p2 = ((ap_sig_allocacmp_x_2 == 31'd640) ? 1'b1 : 1'b0);

assign icmp_ln534_fu_472_p2 = (($signed(zext_ln532_fu_468_p1) < $signed(frame_width)) ? 1'b1 : 1'b0);

assign icmp_ln538_1_fu_502_p2 = (($signed(zext_ln532_fu_468_p1) < $signed(ex0_1)) ? 1'b1 : 1'b0);

assign icmp_ln538_fu_490_p2 = (($signed(zext_ln532_fu_468_p1) < $signed(c_cx0_3)) ? 1'b1 : 1'b0);

assign icmp_ln544_1_fu_544_p2 = (($signed(zext_ln532_fu_468_p1) < $signed(ex1_1)) ? 1'b1 : 1'b0);

assign icmp_ln544_fu_532_p2 = (($signed(zext_ln532_fu_468_p1) < $signed(c_cx0)) ? 1'b1 : 1'b0);

assign lshr_ln5_fu_607_p4 = {{in_stream_TDATA[10:9]}};

assign mul_ln118_2_fu_707_p0 = mul_ln118_2_fu_707_p00;

assign mul_ln118_2_fu_707_p00 = g_reg_1104;

assign mul_ln118_2_fu_707_p1 = 16'd150;

assign mul_ln118_5_fu_713_p0 = mul_ln118_5_fu_713_p00;

assign mul_ln118_5_fu_713_p00 = r_field_reg_1119;

assign mul_ln118_5_fu_713_p1 = 16'd150;

assign mul_ln118_7_fu_722_p0 = mul_ln118_7_fu_722_p00;

assign mul_ln118_7_fu_722_p00 = g_field_reg_1084_pp0_iter1_reg;

assign mul_ln118_7_fu_722_p1 = 16'd150;

assign pix0_address1 = zext_ln540_fu_821_p1;

assign pix0_d1 = gray_6_fu_802_p3;

assign pix1_address1 = zext_ln546_fu_863_p1;

assign pix1_d1 = gray_6_fu_802_p3;

assign r_field_fu_681_p3 = {{tmp_s_reg_1079}, {lshr_ln4_reg_1074}};

assign r_fu_653_p4 = {{in_stream_TDATA[23:16]}};

assign sub_ln539_fu_812_p2 = (trunc_ln532_reg_1041_pp0_iter2_reg - empty_55);

assign sub_ln545_fu_854_p2 = (trunc_ln532_reg_1041_pp0_iter2_reg - empty);

assign tmp_1_fu_617_p4 = {{in_stream_TDATA[10:5]}};

assign tmp_3_fu_929_p9 = 'bx;

assign tmp_fu_896_p9 = 'bx;

assign trunc_ln107_fu_645_p1 = in_stream_TDATA[4:0];

assign trunc_ln532_fu_464_p1 = ap_sig_allocacmp_x_2[12:0];

assign trunc_ln541_1_fu_836_p4 = {{gray_6_fu_802_p3[7:4]}};

assign trunc_ln547_1_fu_878_p4 = {{gray_6_fu_802_p3[7:4]}};

assign xor_ln124_fu_792_p2 = (cmp6_i ^ 1'd1);

assign xor_ln538_fu_496_p2 = (icmp_ln538_fu_490_p2 ^ 1'd1);

assign xor_ln544_fu_538_p2 = (icmp_ln544_fu_532_p2 ^ 1'd1);

assign y_1_fu_749_p2 = (zext_ln118_11_fu_746_p1 + add_ln118_3_reg_1154);

assign y_2_fu_764_p2 = (zext_ln118_11_fu_746_p1 + grp_fu_995_p3);

assign y_fu_731_p2 = (zext_ln118_9_fu_728_p1 + add_ln118_reg_1144);

assign zext_ln118_11_fu_746_p1 = grp_fu_986_p3;

assign zext_ln118_9_fu_728_p1 = add_ln118_1_reg_1149;

assign zext_ln532_fu_468_p1 = ap_sig_allocacmp_x_2;

assign zext_ln540_fu_821_p1 = add_ln540_fu_816_p2;

assign zext_ln541_fu_846_p1 = trunc_ln541_1_fu_836_p4;

assign zext_ln546_fu_863_p1 = add_ln546_fu_858_p2;

assign zext_ln547_fu_888_p1 = trunc_ln547_1_fu_878_p4;

endmodule //eye_feature_eye_feature_Pipeline_FRAME_X
