// ==============================================================
// Generated by Vitis HLS v2023.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module eye_feature_percentile_threshold_Pipeline_FIND_BIN (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        hist_0_address0,
        hist_0_ce0,
        hist_0_q0,
        hist_1_address0,
        hist_1_ce0,
        hist_1_q0,
        hist_2_address0,
        hist_2_ce0,
        hist_2_q0,
        hist_3_address0,
        hist_3_ce0,
        hist_3_q0,
        zext_ln211,
        selected_out,
        selected_out_ap_vld
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [3:0] hist_0_address0;
output   hist_0_ce0;
input  [15:0] hist_0_q0;
output  [3:0] hist_1_address0;
output   hist_1_ce0;
input  [15:0] hist_1_q0;
output  [3:0] hist_2_address0;
output   hist_2_ce0;
input  [15:0] hist_2_q0;
output  [3:0] hist_3_address0;
output   hist_3_ce0;
input  [15:0] hist_3_q0;
input  [12:0] zext_ln211;
output  [29:0] selected_out;
output   selected_out_ap_vld;

reg ap_idle;
reg hist_0_ce0;
reg hist_1_ce0;
reg hist_2_ce0;
reg hist_3_ce0;
reg selected_out_ap_vld;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_idle_pp0;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln219_fu_174_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg   [0:0] found_reg_141;
wire   [31:0] zext_ln211_cast_fu_152_p1;
reg   [31:0] zext_ln211_cast_reg_336;
wire    ap_block_pp0_stage0_11001;
reg   [6:0] i_2_reg_341;
reg   [0:0] icmp_ln219_reg_347;
wire   [0:0] found_2_fu_299_p2;
wire    ap_loop_init;
wire   [63:0] zext_ln214_fu_196_p1;
wire    ap_block_pp0_stage0;
reg   [31:0] selected_fu_64;
wire   [31:0] selected_2_fu_283_p3;
reg   [31:0] cumulative_fu_68;
wire   [31:0] cumulative_1_fu_291_p3;
reg   [6:0] i_fu_72;
wire   [6:0] add_ln219_fu_180_p2;
reg   [6:0] ap_sig_allocacmp_i_2;
wire    ap_block_pp0_stage0_01001;
wire   [3:0] lshr_ln_fu_186_p4;
wire   [15:0] tmp_fu_226_p9;
wire   [1:0] tmp_fu_226_p10;
wire   [15:0] tmp_fu_226_p11;
wire   [31:0] zext_ln222_fu_250_p1;
wire   [31:0] cumulative_2_fu_254_p2;
wire   [0:0] icmp_ln223_fu_260_p2;
wire   [5:0] trunc_ln219_2_fu_223_p1;
wire   [0:0] found_1_fu_265_p2;
wire   [31:0] zext_ln223_fu_271_p1;
wire   [31:0] selected_4_fu_275_p3;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
reg    ap_condition_257;
wire   [1:0] tmp_fu_226_p1;
wire   [1:0] tmp_fu_226_p3;
wire  signed [1:0] tmp_fu_226_p5;
wire  signed [1:0] tmp_fu_226_p7;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 selected_fu_64 = 32'd0;
#0 cumulative_fu_68 = 32'd0;
#0 i_fu_72 = 7'd0;
#0 ap_done_reg = 1'b0;
end

eye_feature_sparsemux_9_2_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 2'h0 ),
    .din0_WIDTH( 16 ),
    .CASE1( 2'h1 ),
    .din1_WIDTH( 16 ),
    .CASE2( 2'h2 ),
    .din2_WIDTH( 16 ),
    .CASE3( 2'h3 ),
    .din3_WIDTH( 16 ),
    .def_WIDTH( 16 ),
    .sel_WIDTH( 2 ),
    .dout_WIDTH( 16 ))
sparsemux_9_2_16_1_1_U54(
    .din0(hist_0_q0),
    .din1(hist_1_q0),
    .din2(hist_2_q0),
    .din3(hist_3_q0),
    .def(tmp_fu_226_p9),
    .sel(tmp_fu_226_p10),
    .dout(tmp_fu_226_p11)
);

eye_feature_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
        if (((ap_loop_exit_ready == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_loop_exit_ready_pp0_iter1_reg <= 1'b0;
        end else if ((1'b0 == ap_block_pp0_stage0_11001)) begin
            ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            cumulative_fu_68 <= 32'd0;
        end else if (((icmp_ln219_reg_347 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            cumulative_fu_68 <= cumulative_1_fu_291_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
        if ((1'b1 == ap_condition_257)) begin
            found_reg_141 <= found_2_fu_299_p2;
        end else if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            found_reg_141 <= 1'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln219_fu_174_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            i_fu_72 <= add_ln219_fu_180_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            i_fu_72 <= 7'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            selected_fu_64 <= 32'd63;
        end else if (((icmp_ln219_reg_347 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            selected_fu_64 <= selected_2_fu_283_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        i_2_reg_341 <= ap_sig_allocacmp_i_2;
        icmp_ln219_reg_347 <= icmp_ln219_fu_174_p2;
        zext_ln211_cast_reg_336[12 : 0] <= zext_ln211_cast_fu_152_p1[12 : 0];
    end
end

always @ (*) begin
    if (((icmp_ln219_fu_174_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_i_2 = 7'd0;
    end else begin
        ap_sig_allocacmp_i_2 = i_fu_72;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        hist_0_ce0 = 1'b1;
    end else begin
        hist_0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        hist_1_ce0 = 1'b1;
    end else begin
        hist_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        hist_2_ce0 = 1'b1;
    end else begin
        hist_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        hist_3_ce0 = 1'b1;
    end else begin
        hist_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln219_reg_347 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        selected_out_ap_vld = 1'b1;
    end else begin
        selected_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln219_fu_180_p2 = (ap_sig_allocacmp_i_2 + 7'd1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_01001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_condition_257 = ((icmp_ln219_reg_347 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign cumulative_1_fu_291_p3 = ((found_reg_141[0:0] == 1'b1) ? cumulative_fu_68 : cumulative_2_fu_254_p2);

assign cumulative_2_fu_254_p2 = (cumulative_fu_68 + zext_ln222_fu_250_p1);

assign found_1_fu_265_p2 = (icmp_ln223_fu_260_p2 ^ 1'd1);

assign found_2_fu_299_p2 = (found_reg_141 | found_1_fu_265_p2);

assign hist_0_address0 = zext_ln214_fu_196_p1;

assign hist_1_address0 = zext_ln214_fu_196_p1;

assign hist_2_address0 = zext_ln214_fu_196_p1;

assign hist_3_address0 = zext_ln214_fu_196_p1;

assign icmp_ln219_fu_174_p2 = ((ap_sig_allocacmp_i_2 == 7'd64) ? 1'b1 : 1'b0);

assign icmp_ln223_fu_260_p2 = (($signed(cumulative_2_fu_254_p2) < $signed(zext_ln211_cast_reg_336)) ? 1'b1 : 1'b0);

assign lshr_ln_fu_186_p4 = {{ap_sig_allocacmp_i_2[5:2]}};

assign selected_2_fu_283_p3 = ((found_reg_141[0:0] == 1'b1) ? selected_fu_64 : selected_4_fu_275_p3);

assign selected_4_fu_275_p3 = ((found_1_fu_265_p2[0:0] == 1'b1) ? zext_ln223_fu_271_p1 : selected_fu_64);

assign selected_out = selected_fu_64[29:0];

assign tmp_fu_226_p10 = i_2_reg_341[1:0];

assign tmp_fu_226_p9 = 'bx;

assign trunc_ln219_2_fu_223_p1 = i_2_reg_341[5:0];

assign zext_ln211_cast_fu_152_p1 = zext_ln211;

assign zext_ln214_fu_196_p1 = lshr_ln_fu_186_p4;

assign zext_ln222_fu_250_p1 = tmp_fu_226_p11;

assign zext_ln223_fu_271_p1 = trunc_ln219_2_fu_223_p1;

always @ (posedge ap_clk) begin
    zext_ln211_cast_reg_336[31:13] <= 19'b0000000000000000000;
end

endmodule //eye_feature_percentile_threshold_Pipeline_FIND_BIN
