set_property PACKAGE_PIN B16 [get_ports echo_0]
set_property PACKAGE_PIN B15 [get_ports trig_0]
set_property IOSTANDARD LVCMOS33 [get_ports echo_0]
set_property IOSTANDARD LVCMOS33 [get_ports trig_0]

set_property MARK_DEBUG true [get_nets {design_1_i/myUltrasonic_0/inst/myUltrasonic_v1_0_S00_AXI_inst/Ultrasonic_inst/distance[1]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myUltrasonic_0/inst/myUltrasonic_v1_0_S00_AXI_inst/Ultrasonic_inst/distance[17]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myUltrasonic_0/inst/myUltrasonic_v1_0_S00_AXI_inst/Ultrasonic_inst/distance[19]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myUltrasonic_0/inst/myUltrasonic_v1_0_S00_AXI_inst/Ultrasonic_inst/distance[20]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myUltrasonic_0/inst/myUltrasonic_v1_0_S00_AXI_inst/Ultrasonic_inst/distance[7]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myUltrasonic_0/inst/myUltrasonic_v1_0_S00_AXI_inst/Ultrasonic_inst/distance[11]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myUltrasonic_0/inst/myUltrasonic_v1_0_S00_AXI_inst/Ultrasonic_inst/distance[12]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myUltrasonic_0/inst/myUltrasonic_v1_0_S00_AXI_inst/Ultrasonic_inst/distance[14]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myUltrasonic_0/inst/myUltrasonic_v1_0_S00_AXI_inst/Ultrasonic_inst/distance[0]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myUltrasonic_0/inst/myUltrasonic_v1_0_S00_AXI_inst/Ultrasonic_inst/distance[4]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myUltrasonic_0/inst/myUltrasonic_v1_0_S00_AXI_inst/Ultrasonic_inst/distance[5]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myUltrasonic_0/inst/myUltrasonic_v1_0_S00_AXI_inst/Ultrasonic_inst/distance[13]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myUltrasonic_0/inst/myUltrasonic_v1_0_S00_AXI_inst/Ultrasonic_inst/distance[15]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myUltrasonic_0/inst/myUltrasonic_v1_0_S00_AXI_inst/Ultrasonic_inst/distance[16]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myUltrasonic_0/inst/myUltrasonic_v1_0_S00_AXI_inst/Ultrasonic_inst/distance[18]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myUltrasonic_0/inst/myUltrasonic_v1_0_S00_AXI_inst/Ultrasonic_inst/distance[2]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myUltrasonic_0/inst/myUltrasonic_v1_0_S00_AXI_inst/Ultrasonic_inst/distance[3]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myUltrasonic_0/inst/myUltrasonic_v1_0_S00_AXI_inst/Ultrasonic_inst/distance[6]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myUltrasonic_0/inst/myUltrasonic_v1_0_S00_AXI_inst/Ultrasonic_inst/distance[8]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myUltrasonic_0/inst/myUltrasonic_v1_0_S00_AXI_inst/Ultrasonic_inst/distance[9]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myUltrasonic_0/inst/myUltrasonic_v1_0_S00_AXI_inst/Ultrasonic_inst/distance[10]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myUltrasonic_0/inst/myUltrasonic_v1_0_S00_AXI_inst/Ultrasonic_inst/distance[21]}]
set_property MARK_DEBUG true [get_nets design_1_i/myUltrasonic_0/inst/myUltrasonic_v1_0_S00_AXI_inst/Ultrasonic_inst/dist_valid]
set_property MARK_DEBUG true [get_nets design_1_i/myUltrasonic_0/inst/myUltrasonic_v1_0_S00_AXI_inst/Ultrasonic_inst/echo]
set_property MARK_DEBUG true [get_nets design_1_i/myUltrasonic_0/inst/myUltrasonic_v1_0_S00_AXI_inst/Ultrasonic_inst/error]
set_property MARK_DEBUG true [get_nets design_1_i/myUltrasonic_0/inst/myUltrasonic_v1_0_S00_AXI_inst/Ultrasonic_inst/trig]
set_property MARK_DEBUG true [get_nets design_1_i/myUltrasonic_0/inst/myUltrasonic_v1_0_S00_AXI_inst/trig]

create_debug_core u_ila_0 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_0]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property C_DATA_DEPTH 131072 [get_debug_cores u_ila_0]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_0]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
connect_debug_port u_ila_0/clk [get_nets [list design_1_i/processing_system7_0/inst/FCLK_CLK0]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property port_width 22 [get_debug_ports u_ila_0/probe0]
connect_debug_port u_ila_0/probe0 [get_nets [list {design_1_i/myUltrasonic_0/inst/myUltrasonic_v1_0_S00_AXI_inst/Ultrasonic_inst/distance[0]} {design_1_i/myUltrasonic_0/inst/myUltrasonic_v1_0_S00_AXI_inst/Ultrasonic_inst/distance[1]} {design_1_i/myUltrasonic_0/inst/myUltrasonic_v1_0_S00_AXI_inst/Ultrasonic_inst/distance[2]} {design_1_i/myUltrasonic_0/inst/myUltrasonic_v1_0_S00_AXI_inst/Ultrasonic_inst/distance[3]} {design_1_i/myUltrasonic_0/inst/myUltrasonic_v1_0_S00_AXI_inst/Ultrasonic_inst/distance[4]} {design_1_i/myUltrasonic_0/inst/myUltrasonic_v1_0_S00_AXI_inst/Ultrasonic_inst/distance[5]} {design_1_i/myUltrasonic_0/inst/myUltrasonic_v1_0_S00_AXI_inst/Ultrasonic_inst/distance[6]} {design_1_i/myUltrasonic_0/inst/myUltrasonic_v1_0_S00_AXI_inst/Ultrasonic_inst/distance[7]} {design_1_i/myUltrasonic_0/inst/myUltrasonic_v1_0_S00_AXI_inst/Ultrasonic_inst/distance[8]} {design_1_i/myUltrasonic_0/inst/myUltrasonic_v1_0_S00_AXI_inst/Ultrasonic_inst/distance[9]} {design_1_i/myUltrasonic_0/inst/myUltrasonic_v1_0_S00_AXI_inst/Ultrasonic_inst/distance[10]} {design_1_i/myUltrasonic_0/inst/myUltrasonic_v1_0_S00_AXI_inst/Ultrasonic_inst/distance[11]} {design_1_i/myUltrasonic_0/inst/myUltrasonic_v1_0_S00_AXI_inst/Ultrasonic_inst/distance[12]} {design_1_i/myUltrasonic_0/inst/myUltrasonic_v1_0_S00_AXI_inst/Ultrasonic_inst/distance[13]} {design_1_i/myUltrasonic_0/inst/myUltrasonic_v1_0_S00_AXI_inst/Ultrasonic_inst/distance[14]} {design_1_i/myUltrasonic_0/inst/myUltrasonic_v1_0_S00_AXI_inst/Ultrasonic_inst/distance[15]} {design_1_i/myUltrasonic_0/inst/myUltrasonic_v1_0_S00_AXI_inst/Ultrasonic_inst/distance[16]} {design_1_i/myUltrasonic_0/inst/myUltrasonic_v1_0_S00_AXI_inst/Ultrasonic_inst/distance[17]} {design_1_i/myUltrasonic_0/inst/myUltrasonic_v1_0_S00_AXI_inst/Ultrasonic_inst/distance[18]} {design_1_i/myUltrasonic_0/inst/myUltrasonic_v1_0_S00_AXI_inst/Ultrasonic_inst/distance[19]} {design_1_i/myUltrasonic_0/inst/myUltrasonic_v1_0_S00_AXI_inst/Ultrasonic_inst/distance[20]} {design_1_i/myUltrasonic_0/inst/myUltrasonic_v1_0_S00_AXI_inst/Ultrasonic_inst/distance[21]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property port_width 1 [get_debug_ports u_ila_0/probe1]
connect_debug_port u_ila_0/probe1 [get_nets [list design_1_i/myUltrasonic_0/inst/myUltrasonic_v1_0_S00_AXI_inst/Ultrasonic_inst/dist_valid]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
set_property port_width 1 [get_debug_ports u_ila_0/probe2]
connect_debug_port u_ila_0/probe2 [get_nets [list design_1_i/myUltrasonic_0/inst/myUltrasonic_v1_0_S00_AXI_inst/Ultrasonic_inst/echo]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe3]
set_property port_width 1 [get_debug_ports u_ila_0/probe3]
connect_debug_port u_ila_0/probe3 [get_nets [list design_1_i/myUltrasonic_0/inst/myUltrasonic_v1_0_S00_AXI_inst/Ultrasonic_inst/error]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe4]
set_property port_width 1 [get_debug_ports u_ila_0/probe4]
connect_debug_port u_ila_0/probe4 [get_nets [list design_1_i/myUltrasonic_0/inst/myUltrasonic_v1_0_S00_AXI_inst/Ultrasonic_inst/trig]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe5]
set_property port_width 1 [get_debug_ports u_ila_0/probe5]
connect_debug_port u_ila_0/probe5 [get_nets [list design_1_i/myUltrasonic_0/inst/myUltrasonic_v1_0_S00_AXI_inst/trig]]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets u_ila_0_FCLK_CLK0]
