// Copyright (C) 1991-2013 Altera Corporation
// Your use of Altera Corporation's design tools, logic functions 
// and other software and tools, and its AMPP partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Altera Program License 
// Subscription Agreement, Altera MegaCore Function License 
// Agreement, or other applicable license agreement, including, 
// without limitation, that your use is for the sole purpose of 
// programming logic devices manufactured by Altera and sold by 
// Altera or its authorized distributors.  Please refer to the 
// applicable agreement for further details.


// Generated by Quartus II 64-Bit Version 13.0 (Build Build 232 06/12/2013)
// Created on Thu Nov 07 09:04:29 2024

counter_74163 counter_74163_inst
(
	.clrn(clrn_sig) ,	// input  clrn_sig
	.ldn(ldn_sig) ,	// input  ldn_sig
	.enp(enp_sig) ,	// input  enp_sig
	.ent(ent_sig) ,	// input  ent_sig
	.clk(clk_sig) ,	// input  clk_sig
	.Q_in(Q_in_sig) ,	// input [3:0] Q_in_sig
	.Q_out(Q_out_sig) ,	// output [3:0] Q_out_sig
	.rco(rco_sig) 	// output  rco_sig
);

