// ==============================================================
// Generated by Vitis HLS v2023.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module classify_classify_Pipeline_MAC_LOOP (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        x_address0,
        x_ce0,
        x_q0,
        x_1_address0,
        x_1_ce0,
        x_1_q0,
        x_2_address0,
        x_2_ce0,
        x_2_q0,
        x_3_address0,
        x_3_ce0,
        x_3_q0,
        x_4_address0,
        x_4_ce0,
        x_4_q0,
        x_5_address0,
        x_5_ce0,
        x_5_q0,
        x_6_address0,
        x_6_ce0,
        x_6_q0,
        x_7_address0,
        x_7_ce0,
        x_7_q0,
        acc_out,
        acc_out_ap_vld
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [3:0] x_address0;
output   x_ce0;
input  [31:0] x_q0;
output  [3:0] x_1_address0;
output   x_1_ce0;
input  [31:0] x_1_q0;
output  [3:0] x_2_address0;
output   x_2_ce0;
input  [31:0] x_2_q0;
output  [3:0] x_3_address0;
output   x_3_ce0;
input  [31:0] x_3_q0;
output  [3:0] x_4_address0;
output   x_4_ce0;
input  [31:0] x_4_q0;
output  [3:0] x_5_address0;
output   x_5_ce0;
input  [31:0] x_5_q0;
output  [3:0] x_6_address0;
output   x_6_ce0;
input  [31:0] x_6_q0;
output  [3:0] x_7_address0;
output   x_7_ce0;
input  [31:0] x_7_q0;
output  [59:0] acc_out;
output   acc_out_ap_vld;

reg ap_idle;
reg x_ce0;
reg x_1_ce0;
reg x_2_ce0;
reg x_3_ce0;
reg x_4_ce0;
reg x_5_ce0;
reg x_6_ce0;
reg x_7_ce0;
reg acc_out_ap_vld;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_idle_pp0;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln87_fu_223_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire   [6:0] SVM_W_address0;
reg    SVM_W_ce0;
wire  signed [21:0] SVM_W_q0;
wire    ap_block_pp0_stage0_11001;
reg   [0:0] icmp_ln87_reg_356;
wire   [2:0] trunc_ln87_fu_240_p1;
reg   [2:0] trunc_ln87_reg_360;
wire   [52:0] mul_ln89_fu_206_p2;
reg   [52:0] mul_ln89_reg_410;
wire   [63:0] zext_ln87_fu_235_p1;
wire    ap_block_pp0_stage0;
wire   [63:0] zext_ln85_fu_254_p1;
reg   [59:0] acc_fu_74;
wire   [59:0] acc_1_fu_326_p2;
wire    ap_loop_init;
reg   [6:0] i_1_fu_78;
wire   [6:0] add_ln87_fu_229_p2;
reg   [6:0] ap_sig_allocacmp_i;
wire    ap_block_pp0_stage0_01001;
wire   [3:0] lshr_ln1_fu_244_p4;
wire   [31:0] tmp_fu_276_p17;
wire  signed [31:0] tmp_fu_276_p19;
wire  signed [59:0] sext_ln89_2_fu_323_p1;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire   [2:0] tmp_fu_276_p1;
wire   [2:0] tmp_fu_276_p3;
wire   [2:0] tmp_fu_276_p5;
wire   [2:0] tmp_fu_276_p7;
wire  signed [2:0] tmp_fu_276_p9;
wire  signed [2:0] tmp_fu_276_p11;
wire  signed [2:0] tmp_fu_276_p13;
wire  signed [2:0] tmp_fu_276_p15;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 acc_fu_74 = 60'd0;
#0 i_1_fu_78 = 7'd0;
#0 ap_done_reg = 1'b0;
end

classify_classify_Pipeline_MAC_LOOP_SVM_W_ROM_AUTO_1R #(
    .DataWidth( 22 ),
    .AddressRange( 120 ),
    .AddressWidth( 7 ))
SVM_W_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(SVM_W_address0),
    .ce0(SVM_W_ce0),
    .q0(SVM_W_q0)
);

classify_mul_32s_22s_53_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 22 ),
    .dout_WIDTH( 53 ))
mul_32s_22s_53_1_1_U13(
    .din0(tmp_fu_276_p19),
    .din1(SVM_W_q0),
    .dout(mul_ln89_fu_206_p2)
);

classify_sparsemux_17_3_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 3'h0 ),
    .din0_WIDTH( 32 ),
    .CASE1( 3'h1 ),
    .din1_WIDTH( 32 ),
    .CASE2( 3'h2 ),
    .din2_WIDTH( 32 ),
    .CASE3( 3'h3 ),
    .din3_WIDTH( 32 ),
    .CASE4( 3'h4 ),
    .din4_WIDTH( 32 ),
    .CASE5( 3'h5 ),
    .din5_WIDTH( 32 ),
    .CASE6( 3'h6 ),
    .din6_WIDTH( 32 ),
    .CASE7( 3'h7 ),
    .din7_WIDTH( 32 ),
    .def_WIDTH( 32 ),
    .sel_WIDTH( 3 ),
    .dout_WIDTH( 32 ))
sparsemux_17_3_32_1_1_U14(
    .din0(x_q0),
    .din1(x_1_q0),
    .din2(x_2_q0),
    .din3(x_3_q0),
    .din4(x_4_q0),
    .din5(x_5_q0),
    .din6(x_6_q0),
    .din7(x_7_q0),
    .def(tmp_fu_276_p17),
    .sel(trunc_ln87_reg_360),
    .dout(tmp_fu_276_p19)
);

classify_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
            acc_fu_74 <= 60'd1152921470117346443;
        end else if ((ap_enable_reg_pp0_iter2 == 1'b1)) begin
            acc_fu_74 <= acc_1_fu_326_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln87_fu_223_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            i_1_fu_78 <= add_ln87_fu_229_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            i_1_fu_78 <= 7'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        icmp_ln87_reg_356 <= icmp_ln87_fu_223_p2;
        mul_ln89_reg_410 <= mul_ln89_fu_206_p2;
        trunc_ln87_reg_360 <= trunc_ln87_fu_240_p1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        SVM_W_ce0 = 1'b1;
    end else begin
        SVM_W_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln87_reg_356 == 1'd1))) begin
        acc_out_ap_vld = 1'b1;
    end else begin
        acc_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln87_fu_223_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_i = 7'd0;
    end else begin
        ap_sig_allocacmp_i = i_1_fu_78;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        x_1_ce0 = 1'b1;
    end else begin
        x_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        x_2_ce0 = 1'b1;
    end else begin
        x_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        x_3_ce0 = 1'b1;
    end else begin
        x_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        x_4_ce0 = 1'b1;
    end else begin
        x_4_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        x_5_ce0 = 1'b1;
    end else begin
        x_5_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        x_6_ce0 = 1'b1;
    end else begin
        x_6_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        x_7_ce0 = 1'b1;
    end else begin
        x_7_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        x_ce0 = 1'b1;
    end else begin
        x_ce0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign SVM_W_address0 = zext_ln87_fu_235_p1;

assign acc_1_fu_326_p2 = ($signed(sext_ln89_2_fu_323_p1) + $signed(acc_fu_74));

assign acc_out = acc_fu_74;

assign add_ln87_fu_229_p2 = (ap_sig_allocacmp_i + 7'd1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_01001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign icmp_ln87_fu_223_p2 = ((ap_sig_allocacmp_i == 7'd120) ? 1'b1 : 1'b0);

assign lshr_ln1_fu_244_p4 = {{ap_sig_allocacmp_i[6:3]}};

assign sext_ln89_2_fu_323_p1 = $signed(mul_ln89_reg_410);

assign tmp_fu_276_p17 = 'bx;

assign trunc_ln87_fu_240_p1 = ap_sig_allocacmp_i[2:0];

assign x_1_address0 = zext_ln85_fu_254_p1;

assign x_2_address0 = zext_ln85_fu_254_p1;

assign x_3_address0 = zext_ln85_fu_254_p1;

assign x_4_address0 = zext_ln85_fu_254_p1;

assign x_5_address0 = zext_ln85_fu_254_p1;

assign x_6_address0 = zext_ln85_fu_254_p1;

assign x_7_address0 = zext_ln85_fu_254_p1;

assign x_address0 = zext_ln85_fu_254_p1;

assign zext_ln85_fu_254_p1 = lshr_ln1_fu_244_p4;

assign zext_ln87_fu_235_p1 = ap_sig_allocacmp_i;

endmodule //classify_classify_Pipeline_MAC_LOOP
